### ISSUE TITLE
DOC: Code Error in Self-RAG using local LLMs

### ISSUE THREAD

**Issue by unworld11** [langchain-ai/langgraph#1006]
### Issue with current documentation:

in the Graph State code
there is a spell error in the print statement which causes an error
<img width="650" alt="Screenshot 2024-07-13 at 12 15 04 AM" src="https://github.com/user-attachments/assets/b2e6c0bb-b773-40e4-868e-8a700ad4f7e3">

**Comment by unworld11** [comment]
@nfcampos if this issue can be assigned, i can do a small fix, i am starting my open source journey, this would help

**Comment by unworld11** [comment]
also at that point in tutorial, pprint is not imported also

**Comment by nfcampos** [comment]
Hi yes would be great to fix

**Comment by unworld11** [comment]
can you point me to the webpage source code, i tried finding it

**Comment by vbarda** [comment]
@unworld11 should be this one https://github.com/langchain-ai/langgraph/blob/main/examples/rag/langgraph_self_rag_local.ipynb. thanks!
