### ISSUE TITLE
web_voyager's add_conditional_edges lacks of conditional_edge_mapping 

### ISSUE THREAD

**Issue by roboticsocialism** [langchain-ai/langgraph#104]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

it seems that "graph_builder.add_conditional_edges("agent", select_tool)" missed one argument, and caused this error when putting in code (not notebook)
 graph_builder.add_conditional_edges("agent", select_tool)
TypeError: Graph.add_conditional_edges() missing 1 required positional argument: 'conditional_edge_mapping'
**********************************
original code is like following
graph_builder = StateGraph(AgentState)

graph_builder.add_node("agent", agent)
graph_builder.set_entry_point("agent")

graph_builder.add_node("update_scratchpad", update_scratchpad)
graph_builder.add_edge("update_scratchpad", "agent")

tools = {
    "Click": click,
    "Type": type_text,
    "Scroll": scroll,
    "Wait": wait,
    "GoBack": go_back,
    "Google": to_google,
}

for node_name, tool in tools.items():
    graph_builder.add_node(
        node_name,
        # The lambda ensures the function's string output is mapped to the "observation"
        # key in the AgentState
        RunnableLambda(tool) | (lambda observation: {"observation": observation}),
    )
    # Always return to the agent (by means of the update-scratchpad node)
    graph_builder.add_edge(node_name, "update_scratchpad")

def select_tool(state: AgentState):
    # Any time the agent completes, this function
    # is called to route the output to a tool or
    # to the end user.
    action = state["prediction"]["action"]
    if action == "ANSWER":
        return END
    if action == "retry":
        return "agent"
    return action

graph_builder.add_conditional_edges("agent", select_tool) <----------- here

graph = graph_builder.compile()

### Error Message and Stack Trace (if applicable)

TypeError: Graph.add_conditional_edges() missing 1 required positional argument: 'conditional_edge_mapping'

### Description

it seems that "graph_builder.add_conditional_edges("agent", select_tool)" missed one argument, and caused this error when putting in code (not notebook)
 graph_builder.add_conditional_edges("agent", select_tool)
TypeError: Graph.add_conditional_edges() missing 1 required positional argument: 'conditional_edge_mapping'

### System Info

Package Information
-------------------
> langchain_core: 0.1.22
> langchain: 0.1.6
> langchain_community: 0.0.19
> langsmith: 0.0.87
> langchain_cli: 0.0.20
> langchain_experimental: 0.0.50
> langchain_google_genai: 0.0.8
> langchain_google_vertexai: 0.0.5
> langchain_openai: 0.0.5
> langchainhub: 0.1.14
> langgraph: 0.0.24
> langserve: 0.0.37

**Comment by hinthornw** [comment]
@roboticsocialism , have you upgraded your local version of langgraph?

**Comment by hinthornw** [comment]
Going to close, as this is a version issue

**Comment by roboticsocialism** [comment]
> Going to close, as this is a version issue

yes, thanks a lot!
