### ISSUE TITLE
The bug report template has links to the langchain repository rather than langgraph

### ISSUE THREAD

**Issue by Glinte** [langchain-ai/langgraph#1040]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Description

On github go to Issues | New Issue, everything is linking to langchain.
![image](https://github.com/user-attachments/assets/c6b01f14-cbf5-41b7-8f09-6b8f1074a89e)
![image](https://github.com/user-attachments/assets/5ccaedad-3b91-4278-b71e-723e9a8ea162)

**Comment by vbarda** [comment]
Fixed in #1045
