### ISSUE TITLE
DOC: How to use with langserve playground?

### ISSUE THREAD

**Issue by russell-dot-js** [langchain-ai/langgraph#124]
### Issue with current documentation:

There doesn't appear to be any documentation anywhere on how to use langgraph with langserve playground. When using the Runnable returned from StateGraph.compile as part of a chain, and calling the langserve stream_log endpoint (this is the behavior of langserve playground), it appears that the graph is invoked a single time - I can see my entrypoint then delegating to a conditional edge, but that conditional edge never continues on to its next edge.

This looks like it might be caused by the error "Trying to load an object that doesn't implement serialization:", thrown by WellKnownLCSerializer.dumps in langserve.serialization. This could be caused by using a TypedDict state that doesn't implement toJSON, but the rabbit hole of errors is pretty difficult to navigate.

### Idea or request for content:

Include examples of how to use langgraph with langserve / playground, particular demonstrating how to customize the formatting of response / intermediate steps from your graph's state.

**Comment by russell-dot-js** [comment]
I actually just finished debugging what was going on and got it working. It turns out that astream_log will stop iterating down the graph if a node does not return a state update

The TLDR is that I haven't had the time to mess around with nested state / subgraphs just yet, so I'm mutating my nested state manually rather than returning a state update. Adding a no-op field to my state that I increment for each no-op resulted in astream_log running the graph to completion.

It is interesting that I've only seen this behavior when calling astream_log... astream and ainvoke seem to work just fine. Is this a bug, or a nuance of the inner workings of astream_log? Is it a bad practice to have a node that doesn't return state updates, or is this usage acceptable?

**Comment by hinthornw** [comment]
Possibly resolved in https://github.com/langchain-ai/langchain/issues/18741

**Comment by hinthornw** [comment]
Going to close as stale, since no one has added to this thread in 2 months
