### ISSUE TITLE
DOC: Passing State in Tools is no longer supported

### ISSUE THREAD

**Issue by streamnsight** [langchain-ai/langgraph#1241]
### Issue with current documentation:

https://langchain-ai.github.io/langgraph/how-tos/pass-run-time-values-to-tools/

this no longer works.

I wanted to point it out but also I'd like to know what is the alternative.

Right now I have been passing config to tools, but this is not ideal.
Is there a new way of passing state to tools? Thanks

**Comment by isahers1** [comment]
@streamnsight What error are you getting, and what version of LangGraph are you using?

**Comment by streamnsight** [comment]
just running the code, can't import InjectedState

<img width="829" alt="image" src="https://github.com/user-attachments/assets/b73fac73-bcb4-4dc4-b98e-598ef73ccecd">

Now I just upgraded and with 0.2.0 it works.
So, I guess the docs were published way before the code was released, because it was there a little while ago with 0.1.8, when it was the latest release, which is when I tried and it didn't work.
