### ISSUE TITLE
ToolNode doesn't support custom state classes

### ISSUE THREAD

**Issue by nfcampos** [langchain-ai/langgraph#1310]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

>I also realized I added a get method to the state class because ToolNode assumes your state is a TypedDict. This may also be another issue, but I haven't looked into it yet. In any case, I left the logging to show when it's accessing messages.

First reported in https://github.com/langchain-ai/langgraph-studio/issues/66

**Comment by hinthornw** [comment]
Mostly resolved in https://github.com/langchain-ai/langgraph/commit/28581e047a8f7dc8f9aac3c1550be6ffff43c2db

(though assumes your custom state can coerce from dict)
