### ISSUE TITLE
DOC: filter_message code is wrong

### ISSUE THREAD

**Issue by streamnsight** [langchain-ai/langgraph#1314]
### Issue with current documentation:

simple issue, but worth pointing out

the code here:
https://langchain-ai.github.io/langgraph/how-tos/memory/manage-conversation-history/#filtering-messages

```def filter_messages(messages: list):
    # This is very simple helper function which only ever uses the last two messages
    return messages[-1:]

```
actually returns the last message, not the last 2.
last 2 would be `messages[-2:]`

**Comment by vbarda** [comment]
this actually needs to be `messages[-1:]`

**Comment by streamnsight** [comment]
@vbarda 

messages[-1:] gives the last message
last 2 is messages[-2:]
```
>>> a = [1,2,3,4,5]
>>> a[-2:]
[4, 5]
>>> a[-1:]
[5]
```

so if the function is to return last 2 as described, then is is messages[-2:]

**Comment by vbarda** [comment]
the description was wrong

**Comment by vbarda** [comment]
see https://github.com/langchain-ai/langgraph/pull/1438

**Comment by gbaian10** [comment]
I previously thought that this tutorial example was meant to include only the first two sentences of the historical dialogue record, not all the dialogue, until I saw that the final run included this:

```py
# This will now not remember the previous messages
# (because we set `messages[-1:]` in the filter messages argument)
input_message = HumanMessage(content="what's my name?")
for event in app.stream({"messages": [input_message]}, config, stream_mode="values"):
    event["messages"][-1].pretty_print()
```

In that case, indeed, just updating the comments within the filter is enough.

**Comment by shaikhn1750** [comment]
how to use 

```
def filter_messages(messages: list):
    # This is very simple helper function which only ever uses the last message
    return messages[-1:]


# Define the function that calls the model
def call_model(state: MessagesState):
    messages = filter_messages(state["messages"])
    response = bound_model.invoke(messages)
    # We return a list, because this will get added to the existing list
    return {"messages": response}
```

in multi agent supervisor scenario?
