### ISSUE TITLE
The minimum supported Python version for this project

### ISSUE THREAD

**Issue by gbaian10** [langchain-ai/langgraph#1366]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Description

The [pyproject.toml in the root directory](https://github.com/gbaian10/langgraph/blob/main/pyproject.toml#L10) specifies that this project requires a Python version greater than `3.10`.
But the [pyproject.toml files in the libs directory](https://github.com/gbaian10/langgraph/blob/main/libs/langgraph/pyproject.toml#L11) indicate that the project only requires a Python version greater than `3.9`.

Which one is correct?
I see Python 3.9 testing in the CI, so is it the root directory that's incorrect?

**Comment by vbarda** [comment]
@gbaian10 the pyproject in the root directory is for the monorepo and is only used for building docs. it's not used by the actual libraries, so 3.9 is the correct minimum version for libraries. i'll adjust for simplicity to minimize confusion!
