### ISSUE TITLE
KeyError encountered: '__start__

### ISSUE THREAD

**Issue by anshulbhide** [langchain-ai/langgraph#1377]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
import os
import streamlit as st
from langchain.agents import Tool
import openai
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool

# Set environment variables
os.environ["OPENAI_API_KEY"] = "your_openai_api_key"
os.environ['LANGCHAIN_TRACING_V2'] = 'true'
os.environ['LANGCHAIN_ENDPOINT'] = "https://api.smith.langchain.com"
os.environ['LANGCHAIN_PROJECT'] = "agent scraper"
os.environ['LANGCHAIN_API_KEY'] = "your_langchain_api_key"

from typing import TypedDict, Annotated
from langchain_core.agents import AgentAction
from langchain_core.messages import BaseMessage
import operator

class AgentState(TypedDict):
    input: str
    chat_history: list[BaseMessage]
    intermediate_steps: Annotated[list[tuple[AgentAction, str]], operator.add]

from serpapi import GoogleSearch

@tool("web_search")
def web_search(name: str):
    """Finds general knowledge information using Google search."""
    serpapi_params = {
        "engine": "google",
        "api_key": "your_serpapi_api_key"
    }
    search = GoogleSearch({
        **serpapi_params,
        "q": name
    })
    results = search.get_dict()
    organic_results = results.get("organic_results", [])

    contexts = []
    for result in organic_results:
        title = result.get("title", "No Title")
        snippet = result.get("snippet", "No Description")
        link = result.get("link", "No Link")

        context = f"{title}\n{snippet}\n{link}\n---"
        contexts.append(context)

    final_context = "\n".join(contexts)
    return final_context

@tool("final_answer")
def final_answer(introduction: str, research_steps: str, main_body: str, conclusion: str, sources: str):
    if type(research_steps) is list:
        research_steps = "\n".join([f"- {r}" for r in research_steps])
    if type(sources) is list:
        sources = "\n".join([f"- {s}" for s in sources])
    return ""

from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import ToolCall, ToolMessage
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(model="gpt-4o", temperature=0.2)
tools = [web_search]

from langgraph.graph import StateGraph, END

graph = StateGraph(AgentState)
graph.add_node("oracle", lambda state: {"next": "next_function_name"})
# Define other nodes and edges as per your graph logic

print("Initial state:", {})
```

### Error Message and Stack Trace (if applicable)

```shell
Initial state: {'__start__': 'oracle', 'input': 'https://www.linkedin.com/in/anshul-bhide-26a96026/', 'chat_history': [], 'intermediate_steps': []}
KeyError encountered: '__start__'
Traceback (most recent call last):
  File "/home/runner/langchain-agent-profile-viewer/main.py", line 340, in <module>
    output=out["intermediate_steps"][-1].tool_input
NameError: name 'out' is not defined. Did you mean: 'oct'?
```

### Description

I am using Langchain to build an agent with several tools (linkedin_search, web_search, and final_answer).
The error occurs when invoking the compiled runnable graph using the invoke method.
The graph uses an initial state that includes the input, chat_history, and intermediate_steps keys. The start key is intended to trigger the start of the graph, but it seems the graph is not handling this key properly.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #27~22.04.1-Ubuntu SMP Tue Jul 16 23:03:39 UTC 2024
> Python Version:  3.10.14 (main, Mar 19 2024, 21:46:16) [GCC 13.2.0]

Package Information
-------------------
> langchain_core: 0.2.9
> langchain: 0.2.5
> langchain_community: 0.2.12
> langsmith: 0.1.81
> langchain_cohere: 0.1.5
> langchain_openai: 0.1.9
> langchain_pinecone: 0.1.1
> langchain_text_splitters: 0.2.1
> langchainhub: 0.1.21
> langgraph: 0.1.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langserve

**Comment by gbaian10** [comment]
Is this from the documentation of a URL? Otherwise, it's hard to understand what you did without enough context.

**Comment by nfcampos** [comment]
`NameError: name 'out' is not defined. Did you mean: 'oct'?` this seems like an issue in your code, we don't have any such variables anywhere in the library

**Comment by anshulbhide** [comment]
Okay - so it worked when I updated to langgraph-0.2.14. Thanks!
