### ISSUE TITLE
Visualized graph has wrong conditional edges

### ISSUE THREAD

**Issue by minki-j** [langchain-ai/langgraph#1394]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
from langgraph.graph import END, StateGraph
from langgraph.checkpoint.memory import MemorySaver
from langchain_core.runnables import RunnablePassthrough
from typing import TypedDict

class State(TypedDict):
    current_step: int
    total_number_of_steps: int

g = StateGraph(State)
g.set_entry_point("entry")

g.add_node("entry", RunnablePassthrough())
g.add_edge("entry", "A")

g.add_node("A", RunnablePassthrough())
g.add_edge("A", "B")

g.add_node("B", RunnablePassthrough())
g.add_edge("B", "reduce_middle_step")

g.add_node("reduce_middle_step", RunnablePassthrough())
g.add_conditional_edges(
    "reduce_middle_step",
    lambda state: (
        END if state["current_step"] >= state["total_number_of_steps"] else "A"
    ),
)

main_graph = g.compile(checkpointer=MemorySaver(), interrupt_after=["B"])


with open("./main_graph.png", "wb") as f:
    f.write(main_graph.get_graph().draw_mermaid_png())
```

### Error Message and Stack Trace (if applicable)

```shell
The graph diagram has unspecified connections
```

### Description

Run the code and check the image generated.
It has conditional edges from "recude_middle_step" to "entry", "A", and "B" where I only connected to "A". 
![main_graph](https://github.com/user-attachments/assets/f1d046e7-bd4d-4246-b8d3-11a8084922e3)

### System Info

not required.

**Comment by gbaian10** [comment]
You can refer to the reply in #987.
![image](https://github.com/user-attachments/assets/4ff0560e-af90-4f1a-af32-9d21c26e4901)

**Comment by minki-j** [comment]
> You can refer to the reply of this issue:
> 
> * [`add_conditional_edges` does not work without optional argument `path_map` #987](https://github.com/langchain-ai/langgraph/issues/987).
> 
> Or check the description in the docstring.
> 
> ![image](https://private-user-images.githubusercontent.com/34255899/359305832-4ff0560e-af90-4f1a-af32-9d21c26e4901.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjI0MTYsIm5iZiI6MTcyNDE2MjExNiwicGF0aCI6Ii8zNDI1NTg5OS8zNTkzMDU4MzItNGZmMDU2MGUtYWY5MC00ZjFhLWFmMzItOWQyMWMyNmU0OTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDEzNTUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZTkyN2MzYWE0ZmNiYzQwZTMxODE2ZDNkZWFiN2Y1YmFhYmEyMTk1YzkyNTkwMWFkOGZjMDBiZTM5MDU0NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9M-zgN6ZkWbPb8IA_f2tnQGMiS6_MfuAPfnl7oQ-FR0)

Thank you!!

**Comment by vbarda** [comment]
+1, thank you @gbaian10 ! we would also love to invite you to join LangChain Community on Slack if you're interested / haven't done it yet! https://www.langchain.com/join-community

**Comment by gbaian10** [comment]
@vbarda Thank you, I have successfully joined. I never knew there was such a great place. 😳
