### ISSUE TITLE
langgraph.pregel.GraphRecursionError: Recursion limit of 25 reachedwithout hitting a stop condition. You can increase the limitby setting the `recursion_limit` config key.

### ISSUE THREAD

**Issue by haolxx** [langchain-ai/langgraph#148]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

do you know typically what is the root cause of this error and how to resolve it? Thanks.

langgraph.pregel.GraphRecursionError: Recursion limit of 25 reachedwithout hitting a stop condition. You can increase the limitby setting the `recursion_limit` config key.

### Error Message and Stack Trace (if applicable)

do you know typically what is the root cause of this error and how to resolve it? Thanks.

langgraph.pregel.GraphRecursionError: Recursion limit of 25 reachedwithout hitting a stop condition. You can increase the limitby setting the `recursion_limit` config key.

### Description

do you know typically what is the root cause of this error and how to resolve it? Thanks.

langgraph.pregel.GraphRecursionError: Recursion limit of 25 reachedwithout hitting a stop condition. You can increase the limitby setting the `recursion_limit` config key.

### System Info

python 311

**Comment by yunfan42** [comment]
Same Question on running the cookbook "langgraph_self_rag.ipynb"

**Comment by yunfan42** [comment]
Same Question on Running cookbook [LangGraph-Self-RAG](https://github.com/langchain-ai/langgraph/blob/main/examples/rag/langgraph_self_rag.ipynb?ref=blog.langchain.dev)

add config in app works for me 

`for output in app.stream(inputs,config={"recursion_limit":100}):`

**Comment by nfcampos** [comment]
Yes you can set a higher recursion limit if you wish to loop for longer

**Comment by hardiknahata** [comment]
If I type a question which is **not** related to the documents, then the graph keeps looping between:
`'retrieve' -> `grade_documents` -> `transform_query``
As it isn't finding any relevant documents even after query transformation, it will end up looping and hitting the recursion limit of 25 or whatever is set.

I would like to raise a PR to handle this issue, **would that be a useful addition?**
