### ISSUE TITLE
langgraph prebuilt NOT work

### ISSUE THREAD

**Issue by jackiezhangcn** [langchain-ai/langgraph#150]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
 from langgraph.prebuilt.tool_executor import ToolExecutor, ToolInvocation
```

### Error Message and Stack Trace (if applicable)

  File "/home/zhangyj/langchain/langgraph.py", line 23, in <module>
    from langgraph.prebuilt.tool_executor import ToolExecutor, ToolInvocation
ModuleNotFoundError: No module named 'langgraph.prebuilt'; 'langgraph' is not a package

### Description

I followed the instructions, trying to run langgraph, but it seems the package can't work as expect

### System Info

 pip freeze | grep langgraph
langgraph==0.0.26
platform (Ubuntu)
python 3.10

**Comment by kevcmk** [comment]
I'm seeing this too. Neither a file nor a variable named langgraph in my entire project.
