### ISSUE TITLE
InvalidUpdateError raised in graph.astream() when given a list of HumanMessage

### ISSUE THREAD

**Issue by niklasmartin** [langchain-ai/langgraph#1511]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code
For easy reproduction, I added the exact same code of the tutorial to a Google Collab, where I encounter the same error:

https://colab.research.google.com/drive/1fxIsAfZkLjWumc_HJfymTgiUYZkUjO3q?usp=sharing

But this is a minimal example:
```python
from langchain_core.messages import HumanMessage
from langgraph.graph import StateGraph
from typing_extensions import TypedDict
from typing import Annotated, List
from langgraph.graph.message import add_messages
import asyncio


class State(TypedDict):
    messages: Annotated[List[HumanMessage], add_messages]


async def dummy_node(state: State):
    return state


builder = StateGraph(State)
builder.add_node("dummy", dummy_node)
builder.add_edge("dummy", "dummy")
graph = builder.compile()


async def main():
    async for event in graph.astream([HumanMessage(content="This is a test message")]):
        print(event)


if __name__ == "__main__":
    asyncio.run(main())

```

### Error Message and Stack Trace (if applicable)

```shell
----> 1 async for event in graph.astream(
      2     [
      3         HumanMessage(
      4             content="Generate an essay on the topicality of The Little Prince and its message in modern life"
      5         )

8 frames
/usr/local/lib/python3.10/dist-packages/langgraph/graph/state.py in _get_state_key(input, config, key)
    541                 return value if value is not None else SKIP_WRITE
    542             else:
--> 543                 raise InvalidUpdateError(f"Expected dict, got {input}")
    544 
    545         # state updaters

InvalidUpdateError: Expected dict, got [HumanMessage(content='Generate an essay on the topicality of The Little Prince and its message in modern life')]
```

### Description

I'm trying to reproduce the Basic Reflection notebook. However, in all environments I tested (Python 3.10 - 3.12, notebook and package environment) I get a InvalidUpdateError: Expected dict, got [HumanMessage(content="...")].

What exactly does the astream() method expect? The type signature Union[dict[str, Any], Any] and the description "The input to the graph." is not very specific imO

### System Info

langchain==0.2.14
langchain-core==0.2.35
langchain-openai==0.1.22
langchain-text-splitters==0.2.2

mac m3

Python 3.12.4

**Comment by vbarda** [comment]
Thanks for reporting -- fixed in https://github.com/langchain-ai/langgraph/pull/1512
Since the state is actually a dictionary with a `messages` key, the input should be `{"messages": [...]}`

**Comment by niklasmartin** [comment]
Thanks for reacting so quickly, I tried this as well. 

This, however, leads to a ValueError:
```ValueError: variable messages should be a list of base messages, got {'messages': [HumanMessage(content='Generate an essay on the topicality of The Little Prince and its message in modern life', id='18eaa929-6ce5-4a7d-9c82-eab714702329')]} of type <class 'dict'>```

Do you know what I'm still doing wrong?

**Comment by niklasmartin** [comment]
But this is exactly what I'm doing in the demo notebook on Google Collab:

https://colab.research.google.com/drive/1fjZRWLtVgwyBmZMqOM-2NbfH1R-45mSW?usp=sharing

I install and import the latest versions and use exactly the same code as in the tutorial. I understand that I can have mismatches in my local environments, but this is already very isolated, no?

**Comment by niklasmartin** [comment]
You're awesome, thanks. Will check it out after some meetings^^

**Comment by niklasmartin** [comment]
Now it works, thanks again for the support
