### ISSUE TITLE
Error In Postgres db connection code 

### ISSUE THREAD

**Issue by vigneshmj1997** [langchain-ai/langgraph#1529]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python

import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool
from langgraph.checkpoint.postgres import PostgresSaver


DATABASE_URL = "postgresql://user:password@localhost:5432/mydatabase"

connection_kwargs = {
    "autocommit": True,
    "prepare_threshold": 0,
}
pool = ConnectionPool(
    conninfo=DATABASE_URL, 
    kwargs= connection_kwargs,
    max_size=20)

def get_db():
    with pool.connection() as conn:
        yield conn





@cv_app.post("/message")
def get_response(request: ChatModel, conn: psycopg.Connection = Depends(get_db)):

    thread_id = request.thread
    config={"configurable": {"thread_id": thread_id}}

    logger.info(f"Poool {pool}")
    checkpointer = PostgresSaver(conn)
    output = checkpointer.get(config=config)
```

### Error Message and Stack Trace (if applicable)

```shell
File "C:\Users\MOL\miniconda3\envs\bot_v2\Lib\site-packages\langgraph\checkpoint\base\__init__.py", line 236, in get
    if value := self.get_tuple(config):
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MOL\miniconda3\envs\bot_v2\Lib\site-packages\langgraph\checkpoint\postgres\__init__.py", line 214, in get_tuple
    "checkpoint_id": value["checkpoint_id"],
```

### Description

I am trying to get the data from the postgres based on the config but there seems to be error in the postgres part of code in langgraph 

### System Info

There are the versions i am using 
psycopg==3.2.1
psycopg-binary==3.2.1
psycopg-pool==3.2.2
langchain-postgres==0.0.9
langgraph==0.2.14
langgraph-checkpoint==1.0.6
langgraph-checkpoint-postgres==1.0.3

I am using the lastest version of postgres as docker in my system

**Comment by vbarda** [comment]
you're using an old version of `langgraph-checkpoint-postgres` -- please update. the issue is related to the use of `row_factory=dict_row` which was required to pass before in connection kwargs, but now is automatically passed in the latest version

**Comment by vigneshmj1997** [comment]
The reason it occurred was . On installation with of langgraph-postgres using poetry. Poetry version control installs langgraph-checkpoint-postgres==1.0.3 and not langgraph-checkpoint-postgres==1.0.4
