### ISSUE TITLE
Unable to trace with Langsmith when using async code

### ISSUE THREAD

**Issue by sirjan-ws-ext** [langchain-ai/langgraph#1542]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
from typing import Literal

from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langgraph.graph import StateGraph, MessagesState
from langgraph.prebuilt import ToolNode

@tool
async def search(query: str):
    """Call to surf the web."""
    if "sf" in query.lower() or "san francisco" in query.lower():
        return "It's 60 degrees and foggy."
    return "It's 90 degrees and sunny."

tools = [search]

tool_node = ToolNode(tools)

model = ChatOpenAI(model="gpt-4o", temperature=0).bind_tools(tools)

async def should_continue(state: MessagesState) -> Literal["tools", "__end__"]:
    messages = state['messages']
    last_message = messages[-1]
    if last_message.tool_calls:
        return "tools"
    return "__end__"


async def call_model(state: MessagesState):
    messages = state['messages']

    # Invoking `model` will automatically infer the correct tracing context
    response = await model.ainvoke(messages)
    return {"messages": [response]}


workflow = StateGraph(MessagesState)

workflow.add_node("agent", call_model)
workflow.add_node("tools", tool_node)

workflow.add_edge("__start__", "agent")
workflow.add_conditional_edges(
    "agent",
    should_continue,
)
workflow.add_edge("tools", 'agent')

app = workflow.compile()

async def main():
    final_state = await app.ainvoke(
        {"messages": [HumanMessage(content="what is the weather in sf")]},
        config={"configurable": {"thread_id": 22242}}
    )
    print(final_state["messages"][-1].content)

import asyncio
asyncio.run(main())
```

### Description

I am trying langgraph with langsmith for tracing,
using this code in the langsmith-langgraph guide: https://docs.smith.langchain.com/how_to_guides/tracing/trace_with_langgraph#2-log-a-trace-1

As the above code is synchronous, all works out well, but when I shift to async, my traces arent grouped, the chat model, tool, langraph are all separate

<img width="1080" alt="Screenshot 2024-08-30 at 6 27 57 AM" src="https://github.com/user-attachments/assets/97f2a595-4df3-4005-9822-454dc61e1086">

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030
> Python Version:  3.10.13 (main, Dec 17 2023, 21:51:58) [Clang 15.0.0 (clang-1500.1.0.2.5)]

Package Information
-------------------
> langchain_core: 0.2.26
> langchain: 0.2.11
> langchain_community: 0.2.10
> langsmith: 0.1.104
> langchain_anthropic: 0.1.23
> langchain_openai: 0.1.20
> langchain_text_splitters: 0.2.2
> langchainhub: 0.1.21
> langgraph: 0.1.17

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langserve

**Comment by hinthornw** [comment]
Python < 3.11 doesn't support contextvar propagation in asyncio; I'd recommend either using a more recent version of python or manually passing the config through
