### ISSUE TITLE
[LATS example] Use recursive best candidate selection in the tree

### ISSUE THREAD

**Issue by zhiyanliu** [langchain-ai/langgraph#159]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

The function `expand(state: TreeState, config: RunnableConfig)` code in the example at [0], only the directed children nodes of the root are considered the UCT values to extend.

[0] https://github.com/langchain-ai/langgraph/blob/main/examples/lats/lats.ipynb

### Error Message and Stack Trace (if applicable)

In the extreme case, the error recursion limit reached of the graph/pregel could be triggered.

### Description

First, thanks for building these awesome assets and the example code!

IIUC on the Language Agents Tree Search approach described in the blog [0], for each node in the tree, should not only consider the UCT values of its direct children, but also recursively consider the UCT values of all descendant nodes, in order to find the best candidate to extend (before the max search depth is reached) with the highest UCT value in the entire tree.

so I consider a fix is:
```python
# best_candidate: Node = root.best_child if root.children else root    # should be replaced by the following
best_candidate: Node = root
while best_candidate.children:
    best_candidate = best_candidate.best_child
```

[0] https://blog.langchain.dev/reflection-agents/

If I understand anything wrong, pls let me know.

zhiyan

### System Info

langchain==0.1.9
langchain-community==0.0.21
langchain-core==0.1.27
langchain-experimental==0.0.52
langchain-openai==0.0.8
langchainhub==0.1.14
langgraph==0.0.26

platform: mac
python: 3.11.7

**Comment by zhiyanliu** [comment]
Hi @hinthornw , could you pls confirm if I have understood you correctly? If so, I'd like to prepare a small PR to address that issue, thanks.

**Comment by hinthornw** [comment]
Ya that's a good observation - I'll land a fix
