### ISSUE TITLE
DOC: format_tool_to_openai_function is deprecated

### ISSUE THREAD

**Issue by Xtrah** [langchain-ai/langgraph#160]
### Issue with current documentation:

`langchain.tools.render.format_tool_to_openai_function()` is used several places in docs and examples, and is planned for deprecation in LangChain v0.2.0.

### Idea or request for content:

Replace all use cases with the alternative `langchain_core.utils.function_calling.convert_to_openai_tool()`, and check other deprecations planned in 0.2.0 in `langchain_core.utils.function_calling`.

**Comment by hinthornw** [comment]
Ya we plan to change when we get the time. Would be happy to review a PR if anyone makes one here!

**Comment by hinthornw** [comment]
Should be updated now
