### ISSUE TITLE
Debug mode of create_react_agent does not work after upgrading to the latest version

### ISSUE THREAD

**Issue by Valdanitooooo** [langchain-ai/langgraph#1632]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
create_react_agent(
    model=llm,
    tools=[
        *tools(),
    ],
    state_modifier=system_message,
    debug=True,
)
```

### Error Message and Stack Trace (if applicable)

```shell
agent = create_react_agent(
    model=llm,
    tools=[
        *tools(),
    ],
    state_modifier=system_message,
    debug=True,
)

agent.astream(input={"messages": messages})
```

### Description

No debug log output

### System Info

langgraph==0.2.18

**Comment by Valdanitooooo** [comment]
After testing, this issue started with version 0.2.17.

**Comment by vbarda** [comment]
@Valdanitooooo i cannot reproduce the issue on the latest version of langgraph -- i see debug log outputs. i would recommend re-installing it in a fresh virtual environment and double-checking. will close for now but let me know if that doesn't help and you're still seeing issues

**Comment by x-arturs** [comment]
@vbarda I stopped getting debug log outputs as well after upgrading to the latest langgraph version (0.2.22). I tried reinstalling it in a fresh virtual environment but this didn't help either. I'm using Python 3.12.2.

**Comment by Valdanitooooo** [comment]
I reinstalled the virtual environment and installed version 0.2.38, but it still doesn't work.
