### ISSUE TITLE
No longer possible to have default value in graph State >=0.2.15

### ISSUE THREAD

**Issue by Freezaa9** [langchain-ai/langgraph#1662]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
import operator
from typing import Literal, Annotated, TypedDict, Optional, List
from langchain_core.pydantic_v1 import BaseModel, Field, validator
from langchain_core.chat_history import BaseChatMessageHistory
from langchain_core.documents import Document
from langchain_core.messages import BaseMessage, AIMessage
from langchain_core.output_parsers import StrOutputParser, PydanticOutputParser
from langgraph.graph import END, START, StateGraph, MessagesState

class MyState(TypedDict):
    query: str
    rephrase_query: str = None
    session_id: str
    documents: Annotated[list[Document], operator.add]
    messages: list[BaseMessage]
    chat_tosummarize: str
    chat_summary: str = "lol"
    output_graph: Optional[AIMessage] = None
    intent: Optional[BaseModel]
    guardrails_triggered: Optional[bool] = False

# Define the function that calls the model
def test(state: TypedDict):
    print(state['chat_summary'])
    print(state['guardrails_triggered'])
    return {"output_graph": "hello"}

# Define a new graph
workflow = StateGraph(MyState)
workflow.add_node("test", test)
workflow.add_edge(START, "test")
workflow.add_edge("test", END)

app = workflow.compile()

app.invoke({"query":"hello"})
```

### Error Message and Stack Trace (if applicable)

```shell
KeyError: 'chat_summary'
```

### Description

Hello,

From langgraph==0.2.15 it is no longer possible to set default value in state like in my example.
I used to set my state like that and use default value from my state into my nodes. 

I believe this change in the 0.2.15 release note is the cause of the issue:
Remove None default for missing keys when generating input for each node

It is an intended behavior ? Or there is an alternative way to do this ?

Thanks for your help :)

### System Info

windows/linux
Python 3.11.9

**Comment by hinthornw** [comment]
Hi @Freezaa9 , apologies for the change!

TypedDict's don't support default values (never have), though we used to create `null` values for all channels (making them appear like total=True), however, since that creates unexpected behavior when interacting with dataclasses and pydantic as state, we stopped doing that (making it appear like total=False)

**Comment by Freezaa9** [comment]
OK thanks @hinthornw  !

So if I want default value, I can use pydantic model like that:
Note:
Information available here: https://langchain-ai.github.io/langgraph/concepts/low_level/#schema
example: https://langchain-ai.github.io/langgraph/how-tos/state-model/#how-to-use-pydantic-model-as-state

```
from pydantic import BaseModel
class MyState(BaseModel):
    query: str
    rephrase_query: Optional[str] = None
    session_id: str
    documents: Annotated[list[Document], operator.add] = None
    messages: Optional[list[BaseMessage]] = None
    chat_tosummarize: Optional[str] = None
    chat_summary: Optional[str] = None
    output_graph: Optional[AIMessage] = None
    intent: Optional[BaseModel] = None
    guardrails_triggered: Optional[bool] = False
```
