### ISSUE TITLE
custom checkpointers notebooks under examples are not working. I get errors for all 3 custom examples

### ISSUE THREAD

**Issue by shivachittamuru** [langchain-ai/langgraph#1668]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
from langgraph.checkpoint.postgres import PostgresSaver
```

### Error Message and Stack Trace (if applicable)

```shell
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: libpq library not found
```

### Description

I installed all the necessary packages as mentioned in the notebooks

`pip install -U psycopg psycopg-pool langgraph langgraph-checkpoint-postgres`

### System Info

I created a conda environment (Windows) and installed all the necessary packages there.

**Comment by vbarda** [comment]
hm, looks like the dependencies did not install correctly -- i would suggest checking out this documentation https://www.psycopg.org/psycopg3/docs/basic/install.html#. you can also try running `pip install "psycopg[binary]"` and see if this solves your issue

**Comment by vbarda** [comment]
glad that worked! did you call `checkpointer.setup()`

**Comment by vbarda** [comment]
also, going to close this issue as it was resolved, but feel free to add more questions here!

**Comment by shivachittamuru** [comment]
My customer and I are still facing this issue. One of my colleagues tried it and he is facing the same issue as me. I did call `checkpointer.setup()` if you check my issue description again.

I tried RedisSaver and SqliteSaver, and they are working fine with "graph.invoke(...)" code, but when I run streaming with those checkpointers, I am running into several issues there as well. For example, see below error when I run the following checkpointer with SqliteSaver:

Code:

`config = {"configurable": {"thread_id": "3"}}
input_message = HumanMessage(content="Hello, how can you assist me?")
async for event in graph.astream_events({"messages": [input_message]}, config, version="v2"):
    print(f"Node: {event['metadata'].get('langgraph_node','')}. Type: {event['event']}. Name: {event['name']}")`
    
 
Error:

`AttributeError: 'sqlite3.Connection' object has no attribute 'is_alive'`

**Comment by psinha30** [comment]
Hey @shivachittamuru  did it work?
