### ISSUE TITLE
[LATS example] Selection should choose best child at each tree level until reaching leaf

### ISSUE THREAD

**Issue by eranhirs** [langchain-ai/langgraph#1722]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

In the [LATS example](https://github.com/langchain-ai/langgraph/blob/main/docs/docs/tutorials/lats/lats.ipynb) implementation, we have the following which selects the next node from all of the tree:

```python

class Node:
    @property
    def best_child(self):
        """Select the child with the highest UCT to search next."""
        if not self.children:
            return None
        all_nodes = self._get_all_children()
        return max(all_nodes, key=lambda child: child.upper_confidence_bound())

    def _get_all_children(self):
        all_nodes = []
        nodes = deque()
        nodes.append(self)
        while nodes:
            node = nodes.popleft()
            all_nodes.extend(node.children)
            for n in node.children:
                nodes.append(n)
        return all_nodes

...

def expand(state: TreeState, config: RunnableConfig) -> dict:
    """Starting from the "best" node in the tree, generate N candidates for the next step."""
    root = state["root"]
    best_candidate: Node = root.best_child if root.children else root
    ...
```

### Error Message and Stack Trace (if applicable)

In some scenarios, the current search algorithm implementation can get stuck in an infinite recursion (until max recursion reached) if the same node is selected and nothing happens in the expand (because it was already expanded).

### Description

Selection should choose the best child of each level until reaching a leaf. From the [LATS paper](https://arxiv.org/abs/2310.04406): "Starting from the root node, denoted as the initial state s0, a child node is selected at each tree level until a leaf node is reached."  

The current implementation creates a pool of all nodes and chooses from the entire pool, which is not the same. In particular, it can also choose nodes which are not leaves, which can cause infinite recursion problems.

### System Info

langchain==0.3.0
langchain-core==0.3.0
langchain-openai==0.2.0
langchain-text-splitters==0.3.0

**Comment by hinthornw** [comment]
Thanks for the catch and fix
