### ISSUE TITLE
DOC: <Please write a comprehensive title after the 'DOC: ' prefix>How to add prompt to every react_agent in every team?

### ISSUE THREAD

**Issue by guapia233** [langchain-ai/langgraph#1764]
### Issue with current documentation:

hierarchical_agent_teams.ipynb
link:https://github.com/langchain-ai/langgraph/blob/main/docs/docs/tutorials/multi_agent/hierarchical_agent_teams.ipynb

### Idea or request for content:

I had been working on this example code for a long time in the field of penetration testing (although it was constantly being changed by the authorities) and started to notice a problem. For example, now there is a scan team consisting of a supervisor and two agents, each equipped with a tool. A team is given a task to be completed in two steps, which requires the cooperation of two agents to complete step by step, but often the task will be stuck in the cycle of the first agent, even if the first part of the task has been completed, and many times the team will not realize the existence of the second tool during the execution (the definition is correct, a separate test can succeed). I would like to know how this is caused and how it can be improved. In the example code, only the supervisor has prompts.How would you add a prompt to each agent, perhaps to solve this problem? I would be grateful if you could answer!

**Comment by py-taha** [comment]
You can add additional prompt to your `react_agent` by using `state_modifier` . So, if you set `state_modifier` as a string then it will be converted into `SystemMessage` and will be added to the beginning of the messages list. Same would happen if you pass a `SystemMessage` on your own.

For more you can refer the documentation [here](https://langchain-ai.github.io/langgraph/reference/prebuilt/)

**Comment by guapia233** [comment]
@py-taha 
I've already use langsimth before, and have done the first two points.
Therefore, I will modify codes from the last two points you suggested:add prompts and maintain a prev key.
I really appreciate the advice, it was exactly what I needed!

**Comment by py-taha** [comment]
> @py-taha I've already use langsimth before, and have done the first two points. Therefore, I will modify codes from the last two points you suggested:add prompts and maintain a prev key. I really appreciate the advice, it was exactly what I needed!

I appreciate it. Let me know if that doesn't work, I'd be happy to help even further.

**Comment by vbarda** [comment]
@guapia233 was your issue resolved?

**Comment by guapia233** [comment]
@vbarda yes, I have solved it. I now realize this is a very simple problem, cause back then I was a rookie (though I still am now). Whatever, thank you😀
