### ISSUE TITLE
[Docs] Be consistent in START/END and "__start__"/"__end__"

### ISSUE THREAD

**Issue by hinthornw** [langchain-ai/langgraph#1781]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

It's the same thing but as a reader, it's confusing to stumble across both.
Variables (START, END) aren't permitted in `Literal[START]` typing, meaning the technique of inferring conditional edges connectivity based on the literal response is not supported using START/END.

(it would likely work, but mypy disallows it, and people enjoy mypy), ipso facto we should either exclusively use literal strings OR we should stop relying on Literal[] and prefer adding a path map (as a list, preferably).

My current bias is:
1. Use Literal["__end__", "tools", ...] when possible
2. If using Send(), etc., use a path_map=["__end__", "tools"], etc.

I could be convinced to only use (2) for the sake of consistency, though it feels a bit redundant in simple cases.
I don't see a great use case for dictionary-type path maps (unless we want to say that's the way of communicating both the "finish_reason" and "finish" as a single variable)

**Comment by vbarda** [comment]
Should be addressed in https://github.com/langchain-ai/langgraph/pull/1874
