### ISSUE TITLE
DOC: Update `thread_ts` to `checkpoint_id`.

### ISSUE THREAD

**Issue by gbaian10** [langchain-ai/langgraph#1789]
### Issue with current documentation:

The current tutorial documents, such as the [Quick Start page](https://langchain-ai.github.io/langgraph/tutorials/introduction/), still use `thread_ts` as an example.

However, as far as I know, it was renamed to `checkpoint_id` after version 0.2.0. Although the program still allows `thread_ts` as input, should the documents be updated to reflect the newer usage?

There might be multiple pages using `thread_ts`, and the ipynb outputs also need to be re-executed.

Additionally, it seems the documents don't specifically explain the purpose of `checkpoint_ns`. I'm curious about this field—when would we need to use it?

**Comment by vbarda** [comment]
This should be fixed now -- thanks for flagging!
