### ISSUE TITLE
PrivateState not working if the node is activated by a Send object

### ISSUE THREAD

**Issue by minki-j** [langchain-ai/langgraph#1909]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
from typing import List, TypedDict, Annotated
from pydantic import BaseModel
from langgraph.types import Send
from langgraph.graph import StateGraph, START, END
import operator


def router(state) -> List[Send]:
    return [
        Send(
            "node_activate_by_Send",
            {"var": var},
        )
        for var in state["list_of_vars"]
    ]

class PrivateState(BaseModel):
    private_var: Annotated[List[str], operator.add]

def node_activate_by_Send(state) -> PrivateState:
    return {"private_var": [state["var"]]}

class State(TypedDict):
    list_of_vars: List[str]

g = StateGraph(State)

g.add_conditional_edges(START, router)

g.add_node(node_activate_by_Send)
g.add_edge("node_activate_by_Send", END)

app = g.compile()

app.invoke({"list_of_vars": ["a", "b", "c"]})
```

### Error Message and Stack Trace (if applicable)

```shell
InvalidUpdateError: Must write to at least one of ['list_of_vars']
```

### Description

PrivateState is not working when the node is activated by a Send object. 

### System Info

langchain==0.3.1
langchain-anthropic==0.2.1
langchain-core==0.3.6
langchain-openai==0.2.1
langchain-text-splitters==0.3.0
langgraph==0.2.28

**Comment by gbaian10** [comment]
Change `g = StateGraph(State)` to `g = StateGraph(State, output=PrivateState)`.

**Comment by minki-j** [comment]
thank you for the reply @gbaian10 

I guess my example was not good enough. Take a look at this updated example. In this case, I can't set the output state to privateState as you suggested. 

```python
from typing import List, TypedDict, Annotated
import operator
from pydantic import BaseModel
from langgraph.types import Send
from langgraph.graph import StateGraph, START, END
from langchain_core.runnables import RunnablePassthrough

class PrivateState(BaseModel):
    private_var: Annotated[List[str], operator.add]

class State(TypedDict):
    list_of_vars: List[str]
    vars_as_strings: str

class OutputState(BaseModel):
    vars_as_strings: str

def router(state) -> List[Send]:
    return [
        Send(
            "node_activate_by_Send",
            {"var": var},
        )
        for var in state["list_of_vars"]
    ]

def node_activate_by_Send(state) -> PrivateState:
    return {"private_var": [state["var"]]}

def generate_vars_as_string(state) -> State:
    return {"vars_as_strings": ", ".join(state["list_of_vars"])}

g = StateGraph(State, output=OutputState)

g.add_conditional_edges(START, router)

g.add_node(node_activate_by_Send)
g.add_edge("node_activate_by_Send", "generate_vars_as_string")

g.add_node("generate_vars_as_string", generate_vars_as_string)
g.add_edge("generate_vars_as_string", END)

app = g.compile()

app.invoke({"list_of_vars": ["a", "b", "c"]})
```

**Comment by isahers1** [comment]
The problem is you need `generate_vars_as_string` to accept `PrivateState` as its state, whereas currently you are passing the overall state. A change like the one below would solve your error. Let me know if you had something different in mind.
```python
def generate_vars_as_string(state: PrivateState) -> State:
    return {"vars_as_strings": state.private_var}
```

**Comment by minki-j** [comment]
@isahers1 ah I missed that. Thank you so much.  It worked well with your suggestion.
