### ISSUE TITLE
can't deploy langgraph 0.2.31 to langgrah cloud

### ISSUE THREAD

**Issue by junan-trustarc** [langchain-ai/langgraph#1933]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
langchain==0.3.1
langchain-core==0.3.7
langchain_openai==0.2.1
langchain-voyageai==0.1.2
langchain_cohere==0.3.0
langchain_experimental==0.3.2
langgraph==0.2.31
langsmith==0.1.129
langchain_pinecone==0.2.0
langgraph-checkpoint-postgres==1.0.11
```

### Error Message and Stack Trace (if applicable)

```shell
01/10/2024, 01:21:36
Step #11:  > [3/7] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -r /deps/__outer_arc-ai-api/src/requirements.txt:
01/10/2024, 01:21:36
Step #11: 3.757     The user requested (constraint) langgraph<0.2.29,>=0.2.18
01/10/2024, 01:21:36
```

### Description

I got this error from langgraph cloud while deploying, where this "constraints.txt" comes from ? 
How to resolve it?

### System Info

window
python 3.12.5

**Comment by hinthornw** [comment]
Hi there! We've since released a version that supports the latest version of langgraph/checkpoints/etc.

Thank you for your patience! Please let us know if you still run into issues deploying!
