### ISSUE TITLE
"langgraph test" doesn't work with latest langgraph

### ISSUE THREAD

**Issue by junan-trustarc** [langchain-ai/langgraph#2010]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
uvicorn==0.31.0
python-dotenv==1.0.1
langchain==0.3.2
langchain-core==0.3.9
langchain_openai==0.2.1
langchain-voyageai==0.1.2
langchain_cohere==0.3.0
langchain_experimental==0.3.2
langgraph==0.2.34
langsmith==0.1.131
langchain_pinecone==0.2.0
langgraph-checkpoint-postgres==2.0.0
wikipedia==1.4.0
pinecone-client[grpc]==5.0.1
pinecone-text==0.9.0
psycopg[binary,pool]==3.2.3
psycopg-pool==3.2.3
requests==2.32.3
pytest==8.3.3
setuptools==75.1.0
```

### Error Message and Stack Trace (if applicable)

```shell
outer_arc-ai-langgraph/src/requirements.txt" did not complete successfully: exit code: 1
------
 > [3/7] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -r /deps/__outer_arc-ai-langgraph/src/requirements.txt:
2.030
2.030 The conflict is caused by:
2.030     The user requested langchain-core==0.3.9
2.030     The user requested (constraint) langchain-core<0.3.0,>=0.2.27
2.030
2.030 To fix this you could try to:
2.030 1. loosen the range of package versions you've specified
2.030 2. remove package versions to allow pip to attempt to solve the dependency conflict
2.030
2.147 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
------
Dockerfile:6
--------------------
   4 |
   5 |     ADD requirements.txt /deps/__outer_arc-ai-langgraph/src/requirements.txt
   6 | >>> RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -r /deps/__outer_arc-ai-langgraph/src/requirements.txt
   7 |
   8 |     ADD . /deps/__outer_arc-ai-langgraph/src
--------------------
ERROR: failed to solve: process "/bin/sh -c PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -r /deps/__outer_arc-ai-langgraph/src/requirements.txt" did not complete successfully: exit code: 1
```

### Description

"langgraph up" is working however "langgraph test" complains with dependencies, could you update constraints.txt to make it working? thanks.

### System Info

windows
python 3.12.5

**Comment by vbarda** [comment]
@junan-trustarc the new recommended way to start a local server is to run `langgraph dev`https://langchain-ai.github.io/langgraph/tutorials/langgraph-platform/local-server/

will close this issue, but let me know if you run into any further problems
