### ISSUE TITLE
"--watch" flag doesn't work on langgraph up

### ISSUE THREAD

**Issue by junan-trustarc** [langchain-ai/langgraph#2011]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
langgraph up --watch
```

### Error Message and Stack Trace (if applicable)

```shell
langgraph up --watch
Starting LangGraph API server...
For local dev, requires env var LANGSMITH_API_KEY with access to LangGraph Cloud closed beta.
For production use, requires a license key in env var LANGGRAPH_CLOUD_LICENSE_KEY.
\ Building...unknown flag: --watch
```

### Description

langgraph-cli documentation has --watch flag however when I tried to run, it doesn't work.
Could you help to resolve?
I am using latest cli as well.

https://langchain-ai.github.io/langgraph/cloud/reference/cli/#up

### System Info

windows
python 3.12.5

**Comment by hinthornw** [comment]
Do you have an old langgraph-cli version?
```
pip show langgraph-cli
```

**Comment by junan-trustarc** [comment]
> Do you have an old langgraph-cli version?
> 
> ```
> pip show langgraph-cli
> ```

Thanks for reply, latest version:  0.1.52

**Comment by hinthornw** [comment]
Hello! A bit late now, but we'd recommend using `langgraph dev` for local development now that it's available: https://langchain-ai.github.io/langgraph/how-tos/local-studio/

**Comment by vbarda** [comment]
Going to close, but please let us know if you are still running into this issue with `langgraph dev`
