### ISSUE TITLE
DOC: Agent Executor Docs deleted after 0.2.19?

### ISSUE THREAD

**Issue by Data-drone** [langchain-ai/langgraph#2097]
### Issue with current documentation:

Just wondering why the agent executor examples were deleted post 0.2.19?

ie https://github.com/langchain-ai/langgraph/blob/0.2.19/examples/chat_agent_executor_with_function_calling/dynamically-returning-directly.ipynb 

These go with the online introductions: https://www.youtube.com/watch?v=rabXcLaAlqE&list=PLfaIDFEXuae16n2TWUkKq5PgJ0w6Pkwtg&index=5

Is there a switch in API? 

If there is a newer class / process maybe it's worth updating the descriptions in the youtube

**Comment by vbarda** [comment]
@Data-drone thanks for raising! we'll add an updated page for that in the documentation. right now it's implemented in `create_react_agent` by setting `return_direct = True` in your tools -- see more here https://github.com/langchain-ai/langgraph/blob/main/libs/langgraph/langgraph/prebuilt/chat_agent_executor.py#L590, so you can use it directly or as a reference in your implementations
