### ISSUE TITLE
ToolNode doesn't detect `InjectedState` annotations for tools with Pydantic `args_schema`

### ISSUE THREAD

**Issue by vbarda** [langchain-ai/langgraph#2220]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
.
```

### Error Message and Stack Trace (if applicable)

```shell
.
```

### Description

.

### System Info

.

**Comment by bengladwell** [comment]
After quite a bit of experimentation (thanks @vbarda!), it is unclear why my field with type InjectedState is not appearing in my tool's `arg_schema` object's `__annotations__` attr.

**Comment by TomTom101** [comment]
Still having trouble with this @vbarda . This toy example from the docs still fails with version 0.2.53

```python
from typing import List
from typing_extensions import Annotated, TypedDict

from langchain_core.messages import BaseMessage, AIMessage
from langchain_core.tools import tool

from langgraph.prebuilt import InjectedState, ToolNode

from pydantic import BaseModel, Field


class AgentState(TypedDict):
    messages: List[BaseMessage]
    state: Annotated[dict, InjectedState]


class ArgsSchema(BaseModel):
    x: int = Field(description="An integer.")
    # state: Annotated[dict, InjectedState] # I tried to no avail


@tool(args_schema=ArgsSchema)
def state_tool(x: int, state: Annotated[dict, InjectedState]) -> str:
    """Do something with state."""
    return state["foo"].upper()


node = ToolNode([state_tool])

tool_call1 = {"name": "state_tool", "args": {"x": 1}, "id": "1", "type": "tool_call"}
state = {
    "messages": [AIMessage("", tool_calls=[tool_call1])],
    "foo": "bar",
}
node.invoke(state)
```

`{'messages': [ToolMessage(content='Error: TypeError("state_tool() missing 1 required positional argument: \'state\'")\n Please fix your mistakes.', name='state_tool', tool_call_id='1', status='error')]}`

Probably I am using it wrong. Any hint possibly?

Thanks!

**Comment by umzaffar** [comment]
@TomTom101  did you find a fix I am having the same problem?

**Comment by sharyar** [comment]
Running into the same issue as well.

**Comment by vbarda** [comment]
The code snippet above is incorrect - this is the correct usage and it works fine for me:

```python
from typing import List
from typing_extensions import Annotated, TypedDict

from langchain_core.messages import BaseMessage, AIMessage
from langchain_core.tools import tool

from langgraph.prebuilt import InjectedState, ToolNode

from pydantic import BaseModel, Field


class AgentState(TypedDict):
    messages: List[BaseMessage]
    foo: str


class ArgsSchema(BaseModel):
    x: int = Field(description="An integer.")
    state: Annotated[dict, InjectedState]


@tool(args_schema=ArgsSchema)
def state_tool(x: int, state: Annotated[dict, InjectedState]) -> str:
    """Do something with state."""
    return state["foo"].upper()


node = ToolNode([state_tool])

tool_call1 = {"name": "state_tool", "args": {"x": 1}, "id": "1", "type": "tool_call"}
state = {
    "messages": [AIMessage("", tool_calls=[tool_call1])],
    "foo": "bar",
}
node.invoke(state)
```

**Comment by pedrojrv** [comment]
I think it would be worthwhile to add this to the documentation. I checked everywhere and could not find the solution until this.

**Comment by dhanlon-intellica** [comment]
You my good sir are a hero... I saw where the AI tried to pass in state to the tool call... so i removed it from the ArgsSchema so it wouldn't attempt to do that (b/c we have injected state) and then my issues began

Im told this helps with that issue
```
   state: Annotated[Any, InjectedState()] | None = Field(
        default=None,
        description="(internal) injected  state",
        json_schema_extra={"hidden": True},
    )
```
