### ISSUE TITLE
DOC: Incorrect link to conceptual guide

### ISSUE THREAD

**Issue by cab938** [langchain-ai/langgraph#2295]
### Issue with current documentation:

This page: https://langchain-ai.github.io/langgraph/tutorials/introduction/#part-1-build-a-basic-chatbot

Has an incorrect link to the conceptual guide: https://langchain-ai.github.io/langgraph/reference/graphs/?h=add+messages#add_messages

The link ends up linking to an API doc entry for the Graph class.

### Idea or request for content:

It should go here instead: https://langchain-ai.github.io/langgraph/concepts/

**Comment by vbarda** [comment]
Thanks for reporting -- will fix!

**Comment by vbarda** [comment]
Fixed in #2305
