### ISSUE TITLE
LangGraph Studio (mac) -> AttributeError: module 'mvgbxnshzyfjxntsvqcqbkah' has no attribute 'graph'

### ISSUE THREAD

**Issue by acsankar** [langchain-ai/langgraph#2316]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
def create_workflow() -> StateGraph:
    """Create the workflow graph with conditional routing"""
    
    # Initialize workflow with State type
    workflow = StateGraph(State)
    
    # Define routing function
    def router(state: State) -> str:
        """Route based on state's next value"""
        return state.get('next', 'triage')
    
    # Add nodes
    workflow.add_node("triage", triage_agent)
    workflow.add_node("data_agent", data_agent)
    workflow.add_node("access_agent", access_agent)
    workflow.add_node("human_in_loop", human_in_loop)
    
    # Set entry point
    workflow.set_entry_point("triage")
    
    # Add conditional edges from triage
    workflow.add_conditional_edges(
        "triage",
        router,
        {
            "data_agent": "data_agent",
            "access_agent": "access_agent",
            "human_in_loop": "human_in_loop"
        }
    )
    
    # Add conditional edges from human_in_loop
    workflow.add_conditional_edges(
        "human_in_loop",
        router,
        {
            "data_agent": "data_agent",
            "access_agent": "access_agent",
            "end": END
        }
    )
    
    # Add edges to END from agents
    workflow.add_conditional_edges(
        "data_agent",
        lambda x: "end",
        {"end": END}
    )
    
    workflow.add_conditional_edges(
        "access_agent",
        lambda x: "end",
        {"end": END}
    )
    
    return workflow.compile()
```

### Error Message and Stack Trace (if applicable)

```shell
Failed to start project lang4
error | Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/api/langgraph_api/lifespan.py", line 30, in lifespan
  File "/api/langgraph_api/shared/graph.py", line 230, in collect_graphs_from_env
  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 588, in run_in_executor
    return await asyncio.get_running_loop().run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 579, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/api/langgraph_api/shared/graph.py", line 276, in _graph_from_spec
AttributeError: module 'mvgbxnshzyfjxntsvqcqbkah' has no attribute 'graph'
```

### Description

I am trying to load the folder to Langstudio (mac installation), i am getting the below issue:

  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 579, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/api/langgraph_api/shared/graph.py", line 276, in _graph_from_spec
AttributeError: module 'mvgbxnshzyfjxntsvqcqbkah' has no attribute 'graph'

### System Info

]

**Comment by vbarda** [comment]
@acsankar could you share your `langgraph.json`? it sounds like you don't have a variable called `graph` with the compiled graph in the `.py` file you're trying to load the graph from

**Comment by acsankar** [comment]
> @acsankar could you share your `langgraph.json`? it sounds like you don't have a variable called `graph` with the compiled graph in the `.py` file you're trying to load the graph from

{
  "dockerfile_lines": [],
  "graphs": {
    "agent": "./main.py:graph"
  },
  "env": [
    "HK"
  ],
  "python_version": "3.11",
  "dependencies": [
    "."
  ]
}

**Comment by vbarda** [comment]
and just to confirm -- you have a variable like `graph = create_workflow()` in `main.py`, right?

**Comment by acsankar** [comment]
Below is the code

def create_workflow() -> Graph:
    """Create the workflow graph"""
    workflow = Graph()
    
    # Add nodes
    workflow.add_node("triage", triage_agent)
    workflow.add_node("data_agent", data_agent)
    workflow.add_node("access_agent", access_agent)
    workflow.add_node("human_in_loop", human_in_loop)
    
    # Add edges
    workflow.set_entry_point("triage")
    workflow.add_edge('triage', 'data_agent')
    workflow.add_edge('triage', 'access_agent')
    workflow.add_edge('triage', 'human_in_loop')
    workflow.add_edge('human_in_loop', 'data_agent')
    workflow.add_edge('human_in_loop', 'access_agent')
    
    return workflow.compile()

**Comment by vbarda** [comment]
> Below is the code
> 
> def create_workflow() -> Graph: """Create the workflow graph""" workflow = Graph()
> 
> ```
> # Add nodes
> workflow.add_node("triage", triage_agent)
> workflow.add_node("data_agent", data_agent)
> workflow.add_node("access_agent", access_agent)
> workflow.add_node("human_in_loop", human_in_loop)
> 
> # Add edges
> workflow.set_entry_point("triage")
> workflow.add_edge('triage', 'data_agent')
> workflow.add_edge('triage', 'access_agent')
> workflow.add_edge('triage', 'human_in_loop')
> workflow.add_edge('human_in_loop', 'data_agent')
> workflow.add_edge('human_in_loop', 'access_agent')
> 
> return workflow.compile()
> ```

right, but do you save the output of `create_workflow` into a variable? if yes, then it should be named `graph` for your config to work. if no - you can also provide function names instead of variables like this: 

`"agent": "./main.py:create_workflow"`

hope this helps

**Comment by magaton** [comment]
I have a similar issue:

I have my langgraphs as classes
```
class Search(BaseLanggraph) :

    def __init__(self, metadata_store: MetadataStore, collection : Collection):
        super().__init__(metadata_store, collection, LangGraphType.SEARCH)
        workflow = StateGraph(BasicState)
        workflow.add_node("retrieve", self.retrieve)
        workflow.set_entry_point("retrieve")
        workflow.add_node("rerank", self.rerank)
        workflow.add_node("post_retrieve", self.post_retrieve)
        workflow.add_edge("retrieve", "rerank")
        workflow.add_edge("rerank", "post_retrieve")
        workflow.add_edge('post_retrieve', END)
        self.graph : CompiledStateGraph =workflow.compile()
        
 ```       
 
 As you can see: in constructor I compile graph
 
 Then on the client side I get the graph instance as a member variable:
 get_langgraph(collection, metadata_store).graph
 
 Now what should I put in my langgraph.json?
 
 ```
 {
  "dockerfile_lines": [],
  "graphs": {
    "search": "./langgraph/search.py:__init__",
    "suggest": "./langgraph/suggest.py:__init__",
    "experimental": "./langgraph/experimental.py:__init__"
  },
  "env": ".env",
  "python_version": "3.11",
  "dependencies": [
    "."
  ]
}
 ```
 I tried with __init__, a member method het_graph that returns self.graph, graph itself, etc. But I always get the error like:
 `AttributeError: module 'ijzxmhgjljxfogukyuyxliar' has no attribute '...'`

**Comment by vbarda** [comment]
@magaton you would need to change Langgraph JSON to

```
...
"graphs": {
   "search": "./langgraph/search.py: langgraph"
   ...
},
...
```

e.g. using this `langgraph = get_langgraph(collection, metadata_store).graph`
