### ISSUE TITLE
Customer Support Bot

### ISSUE THREAD

**Issue by hinthornw** [langchain-ai/langgraph#233]
(less of an academic example, more a practical implementation)

Functionality to highlight here:

1. Human-in-the-loop
2. Persistence (can stop and then resume any time)
3. Simple knowledge connection (RAG)

**Comment by tevslin** [comment]
would be helpful to know how to break to, for example, have a human complete a form in a stateful UI like Streamlit and then resume the execution of the graph following the agent or function which requetsd the input

**Comment by hinthornw** [comment]
Implemented! https://langchain-ai.github.io/langgraph/tutorials/customer-support/customer-support/?h=customer

**Comment by tevslin** [comment]
Great. Thank you
