### ISSUE TITLE
Subgraph with private state doesn't have a proper state at the last node

### ISSUE THREAD

**Issue by minki-j** [langchain-ai/langgraph#2392]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
class CodeFeedbackAgentPrivateState(BaseModel):
    interview_question: str = Field(default="")
    interview_solution: str = Field(default="")
    code_editor_state: str = Field(default="")

    debugging_result: str = Field(default="")
    assessment_result: str = Field(default="")

class DebuggingAgentPrivateState(BaseModel):
    interview_question: str = Field(default="")
    interview_solution: str = Field(default="")
    code_editor_state: str = Field(default="")

    debugging_record: list[str] = Field(default=[])


def initiate_private_state(state):
    print("initiate_private_state: \n", state.__annotations__)
    print("type: ", type(state))
    return {
        "interview_question": state.interview_question,
        "interview_solution": state.interview_solution,
        "code_editor_state": state.code_editor_state,
    }


def placeholder_node(state: DebuggingAgentPrivateState):
    return {
        "debugging_record": ["debugging_record testing"],
    }


def placeholder_node2(state: DebuggingAgentPrivateState):
    return {
        "debugging_result": "debugging_result testing",
    }

def last_node(state: CodeFeedbackAgentPrivateState):

    print("last_node CodeFeedbackAgentPrivateState debugging_result: \n", state.debugging_result)
    return {
        "debugging_result": state.debugging_result, #? BUG: this return is applied to OverallState instead of CodeFeedbackAgentPrivateState
    }

g = StateGraph(CodeFeedbackAgentPrivateState)
g.add_edge(START, n(initiate_private_state))

g.add_node(initiate_private_state)
g.add_edge(n(initiate_private_state), n(placeholder_node))

g.add_node(placeholder_node)
g.add_edge(n(placeholder_node), n(placeholder_node2))

g.add_node(placeholder_node2)
g.add_edge(n(placeholder_node2), n(last_node))

g.add_node(last_node)
g.add_edge(n(last_node), END)

debugging_agent_graph = g.compile()
```

### Description

I have double nested subgraphs. 

Level 0: main_graph
- uses OverAllState as StateGraph schema
- no private states
- includes a node of code_feedback_agent_graph

Level 1: code_feedback_agent_graph
- uses OverAllState as StateGraph schema
- uses CodeFeedbackAgentPrivateState as a private state
- includes a node debugging_agent_graph
- the private state is used when the debugging_agent_graph is triggered

level 2: debugging_agent_graph
- uses CodeFeedbackAgentPrivateState as StateGraph schema 
- uses DebuggingAgentPrivateState as private state

At the last node of level 2 graph, I'm returning a dictionary that includes state variable of level 1 graph's private state because that is the state that is used when level 2 graph is triggered. 

However, I'm getting an error saying the return should include OverAllState variable. Since level 2 graph is using CodeFeedbackAgentPrivateState as its StateGraph schema, the last node's return dict should update that instead of OverAllState. Shouldn't it be?

### System Info

Version: 0.2.28

**Comment by vbarda** [comment]
@minki-j the update from `last_node` is in fact applied to the state of the Level 1 graph, but since Level 1 graph is invoked inside the Level 0 graph, Level 1 graph as a whole **still** needs to respect the state of the parent (Level 0) graph. if you want to keep the state schemas independent, i.e. have no overlapping keys, you can just add input/output transformations before/after you invoke level 1 graph

see more here: https://langchain-ai.github.io/langgraph/concepts/low_level/#as-a-function

hope this helps!

**Comment by minki-j** [comment]
@vbarda Thank you so much for your answer!! It makes sense. I'll follow your recommendation. 

Again, I really really appreciate you guys work on LangGraph! Thank you so much!

**Comment by vbarda** [comment]
Glad it helped! Will close this issue for now, but let me know if you run into any problems w/ subgraphs/state management
