### ISSUE TITLE
Why the agent can't retrieve for more than 2 chat messages?

### ISSUE THREAD

**Issue by FireAngelx** [langchain-ai/langgraph#2395]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
@tool
def get_user_age(name: str) -> str:
    """Use this tool to find the user's age."""
    # This is a placeholder for the actual implementation
    if "bob" in name.lower():
        return "20 years old"
    return "41 years old"


tools = [get_user_age]
memory = MemorySaver()
app = create_react_agent(
    model=model,
    tools=tools,
    checkpointer=memory
)
thread_id = uuid.uuid4()
config = {"configurable": {"thread_id": thread_id}}


def agent_call(content):
    for event in app.stream({"messages": [content]}, config, stream_mode="values"):
        event["messages"][-1].pretty_print()


agent_call(content="hi! I'm bob.")
agent_call(content="My mother is susiy.")
agent_call(content="do you remember my name? do you remember my mother name?")
```

### Error Message and Stack Trace (if applicable)

```shell
I find that the MemorySave can only remember 1 message. If I ask 'hi! I'm bob.' then 'do you remember my name? ', the agent can response correctly. However, between these two query add a useless query like '1+1=?', the agent would forget my name. Is there any params solving this problem?
```

### Description

The third output is "It seems there was a little confusion. I used the function to find the age of your mother, Susiy, and it appears that she is 41 years old. However, I still haven't learned your name. Could you please tell me your name?"

### System Info

The result is wrong.

**Comment by vbarda** [comment]
@FireAngelx it's likely that it's an issue with the LLM you're using. I tested using `gpt-4o-mini` and it works as expected for me
<img width="778" alt="image" src="https://github.com/user-attachments/assets/bcfc4c65-c4d5-4efb-8bb9-bbbe5cc201d0">

**Comment by FireAngelx** [comment]
@vbarda Thanks, I used qwen-max and found it work not well in react chain, but it responsed correctly in normal LLMChain API. I don't solve the problem, but it seem that GPT api works as expected.

**Comment by FireAngelx** [comment]
@vbarda later I test other llm like deepseek-chat, chatglm. etc. They can get the memory well. But if I would like to limit the length of history, which param I can set?

**Comment by vbarda** [comment]
We don't have a param for this yet in `create_react_agent` (but actively working on improvements for memory/chat history management inside react agent). Currently you would need to implement the react agent yourself and then add logic for filtering/removing messages from the history if it grows too long, see these two guides:

- custom react agent: https://langchain-ai.github.io/langgraph/how-tos/react-agent-from-scratch/
- managing message history: https://langchain-ai.github.io/langgraph/how-tos/memory/manage-conversation-history/

in the meantime, will close this issue
