### ISSUE TITLE
Latency for get_state using MemorySaver is very high

### ISSUE THREAD

**Issue by mukundt** [langchain-ai/langgraph#2403]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
t0 = time.time()
snapshot = graph_manager.graph.get_state(config)
print(f"get_state latency: {(time.time() - t0) * 1000:.2f}ms")
messages = snapshot.values.get("messages")
```

### Description

Hey! I am building an extremely low-latency application. I noticed that when using MemorySaver, the latency of this simple call is between 20-40ms -- this might sound small but is pretty significant for my use case. Is there any way to get this down?

### System Info

langgraph 0.2.46
langgraph-checkpoint 2.0.3
python 3.10

**Comment by vbarda** [comment]
@mukundt any reason why you're not using `langgraph-checkpoint-postgres` / `langgraph-checkpoint-sqlite` / `langgraph-checkpoint-duckdb`? in-memory checkpointer is not meant for any production applications

**Comment by vbarda** [comment]
will investigate memory saver latency in the meantime -- thanks for reporting

**Comment by mukundt** [comment]
@vbarda are any of those lower latency? If so, more than happy to give them a shot! I just assumed memory saver would be the fastest.
My application only has one active graph in use at a time, so don't need the benefits that a DB offers :)

**Comment by mukundt** [comment]
@vbarda - it should be pretty simple, just a bunch of (pretty small) lists. I've noticed sometimes `get_state` is 3 ms at the start, but then it is consistently 35-40ms after that. This is on an M3 MacBook so should be pretty fast.

```
class State(TypedDict):
    messages: Annotated[list, add_and_persist_messages]
    agents: Annotated[list, reducer]
    user_info: str
    dialog_state: Annotated[
        list[str],
        update_dialog_stack,
    ]
    ```

**Comment by vbarda** [comment]
@mukundt do you see the same issue if you call `checkpointer.get_tuple(config)`? i think the latency you're seeing is coming from `.get_state`, but wanted to confirm

**Comment by vbarda** [comment]
@mukundt could you please update to `langchain-core==0.3.19` and see if you're still running into this issue?

**Comment by mukundt** [comment]
@vbarda with `langchain-core==0.3.19` + `get_state` I still have the same issue:

```
GET_STATE SYNC LATENCY: 45.90ms
GET_STATE SYNC LATENCY: 20.98ms
```

However, `checkpointer.get_tuple(config)` is significantly faster, never more than 1ms. Should we use this instead? And does it have any different behavior to get the `messages` array?

```
GET_STATE SYNC LATENCY: 36.74ms
GET_TUPLE SYNC LATENCY: 0.16ms
```
