### ISSUE TITLE
DOC: `MessageGraph` not appears in `/langgraph/reference/graphs`

### ISSUE THREAD

**Issue by WendaoLee** [langchain-ai/langgraph#2444]
### Issue with current documentation:

I'm learning langgraph's core concepts through [Conceptual Documents](https://langchain-ai.github.io/langgraph/concepts/low_level/#messagegraph) and [Library Reference](https://langchain-ai.github.io/langgraph/reference/graphs/).

I noticed in the [Glossary Chapter](https://langchain-ai.github.io/langgraph/concepts/low_level/#messagegraph),it metioned `MessageGraph`,but it not appears in [Library Reference](https://langchain-ai.github.io/langgraph/reference/graphs/),though the lib indeedly export this class:

```python
from langgraph.graph.message import MessageGraph, MessagesState, add_messages
from langgraph.graph.state import GraphCommand, StateGraph

__all__ = [
    "END",
    "START",
    "Graph",
    "StateGraph",
    "GraphCommand",
    "MessageGraph",
    "add_messages",
    "MessagesState",
]
```

Is this omission intentional, or is it an oversight?

### Idea or request for content:

Add `MessageGraph Class` documents in  [Library Reference](https://langchain-ai.github.io/langgraph/reference/graphs/).

**Comment by vbarda** [comment]
@WendaoLee this is on purpose -- we're not encouraging people to use `MessageGraph`. You can still use `MessagesState` if you need to have a shorthand for using `messages` key with `add_messages` reducer
