### ISSUE TITLE
Storm notebook issue: BadRequestError: Error code: 400 - {'error': {'message': "'Subject Matter Expert' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.1.name'", 'type': 'invalid_request_error'

### ISSUE THREAD

**Issue by ruanwz** [langchain-ai/langgraph#248]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
final_step = None

initial_state = {
    "editor": perspectives.editors[0],
    "messages": [
        AIMessage(
            content=f"So you said you were writing an article on {example_topic}?",
            name="Subject Matter Expert",
        )
    ],
}
async for step in interview_graph.astream(initial_state):
    name = next(iter(step))
    print(name)
    print("-- ", str(step[name]["messages"])[:300])
    if END in step:
        final_step = step
```

### Error Message and Stack Trace (if applicable)

{
	"name": "BadRequestError",
	"message": "Error code: 400 - {'error': {'message': \"'Subject Matter Expert' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.1.name'\", 'type': 'invalid_request_error', 'param': None, 'code': None}}",
	"stack": "---------------------------------------------------------------------------
BadRequestError                           Traceback (most recent call last)
Cell In[28], line 12
      1 final_step = None
      3 initial_state = {
      4     \"editor\": perspectives.editors[0],
      5     \"messages\": [
   (...)
     10     ],
     11 }
---> 12 async for step in interview_graph.astream(initial_state):
     13     name = next(iter(step))
     14     print(name)

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langchain_core/runnables/base.py:4645, in RunnableBindingBase.astream(self, input, config, **kwargs)
   4639 async def astream(
   4640     self,
   4641     input: Input,
   4642     config: Optional[RunnableConfig] = None,
   4643     **kwargs: Optional[Any],
   4644 ) -> AsyncIterator[Output]:
-> 4645     async for item in self.bound.astream(
   4646         input,
   4647         self._merge_configs(config),
   4648         **{**self.kwargs, **kwargs},
   4649     ):
   4650         yield item

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langgraph/pregel/__init__.py:940, in Pregel.astream(self, input, config, output_keys, input_keys, interrupt_before_nodes, interrupt_after_nodes, debug, **kwargs)
    937 async def input_stream() -> AsyncIterator[Union[dict[str, Any], Any]]:
    938     yield input
--> 940 async for chunk in self.atransform(
    941     input_stream(),
    942     config,
    943     output_keys=output_keys,
    944     input_keys=input_keys,
    945     interrupt_before_nodes=interrupt_before_nodes,
    946     interrupt_after_nodes=interrupt_after_nodes,
    947     debug=debug,
    948     **kwargs,
    949 ):
    950     yield chunk

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langgraph/pregel/__init__.py:964, in Pregel.atransform(self, input, config, output_keys, input_keys, interrupt_before_nodes, interrupt_after_nodes, debug, **kwargs)
    952 async def atransform(
    953     self,
    954     input: AsyncIterator[Union[dict[str, Any], Any]],
   (...)
    962     **kwargs: Any,
    963 ) -> AsyncIterator[Union[dict[str, Any], Any]]:
--> 964     async for chunk in self._atransform_stream_with_config(
    965         input,
    966         self._atransform,
    967         config,
    968         output_keys=output_keys,
    969         input_keys=input_keys,
    970         interrupt_before_nodes=interrupt_before_nodes,
    971         interrupt_after_nodes=interrupt_after_nodes,
    972         debug=debug,
    973         **kwargs,
    974     ):
    975         yield chunk

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langchain_core/runnables/base.py:1979, in Runnable._atransform_stream_with_config(self, input, transformer, config, run_type, **kwargs)
   1977 while True:
   1978     if accepts_context(asyncio.create_task):
-> 1979         chunk: Output = await asyncio.create_task(  # type: ignore[call-arg]
   1980             py_anext(iterator),  # type: ignore[arg-type]
   1981             context=context,
   1982         )
   1983     else:
   1984         chunk = cast(Output, await py_anext(iterator))

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langgraph/pregel/__init__.py:763, in Pregel._atransform(self, input, run_manager, config, **kwargs)
    756 done, inflight = await asyncio.wait(
    757     futures,
    758     return_when=asyncio.FIRST_EXCEPTION,
    759     timeout=self.step_timeout,
    760 )
    762 # panic on failure or timeout
--> 763 _panic_or_proceed(done, inflight, step)
    765 # apply writes to channels
    766 _apply_writes(
    767     checkpoint, channels, pending_writes, config, step + 1
    768 )

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langgraph/pregel/__init__.py:990, in _panic_or_proceed(done, inflight, step)
    988             inflight.pop().cancel()
    989         # raise the exception
--> 990         raise exc
    991         # TODO this is where retry of an entire step would happen
    993 if inflight:
    994     # if we got here means we timed out

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langchain_core/runnables/base.py:4470, in RunnableBindingBase.ainvoke(self, input, config, **kwargs)
   4464 async def ainvoke(
   4465     self,
   4466     input: Input,
   4467     config: Optional[RunnableConfig] = None,
   4468     **kwargs: Optional[Any],
   4469 ) -> Output:
-> 4470     return await self.bound.ainvoke(
   4471         input,
   4472         self._merge_configs(config),
   4473         **{**self.kwargs, **kwargs},
   4474     )

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langchain_core/runnables/base.py:2483, in RunnableSequence.ainvoke(self, input, config, **kwargs)
   2481 try:
   2482     for i, step in enumerate(self.steps):
-> 2483         input = await step.ainvoke(
   2484             input,
   2485             # mark each step as a child run
   2486             patch_config(
   2487                 config, callbacks=run_manager.get_child(f\"seq:step:{i+1}\")
   2488             ),
   2489         )
   2490 # finish the root run
   2491 except BaseException as e:

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langchain_core/runnables/base.py:3928, in RunnableLambda.ainvoke(self, input, config, **kwargs)
   3926 \"\"\"Invoke this runnable asynchronously.\"\"\"
   3927 the_func = self.afunc if hasattr(self, \"afunc\") else self.func
-> 3928 return await self._acall_with_config(
   3929     self._ainvoke,
   3930     input,
   3931     self._config(config, the_func),
   3932     **kwargs,
   3933 )

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langchain_core/runnables/base.py:1675, in Runnable._acall_with_config(self, func, input, config, run_type, **kwargs)
   1671 coro = acall_func_with_variable_args(
   1672     func, input, config, run_manager, **kwargs
   1673 )
   1674 if accepts_context(asyncio.create_task):
-> 1675     output: Output = await asyncio.create_task(coro, context=context)  # type: ignore
   1676 else:
   1677     output = await coro

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langchain_core/runnables/base.py:3875, in RunnableLambda._ainvoke(self, input, run_manager, config, **kwargs)
   3873                 output = chunk
   3874 else:
-> 3875     output = await acall_func_with_variable_args(
   3876         cast(Callable, afunc), input, config, run_manager, **kwargs
   3877     )
   3878 # If the output is a runnable, invoke it
   3879 if isinstance(output, Runnable):

Cell In[15], line 50, in generate_question(state)
     43 editor = state[\"editor\"]
     44 gn_chain = (
     45     RunnableLambda(swap_roles).bind(name=editor.name)
     46     | gen_qn_prompt.partial(persona=editor.persona)
     47     | fast_llm
     48     | RunnableLambda(tag_with_name).bind(name=editor.name)
     49 )
---> 50 result = await gn_chain.ainvoke(state)
     51 return {\"messages\": [result]}

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langchain_core/runnables/base.py:2483, in RunnableSequence.ainvoke(self, input, config, **kwargs)
   2481 try:
   2482     for i, step in enumerate(self.steps):
-> 2483         input = await step.ainvoke(
   2484             input,
   2485             # mark each step as a child run
   2486             patch_config(
   2487                 config, callbacks=run_manager.get_child(f\"seq:step:{i+1}\")
   2488             ),
   2489         )
   2490 # finish the root run
   2491 except BaseException as e:

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:174, in BaseChatModel.ainvoke(self, input, config, stop, **kwargs)
    165 async def ainvoke(
    166     self,
    167     input: LanguageModelInput,
   (...)
    171     **kwargs: Any,
    172 ) -> BaseMessage:
    173     config = ensure_config(config)
--> 174     llm_result = await self.agenerate_prompt(
    175         [self._convert_input(input)],
    176         stop=stop,
    177         callbacks=config.get(\"callbacks\"),
    178         tags=config.get(\"tags\"),
    179         metadata=config.get(\"metadata\"),
    180         run_name=config.get(\"run_name\"),
    181         **kwargs,
    182     )
    183     return cast(ChatGeneration, llm_result.generations[0][0]).message

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:560, in BaseChatModel.agenerate_prompt(self, prompts, stop, callbacks, **kwargs)
    552 async def agenerate_prompt(
    553     self,
    554     prompts: List[PromptValue],
   (...)
    557     **kwargs: Any,
    558 ) -> LLMResult:
    559     prompt_messages = [p.to_messages() for p in prompts]
--> 560     return await self.agenerate(
    561         prompt_messages, stop=stop, callbacks=callbacks, **kwargs
    562     )

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:520, in BaseChatModel.agenerate(self, messages, stop, callbacks, tags, metadata, run_name, run_id, **kwargs)
    507     if run_managers:
    508         await asyncio.gather(
    509             *[
    510                 run_manager.on_llm_end(
   (...)
    518             ]
    519         )
--> 520     raise exceptions[0]
    521 flattened_outputs = [
    522     LLMResult(generations=[res.generations], llm_output=res.llm_output)  # type: ignore[list-item, union-attr]
    523     for res in results
    524 ]
    525 llm_output = self._combine_llm_outputs([res.llm_output for res in results])  # type: ignore[union-attr]

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:695, in BaseChatModel._agenerate_with_cache(self, messages, stop, run_manager, **kwargs)
    693 else:
    694     if inspect.signature(self._agenerate).parameters.get(\"run_manager\"):
--> 695         result = await self._agenerate(
    696             messages, stop=stop, run_manager=run_manager, **kwargs
    697         )
    698     else:
    699         result = await self._agenerate(messages, stop=stop, **kwargs)

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/langchain_openai/chat_models/base.py:581, in ChatOpenAI._agenerate(self, messages, stop, run_manager, stream, **kwargs)
    575 message_dicts, params = self._create_message_dicts(messages, stop)
    576 params = {
    577     **params,
    578     **({\"stream\": stream} if stream is not None else {}),
    579     **kwargs,
    580 }
--> 581 response = await self.async_client.create(messages=message_dicts, **params)
    582 return self._create_chat_result(response)

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/openai/resources/chat/completions.py:1330, in AsyncCompletions.create(self, messages, model, frequency_penalty, function_call, functions, logit_bias, logprobs, max_tokens, n, presence_penalty, response_format, seed, stop, stream, temperature, tool_choice, tools, top_logprobs, top_p, user, extra_headers, extra_query, extra_body, timeout)
   1278 @required_args([\"messages\", \"model\"], [\"messages\", \"model\", \"stream\"])
   1279 async def create(
   1280     self,
   (...)
   1328     timeout: float | httpx.Timeout | None | NotGiven = NOT_GIVEN,
   1329 ) -> ChatCompletion | AsyncStream[ChatCompletionChunk]:
-> 1330     return await self._post(
   1331         \"/chat/completions\",
   1332         body=maybe_transform(
   1333             {
   1334                 \"messages\": messages,
   1335                 \"model\": model,
   1336                 \"frequency_penalty\": frequency_penalty,
   1337                 \"function_call\": function_call,
   1338                 \"functions\": functions,
   1339                 \"logit_bias\": logit_bias,
   1340                 \"logprobs\": logprobs,
   1341                 \"max_tokens\": max_tokens,
   1342                 \"n\": n,
   1343                 \"presence_penalty\": presence_penalty,
   1344                 \"response_format\": response_format,
   1345                 \"seed\": seed,
   1346                 \"stop\": stop,
   1347                 \"stream\": stream,
   1348                 \"temperature\": temperature,
   1349                 \"tool_choice\": tool_choice,
   1350                 \"tools\": tools,
   1351                 \"top_logprobs\": top_logprobs,
   1352                 \"top_p\": top_p,
   1353                 \"user\": user,
   1354             },
   1355             completion_create_params.CompletionCreateParams,
   1356         ),
   1357         options=make_request_options(
   1358             extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
   1359         ),
   1360         cast_to=ChatCompletion,
   1361         stream=stream or False,
   1362         stream_cls=AsyncStream[ChatCompletionChunk],
   1363     )

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/openai/_base_client.py:1725, in AsyncAPIClient.post(self, path, cast_to, body, files, options, stream, stream_cls)
   1711 async def post(
   1712     self,
   1713     path: str,
   (...)
   1720     stream_cls: type[_AsyncStreamT] | None = None,
   1721 ) -> ResponseT | _AsyncStreamT:
   1722     opts = FinalRequestOptions.construct(
   1723         method=\"post\", url=path, json_data=body, files=await async_to_httpx_files(files), **options
   1724     )
-> 1725     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/openai/_base_client.py:1428, in AsyncAPIClient.request(self, cast_to, options, stream, stream_cls, remaining_retries)
   1419 async def request(
   1420     self,
   1421     cast_to: Type[ResponseT],
   (...)
   1426     remaining_retries: Optional[int] = None,
   1427 ) -> ResponseT | _AsyncStreamT:
-> 1428     return await self._request(
   1429         cast_to=cast_to,
   1430         options=options,
   1431         stream=stream,
   1432         stream_cls=stream_cls,
   1433         remaining_retries=remaining_retries,
   1434     )

File ~/miniconda3/envs/langgraph/lib/python3.11/site-packages/openai/_base_client.py:1519, in AsyncAPIClient._request(self, cast_to, options, stream, stream_cls, remaining_retries)
   1516         await err.response.aread()
   1518     log.debug(\"Re-raising status error\")
-> 1519     raise self._make_status_error_from_response(err.response) from None
   1521 return await self._process_response(
   1522     cast_to=cast_to,
   1523     options=options,
   (...)
   1526     stream_cls=stream_cls,
   1527 )

BadRequestError: Error code: 400 - {'error': {'message': \"'Subject Matter Expert' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.1.name'\", 'type': 'invalid_request_error', 'param': None, 'code': None}}"
}

### Description

The code worked some time before, but it failed later, it could be related to some lib version. But I have already upgraded all following libs:
langgraph
openai
langchain-openai
langchain_community
langchain_core

and it still failed.

### System Info

pip freeze | grep langchain
langchain==0.1.13
langchain-community==0.0.29
langchain-core==0.1.36
langchain-experimental==0.0.49
langchain-fireworks==0.1.1
langchain-google-genai==0.0.11
langchain-google-vertexai==0.1.2
langchain-mistralai==0.0.4
langchain-openai==0.1.1
langchain-text-splitters==0.0.1
langchainhub==0.1.14
mac
Python 3.11.7

**Comment by monuminu** [comment]
I am facing this issue. Is this issue resolved ?

**Comment by monuminu** [comment]
I am facing the same issue. When are we planning to merge this to master ?

**Comment by csellis** [comment]
@monuminu @ruanwz , strip the spaces and special characters in name creation

**Comment by monuminu** [comment]
@csellis could you please share the working notebook if possible or the line I need to change .

**Comment by DhavalThkkar** [comment]
@monuminu 

Your code:
```
initial_state = {
    "editor": perspectives.editors[0],
    "messages": [
        AIMessage(
            content=f"So you said you were writing an article on {example_topic}?",
            name="Subject Matter Expert",
        )
    ],
}
```

Fixed code:
```
initial_state = {
    "editor": perspectives.editors[0],
    "messages": [
        AIMessage(
            content=f"So you said you were writing an article on {example_topic}?",
            name="Subject_Matter_Expert",
        )
    ],
}```

The `name` parameter doesn't accept any spaces so replace them with underscore or remove them
