### ISSUE TITLE
DOC:  Fix Typographical Error in "with with" in Documentation/Comments

### ISSUE THREAD

**Issue by nirnay-raval-st10** [langchain-ai/langgraph#2537]
### Purpose

To correct a grammatical issue in the documentation or code comment for improved clarity and professionalism.

### Outcome

A clear and professional statement without repetitive wording.

### Background

The current statement includes a redundant "with with," which is a typographical error that could confuse readers or appear unpolished.

Original statement:
```
Now, we can just manually update our graph state with with the user input -
```
After Step-1 in
Location: https://langchain-ai.github.io/langgraph/how-tos/human_in_the_loop/wait-user-input/#simple-usage

### Actions

1. Locate the source of the statement in the documentation or code comments.
2. Update the statement to remove the redundant "with" for clarity:
   ```
   Now, we can just manually update our graph state with the user input -
   ```
3. Review the surrounding text to ensure no additional issues are present.
4. Commit the corrected text and reference this issue for tracking purposes.

**Comment by vbarda** [comment]
This is now resolved, thanks for reporting
