### ISSUE TITLE
INVALID_GRAPH_NODE_RETURN_VALUE on conditional node return

### ISSUE THREAD

**Issue by kevin-liangit** [langchain-ai/langgraph#2599]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
# Define state for application
class State(TypedDict):
    question: str
    context: List[Document]
    answer: str
    uploaded: str

def evaluate_answer(state: State):
    #if generated RAG answer is not good then generate only from LLM.
    if  "I don't know" in state["answer"]:
        print("generate instead")
        return "this is not useful"
    return "this is useful"




def lang_graph_init():
    # Compile application and test
    # graph_builder = StateGraph(State).add_sequence([retrieve, generate])
    # graph_builder.add_edge(START, "retrieve")
    
    # graph = graph_builder.compile()

    ###
    graph_builder = StateGraph(State)
    graph_builder.add_node("retrieve", retrieve) # retrieve
    graph_builder.set_entry_point("retrieve")
    graph_builder.add_node("generate", generate) # generatae
    graph_builder.add_node("evaluate", evaluate_answer) # grade documents
    graph_builder.add_node("generate_llm_response", generate_llm_response) # generatae

    graph_builder.add_edge("retrieve","generate")
    graph_builder.add_edge("generate","evaluate")
    graph_builder.add_conditional_edges(
    "evaluate",
    evaluate_answer,{"this is not useful":"generate_llm_response", "this is useful":END })
    graph_builder.add_edge("generate_llm_response",END)

    graph = graph_builder.compile()
    mermaid_png_data=graph.get_graph().draw_mermaid_png()

    with open('my_graph.png', 'wb') as f:
        f.write(mermaid_png_data)
```

### Error Message and Stack Trace (if applicable)

```shell
Expected dict, got this is useful For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/INVALID_GRAPH_NODE_RETURN_VALUE

or

Expected dict, got this is not useful For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/INVALID_GRAPH_NODE_RETURN_VALUE
```

### Description

With the following langgraph, evaluate is a conditional_node that is suppose to return the next node.

If "this is useful" then go to END
If "this is not useful" then go to generate_llm_response

However getting the errors as indicated. Why is it expecting a dictionary return of the from State? 

### System Info

langchain==0.3.8
langchain-community==0.3.8
langchain-core==0.3.21
langchain-google-community==2.0.2
langchain-google-vertexai==2.0.3
langchain-huggingface==0.1.2
langchain-openai==0.2.10
langchain-text-splitters==0.3.2
langgraph==0.2.53
langgraph-checkpoint==2.0.6
langgraph-sdk==0.1.36
langsmith==0.1.146

**Comment by gbaian10** [comment]
You can remove the `evaluate` Node, as the routing decision has already been handled by `conditional_edges`.

```py
def lang_graph_init():
    graph_builder = StateGraph(State)
    graph_builder.add_node("retrieve", lambda _: None)  # retrieve
    graph_builder.set_entry_point("retrieve")
    graph_builder.add_node("generate", lambda _: None)  # generatae
    graph_builder.add_node("generate_llm_response", lambda _: None)  # generatae

    graph_builder.add_edge("retrieve", "generate")
    graph_builder.add_conditional_edges(
        "generate",
        evaluate_answer,
        {"this is not useful": "generate_llm_response", "this is useful": END},
    )
    graph_builder.add_edge("generate_llm_response", END)

    graph = graph_builder.compile()
```

If you really want to keep `evaluate`, you can have it output a simple boolean result and save it in a field in the state, which `conditional_edges` can then read to determine the next node to proceed to.

**Comment by kevin-liangit** [comment]
Ah this was it. I mixed up my understanding of the implementation. thanks!
