### ISSUE TITLE
Checkpoint_NS not populating in the database when passed in config in stream method

### ISSUE THREAD

**Issue by ishaan812** [langchain-ai/langgraph#2604]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
def start(self, message = ""):
        thread_id = stripped_uuid4()
        config: RunnableConfig = RunnableConfig(
            configurable={
                "thread_id": thread_id,
                "checkpoint_ns": "story_promo"
            }   
        )
        initial_state = WorkflowState(
            messages=[],
            template=1,
            context="",
            product_count=0,
            product_name="",
            nodes=[], edges=[], cards=[], file="file",
        )
        latest_event = None
        for event in self.workflow_instance.stream(initial_state, config=config, stream_mode="values"):
            latest_event = event
        return thread_id, latest_event
```

### Description

In sample code above, the checkpoint with the corrrect threadId and initialised. But checkpoint_ns is still empty in the database. Tried to debug more, the checkpointer.postgres.init file the put function I presume is what is being used to store it in the database. The configurable object passed to the stream method is not getting passed to there correctly, although threadId is still being passed somehow and being used. Super confused how this is happening. I dont think the stream method in langgraph is using the put at all. Cant figure out how the stream method is calling the checkpointer at all

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.6.0: Fri Jul  5 17:56:39 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T8122
> Python Version:  3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)]

Package Information
-------------------
> langchain_core: 0.3.19
> langchain: 0.3.7
> langchain_community: 0.3.7
> langsmith: 0.1.142
> langchain_huggingface: 0.1.2
> langchain_openai: 0.2.6
> langchain_text_splitters: 0.3.2
> langgraph: 0.2.45

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.11.0
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> httpx: 0.27.2
> httpx-sse: 0.4.0
> huggingface-hub: 0.26.2
> jsonpatch: 1.33
> langgraph-checkpoint: 2.0.2
> langgraph-sdk: 0.1.35
> numpy: 1.26.4
> openai: 1.54.3
> orjson: 3.10.11
> packaging: 24.2
> pydantic: 2.9.2
> pydantic-settings: 2.6.1
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> sentence-transformers: 3.2.1
> SQLAlchemy: 2.0.35
> tenacity: 9.0.0
> tiktoken: 0.8.0
> tokenizers: 0.20.3
> transformers: 4.46.2
> typing-extensions: 4.12.2

**Comment by vbarda** [comment]
@ishaan812 `checkpoint_ns` is an internal field used by LangGraphj and is not meant to be used for tagging like `story_promo`. i would recommend using metadata for adding custom tags

**Comment by vbarda** [comment]
Closing this for now -- please use metadata instead

**Comment by rogerleung0411** [comment]
hi @vbarda, i'm trying to implement a custom saver base on BaseCheckpointSaver. I have a main graph and a subgraph, and the subgraph may also work independently as a particularly "main graph" in some scenerio. So, I think i need to specify the "checkpoint_ns" myself, but passing throught configurable does not work as i expected. So what's the best practice for this ? I Also see the official checkpoint implementation like langgraph-checkpoint-mongodb here:
https://github.com/langchain-ai/langchain-mongodb/blob/9f581b57859a02b907920b6fd6ae247bf86981a4/libs/langgraph-checkpoint-mongodb/langgraph/checkpoint/mongodb/saver.py#L376
is reading checkpoint_ns from configurable.
