### ISSUE TITLE
langgraph.errors.InvalidUpdateError: Must write to at least one of ['foo']

### ISSUE THREAD

**Issue by starrystar** [langchain-ai/langgraph#2644]
### Checked other resources

- [ ] This is a bug, not a usage question. For questions, please use GitHub Discussions.
- [X] I added a clear and detailed title that summarizes the issue.
- [X] I read what a minimal reproducible example is (https://stackoverflow.com/help/minimal-reproducible-example).
- [X] I included a self-contained, minimal example that demonstrates the issue INCLUDING all the relevant imports. The code run AS IS to reproduce the issue.

### Example Code

```python
from typing_extensions import TypedDict
from IPython.display import Image, display
from langgraph.graph import StateGraph, START, END
class State(TypedDict):
    foo: int
class TmpState(TypedDict):
    zoo: int
class node1:
    def __call__(self, state: State) -> TmpState:
        print("---Node 1---")
        return {"zoo": state['foo'] + 1}
class node2:
    def __call__(self, state: TmpState) -> State:
        print("---Node 2---")
        return {"foo": state['zoo'] + 1}
# Build graph
builder = StateGraph(State)
builder.add_node("node_1", node1())
builder.add_node("node_2", node2())
# Logic
builder.add_edge(START, "node_1")
builder.add_edge("node_1", "node_2")
builder.add_edge("node_2", END)
# Add
graph = builder.compile()
# View
display(Image(graph.get_graph().draw_mermaid_png()))
graph.invoke({"foo" : 1})
```

### Error Message and Stack Trace (if applicable)

```shell
<IPython.core.display.Image object>
---Node 1---
Traceback (most recent call last):
  File "d:\Software\anaconda3\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Software\anaconda3\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\f\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 71, in <module>
    cli.main()
  File "c:\Users\f\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 501, in main
    run()
  File "c:\Users\f\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 351, in run_file    runpy.run_path(target, run_name="__main__")
  File "c:\Users\f\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\f\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "c:\Users\f\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "D:\1毕设\code\My\2.py", line 28, in <module>
    graph.invoke({"foo" : 1})
  File "d:\Software\anaconda3\Lib\site-packages\langgraph\pregel\__init__.py", line 1551, in invoke
    for chunk in self.stream(
  File "d:\Software\anaconda3\Lib\site-packages\langgraph\pregel\__init__.py", line 1290, in stream
    for _ in runner.tick(
  File "d:\Software\anaconda3\Lib\site-packages\langgraph\pregel\runner.py", line 56, in tick
    run_with_retry(t, retry_policy)
  File "d:\Software\anaconda3\Lib\site-packages\langgraph\pregel\retry.py", line 29, in run_with_retry
    task.proc.invoke(task.input, config)
  File "d:\Software\anaconda3\Lib\site-packages\langgraph\utils\runnable.py", line 387, in invoke
    input = context.run(step.invoke, input, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Software\anaconda3\Lib\site-packages\langgraph\utils\runnable.py", line 159, in invoke
    ret = context.run(self.func, input, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Software\anaconda3\Lib\site-packages\langgraph\pregel\write.py", line 85, in _write
    self.do_write(
  File "d:\Software\anaconda3\Lib\site-packages\langgraph\pregel\write.py", line 138, in do_write
    raise InvalidUpdateError(
langgraph.errors.InvalidUpdateError: Must write to at least one of ['foo']
```

### Description

I'm trying to use the class node (instead of function node) to multiple schemas. I expect to see {'foo': 3}. Instead, it raise Exception.

### System Info

python -m langchain_core.sys_info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.19045
> Python Version:  3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.3.12
> langchain: 0.3.4
> langchain_community: 0.3.3
> langsmith: 0.1.128
> langchain_anthropic: 0.1.23
> langchain_cohere: 0.3.0
> langchain_experimental: 0.3.1
> langchain_openai: 0.2.3
> langchain_text_splitters: 0.3.0
> langchainhub: 0.1.21
> langgraph: 0.2.27

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.9.3
> anthropic: 0.34.2
> async-timeout: Installed. No version info available.
> cohere: 5.9.4
> dataclasses-json: 0.6.7
> defusedxml: 0.7.1
> httpx: 0.27.2
> jsonpatch: 1.33
> langgraph-checkpoint: 1.0.9
> numpy: 1.26.4
> openai: 1.52.2
> orjson: 3.10.7
> packaging: 23.2
> pandas: 2.1.4
> pydantic: 2.9.2
> pydantic-settings: 2.5.2
> PyYAML: 6.0.1
> requests: 2.31.0
> SQLAlchemy: 2.0.25
> tabulate: 0.9.0
> tenacity: 8.5.0
> tiktoken: 0.7.0
> types-requests: 2.32.0.20240914
> typing-extensions: 4.12.2

**Comment by hinthornw** [comment]
Hm the code ran for me as-is when I tried to reproduce

**Comment by starrystar** [comment]
> Hm the code ran for me as-is when I tried to reproduce

Sorry, you mean the code syntax is right? I thought maybe I write the wrong code, because I havn't seen the multi-schema in a class node syntax.

**Comment by hinthornw** [comment]
I mean this code block runs with no errors when i run it:
```
from typing_extensions import TypedDict
from IPython.display import Image, display
from langgraph.graph import StateGraph, START, END
class State(TypedDict):
    foo: int
class TmpState(TypedDict):
    zoo: int
class node1:
    def __call__(self, state: State) -> TmpState:
        print("---Node 1---")
        return {"zoo": state['foo'] + 1}
class node2:
    def __call__(self, state: TmpState) -> State:
        print("---Node 2---")
        return {"foo": state['zoo'] + 1}
# Build graph
builder = StateGraph(State)
builder.add_node("node_1", node1())
builder.add_node("node_2", node2())
# Logic
builder.add_edge(START, "node_1")
builder.add_edge("node_1", "node_2")
builder.add_edge("node_2", END)
# Add
graph = builder.compile()
# View
display(Image(graph.get_graph().draw_mermaid_png()))
graph.invoke({"foo" : 1})
```

**Comment by starrystar** [comment]
> I mean this code block runs with no errors when i run it:
> 
> ```
> from typing_extensions import TypedDict
> from IPython.display import Image, display
> from langgraph.graph import StateGraph, START, END
> class State(TypedDict):
>     foo: int
> class TmpState(TypedDict):
>     zoo: int
> class node1:
>     def __call__(self, state: State) -> TmpState:
>         print("---Node 1---")
>         return {"zoo": state['foo'] + 1}
> class node2:
>     def __call__(self, state: TmpState) -> State:
>         print("---Node 2---")
>         return {"foo": state['zoo'] + 1}
> # Build graph
> builder = StateGraph(State)
> builder.add_node("node_1", node1())
> builder.add_node("node_2", node2())
> # Logic
> builder.add_edge(START, "node_1")
> builder.add_edge("node_1", "node_2")
> builder.add_edge("node_2", END)
> # Add
> graph = builder.compile()
> # View
> display(Image(graph.get_graph().draw_mermaid_png()))
> graph.invoke({"foo" : 1})
> ```

Thank you so much, maybe I should check my version to the lastest.

**Comment by starrystar** [comment]
I've upgraded my version to the following, but it still doesn't work. Could you please offer some suggestions or insights on what might be the issue?
System Information
------------------
> OS:  Windows
> OS Version:  10.0.19045
> Python Version:  3.9.19 (main, May  6 2024, 20:12:36) [MSC v.1916 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.3.21
> langchain: 0.3.9
> langchain_community: 0.3.9
> langsmith: 0.1.147
> langchain_chroma: 0.1.4
> langchain_cohere: 0.3.3
> langchain_experimental: 0.3.3
> langchain_openai: 0.2.11
> langchain_text_splitters: 0.3.2
> langchainhub: 0.1.21
> langgraph_sdk: 0.1.43
