### ISSUE TITLE
Cannot run Langgraph dev for langgraph.js: AttributeError: 'str' object has no attribute 'parent'

### ISSUE THREAD

**Issue by debkanchan** [langchain-ai/langgraph#2647]
### Checked other resources

- [X] This is a bug, not a usage question. For questions, please use GitHub Discussions.
- [X] I added a clear and detailed title that summarizes the issue.
- [X] I read what a minimal reproducible example is (https://stackoverflow.com/help/minimal-reproducible-example).
- [X] I included a self-contained, minimal example that demonstrates the issue INCLUDING all the relevant imports. The code run AS IS to reproduce the issue.

### Example Code

```python
https://github.com/debkanchan/langgraph-repro.git
```

### Error Message and Stack Trace (if applicable)

```shell
(.venv) workspace  chain-of-thought ❯ langgraph dev                                                                        ✹ ✭
Traceback (most recent call last):
  File "/Users/debkanchan/Code/paralegal-ai/workspace/.venv/bin/langgraph", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/debkanchan/Code/paralegal-ai/workspace/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/debkanchan/Code/paralegal-ai/workspace/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/debkanchan/Code/paralegal-ai/workspace/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/debkanchan/Code/paralegal-ai/workspace/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/debkanchan/Code/paralegal-ai/workspace/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/debkanchan/Code/paralegal-ai/workspace/.venv/lib/python3.11/site-packages/langgraph_cli/analytics.py", line 96, in decorator
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/debkanchan/Code/paralegal-ai/workspace/.venv/lib/python3.11/site-packages/langgraph_cli/cli.py", line 595, in dev
    config_json = langgraph_cli.config.validate_config_file(config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/debkanchan/Code/paralegal-ai/workspace/.venv/lib/python3.11/site-packages/langgraph_cli/config.py", line 154, in validate_config_file
    package_json_path = config_path.parent / "package.json"
                        ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'parent'
```

### Description

* I am trying to run langgraph studio locally through langgraph cli
* I expect it to start langgraph studio
* Instead I get the error

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:14 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8103
> Python Version:  3.11.6 (v3.11.6:8b6ee5ba3b, Oct  2 2023, 11:18:21) [Clang 13.0.0 (clang-1300.0.29.30)]

Package Information
-------------------
> langchain_core: 0.3.21
> langsmith: 0.1.147
> langgraph_api: 0.0.6
> langgraph_cli: 0.1.61
> langgraph_license: Installed. No version info available.
> langgraph_sdk: 0.1.43
> langgraph_storage: Installed. No version info available.

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> click: 8.1.7
> cryptography: 43.0.3
> httpx: 0.28.0
> jsonpatch: 1.33
> jsonschema-rs: 0.25.1
> langgraph: 0.2.56
> langgraph-checkpoint: 2.0.8
> langsmith-pyo3: Installed. No version info available.
> orjson: 3.10.12
> packaging: 24.2
> pydantic: 2.10.3
> pyjwt: 2.10.1
> python-dotenv: 1.0.1
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> sse-starlette: 2.1.3
> starlette: 0.41.3
> structlog: 24.4.0
> tenacity: 8.5.0
> typing-extensions: 4.12.2
> uvicorn: 0.32.1
> watchfiles: 1.0.0

**Comment by hinthornw** [comment]
Note that we have not added support for `LangGraph.js` to the dev server yet.

**Comment by debkanchan** [comment]
@hinthornw any timeline for LangGraph.js support? I'm tired of waiting 5 min for LangGraph studio to open and then crash docker itself after 1 run. Then I have to restart my computer and do this process again.

**Comment by hinthornw** [comment]
I hear you! I believe Jacob or David on our team is going to try to get it in before year's end, but we haven't published a formal release date yet
