### ISSUE TITLE
Support AgentExecutor features via create_agent_executor

### ISSUE THREAD

**Issue by ccurme** [langchain-ai/langgraph#265]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

- [x] ~max_iterations~ handled by `recursion_limit` config?
- [X] ~max_execution_time~ OK with `step_timeout`? (via asyncio task timeouts)
- [X] return_intermediate_steps (always)
- [X] trim_intermediate_steps (via the message functioN)
- [ ] handle_parsing_errors
- [ X] early_stopping_method (via timeouts + recursion error handling)
- [ X] verbose (via deug)
- [x] [handle old style tools](https://github.com/langchain-ai/langchain/blob/3218463f6a3d841905648971735949a14a16e191/libs/langchain/langchain/agents/output_parsers/openai_tools.py#L45-L54) that do not expose a schema and expect a single string argument as an input
- [ ] ??

**Comment by hinthornw** [comment]
Think this can be closed now!
