### ISSUE TITLE
Parameter Name Mismatch in run_server() Function for langgraph-cli

### ISSUE THREAD

**Issue by kingsotn-twelve** [langchain-ai/langgraph#2671]
### Checked other resources

- [X] This is a bug, not a usage question. For questions, please use GitHub Discussions.
- [X] I added a clear and detailed title that summarizes the issue.
- [X] I read what a minimal reproducible example is (https://stackoverflow.com/help/minimal-reproducible-example).
- [X] I included a self-contained, minimal example that demonstrates the issue INCLUDING all the relevant imports. The code run AS IS to reproduce the issue.

### Example Code

```bash
# install langgraph-cli=0.1.61
pip install langgraph-cli -U

# cli cmd
langgraph dev --config langgraph.json --host 127.0.0.1 --port 2024 --debug-port 5678 --no-browser

# here is the langgraph.json
{
    "graphs": {"jockey": "jockey/app.py:jockey"},
    "env": ".env",
    "dependencies": ["."],
}
```

### Error Message and Stack Trace (if applicable)

```shell
File "venv/lib/python3.11/site-packages/langgraph_cli/cli.py", line 605, in dev
    run_server(
TypeError: run_server() got an unexpected keyword argument 'env'
```

### Description

I encountered a bug in the `run_server()` function where the parameter names `env_file`, `store`, and `wait_for_client` are mismatched or not behaving as expected. This issue is present in the file `langgraph_cli/cli.py`, specifically in the `dev` function where `run_server()` is called.

In `langgraph_cli/cli.py` [the params specified](https://github.com/langchain-ai/langgraph/blob/6784a5a5b1319e8c5d38d91de386776ceb7221c4/libs/cli/langgraph_cli/cli.py#L606) do not match the params defined:
```python
    run_server(
        host,
        port,
        not no_reload,
        graphs,
        n_jobs_per_worker=n_jobs_per_worker,
        open_browser=not no_browser,
        debug_port=debug_port,
        env=config_json.get("env"),
        store=config_json.get("store"),
        wait_for_client=wait_for_client,
    )
```

However, the function run_server() is defined as follows in `langgraph_api/cli.py`:
```python
def run_server(
    host: str = "127.0.0.1",
    port: int = 2024,
    reload: bool = False,
    graphs: dict | None = None,
    n_jobs_per_worker: int | None = None,
    env_file: str | None = None,
    open_browser: bool = False,
    debug_port: int | None = None,
):
```

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.6.0: Thu Sep 12 23:35:10 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T6030
> Python Version:  3.11.10 (main, Sep 30 2024, 15:19:48) [Clang 15.0.0 (clang-1500.3.9.4)]

Package Information
-------------------
> langchain_core: 0.3.19
> langchain: 0.3.7
> langsmith: 0.1.129
> langchain_openai: 0.2.9
> langchain_text_splitters: 0.3.2
> langgraph: 0.2.56

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.8
> async-timeout: Installed. No version info available.
> httpx: 0.27.2
> jsonpatch: 1.33
> langgraph-checkpoint: 2.0.7
> langgraph-sdk: 0.1.42
> numpy: 1.26.4
> openai: 1.54.5
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.9.2
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.35
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2

**Comment by hinthornw** [comment]
What version of `langgraph-api` are you on?

**Comment by kingsotn-twelve** [comment]
> What version of `langgraph-api` are you on?

langgraph-api             0.0.6
langgraph-api-inmem       0.0.4

**Comment by hinthornw** [comment]
Is fixed by updating version of the langgraph-api! 
We have also increased th emin bound for the langgraph-cli's dep so that this doesn't happen agian

**Comment by kingsotn-twelve** [comment]
thank you!
