### ISSUE TITLE
BadRequestError: 400 - "'Note Taker' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.2.name'"

### ISSUE THREAD

**Issue by kiranramanna** [langchain-ai/langgraph#272]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [ ] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [ ] I am sure that this is a bug in LangChain rather than my code.

### Example Code

issue is in this cell : https://github.com/langchain-ai/langgraph/blame/e30d5f13bf6714fbfd67098f962af22f5f4a7b73/examples/multi_agent/hierarchical_agent_teams.ipynb#L662
I tried referring documentation : https://python.langchain.com/docs/langgraph#define-the-nodes

### Error Message and Stack Trace (if applicable)

BadRequestError: Error code: 400 - {'error': {'message': "'Note Taker' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.2.name'", 'type': 'invalid_request_error', 'param': None, 'code': None}}

### Description

I am trying to run this notebook.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:43 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6000
> Python Version:  3.11.8 (main, Feb 26 2024, 15:36:12) [Clang 14.0.6 ]

Package Information
-------------------
> langchain_core: 0.1.39
> langchain: 0.1.14
> langchain_community: 0.0.31
> langsmith: 0.1.38
> langchain_experimental: 0.0.56
> langchain_openai: 0.1.1
> langchain_text_splitters: 0.0.1
> langgraph: 0.0.31

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langserve

**Comment by dhanashri3107** [comment]
Removing the space in Note Taker should work. For ex: Note_Taker

**Comment by hinthornw** [comment]
This is now fixed
