### ISSUE TITLE
LangGraph AsyncPostgresSaver throws an psycopg.errors.InvalidSqlStatementName error

### ISSUE THREAD

**Issue by HasnainKhanNiazi** [langchain-ai/langgraph#2755]
### Checked other resources

- [X] This is a bug, not a usage question. For questions, please use GitHub Discussions.
- [X] I added a clear and detailed title that summarizes the issue.
- [X] I read what a minimal reproducible example is (https://stackoverflow.com/help/minimal-reproducible-example).
- [X] I included a self-contained, minimal example that demonstrates the issue INCLUDING all the relevant imports. The code run AS IS to reproduce the issue.

### Example Code

```python
from dotenv import load_dotenv
load_dotenv()

from typing import (
    Annotated,
    Sequence,
    TypedDict,
)
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from langchain_openai import ChatOpenAI
from tools_new import TOOLS
import json
from langchain_core.messages import ToolMessage, SystemMessage
from langchain_core.runnables import RunnableConfig
from langgraph.graph import StateGraph, END
from prompt import prompt
from langchain_core.messages import HumanMessage
import asyncio
from psycopg import AsyncConnection
import os
from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver
from rich.console import Console
rich = Console()

connection_kwargs = {
    "autocommit": True,
    "prepare_threshold": 0,
}

model = ChatOpenAI(model="gpt-4o", temperature=0)

class AgentState(TypedDict):
    """The state of the agent."""

    messages: Annotated[Sequence[BaseMessage], add_messages]

model = model.bind_tools(TOOLS)
tools_by_name = {tool.name: tool for tool in TOOLS}

def tool_node(state: AgentState):
    outputs = []
    for tool_call in state["messages"][-1].tool_calls:
        tool_result = tools_by_name[tool_call["name"]].invoke(tool_call["args"])
        outputs.append(
            ToolMessage(
                content=json.dumps(tool_result),
                name=tool_call["name"],
                tool_call_id=tool_call["id"],
            )
        )
    return {"messages": outputs}

def call_model(
    state: AgentState,
    config: RunnableConfig,
):
    system_prompt = SystemMessage(
        prompt
    )
    response = model.invoke([system_prompt] + state["messages"], config)
    return {"messages": [response]}

def should_continue(state: AgentState):
    messages = state["messages"]
    last_message = messages[-1]
    if not last_message.tool_calls:
        return "end"
    else:
        return "continue"

# Define a new graph
workflow = StateGraph(AgentState)

workflow.add_node("agent", call_model)
workflow.add_node("tools", tool_node)

workflow.set_entry_point("agent")

# We now add a conditional edge
workflow.add_conditional_edges(
    "agent",
    should_continue,
    {
        "continue": "tools",
        "end": END,
    },
)

workflow.add_edge("tools", "agent")

async def run_graph(user_input: str, thread_id: str):
    with AsyncConnection.connect(os.getenv("DB_URI"), **connection_kwargs) as conn:
        checkpointer = AsyncPostgresSaver(conn)
        await checkpointer.setup()
        graph = workflow.compile(checkpointer=checkpointer)
        config = {"configurable": {"thread_id": thread_id}}
        async for event in graph.astream_events(
            {"messages": [HumanMessage(content=user_input)]},
            version = 'v2', stream_mode="values", config=config
        ):
            if "on_chat_model_stream" == event['event']:
                if len(event['data']["chunk"].content) > 0:
                    print(event['data']['chunk'].content, end='', flush=True)

if __name__ == '__main__':
    print("Running model")
    asyncio.run(run_graph(user_input="How are you?", thread_id="testing5"))


`DB_URI= postgresql://USER:PASSWORD@aws-0-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=disable`
```

### Error Message and Stack Trace (if applicable)

```shell
(langgraph) hasnain@Mac src % python example_3.py
/Users/hasnain/anaconda3/envs/langgraph/lib/python3.10/site-packages/langgraph/graph/graph.py:36: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain_core.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.

For example, replace imports like: `from langchain_core.pydantic_v1 import BaseModel`
with: `from pydantic import BaseModel`
or the v1 compatibility namespace if you are working in a code base that has not been fully upgraded to pydantic 2 yet. 	from pydantic.v1 import BaseModel

  from langgraph.pregel import Channel, Pregel
Traceback (most recent call last):
  File "/Users/hasnain/Documents/react-agent/src/example_3.py", line 143, in <module>
    main()
  File "/Users/hasnain/Documents/react-agent/src/example_3.py", line 112, in main
    checkpointer.setup()
  File "/Users/hasnain/anaconda3/envs/langgraph/lib/python3.10/site-packages/langgraph/checkpoint/postgres/__init__.py", line 89, in setup
    row = cur.execute(
  File "/Users/hasnain/anaconda3/envs/langgraph/lib/python3.10/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.DuplicatePreparedStatement: prepared statement "_pg3_0" already exists
```

### Description

I am using above code for `react-agent` with `memory`. Without memory, agent is working fine but when I add memory to it then sometime it gives me this error and sometime it works fine. I am not sure what could be wrong. I am using Supabase and above error is quite random, sometime I see that error immediately when I run the code and sometime agent takes an input and throws an error before or after giving the output. 

NOTE: Initially, I was using some tools where I was calling Database to fetch some data and I assumed that could be the cause  but I am getting this error even with `TavilySearchResults` tool as well.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020
> Python Version:  3.10.14 (main, May  6 2024, 14:42:37) [Clang 14.0.6 ]

Package Information
-------------------
> langchain_core: 0.3.24
> langchain: 0.3.0
> langchain_community: 0.3.0
> langsmith: 0.1.145
> langchain_anthropic: 0.2.1
> langchain_experimental: 0.3.0
> langchain_openai: 0.2.12
> langchain_text_splitters: 0.3.0
> langchainhub: 0.1.20
> langserve: 0.3.0

Other Dependencies
------------------
> aiohttp: 3.9.5
> anthropic: 0.34.2
> async-timeout: 4.0.3
> dataclasses-json: 0.6.7
> defusedxml: 0.7.1
> fastapi: 0.112.0
> httpx: 0.27.0
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.57.2
> orjson: 3.10.6
> packaging: 24.1
> pydantic: 2.9.2
> pydantic-settings: 2.5.2
> PyYAML: 6.0.1
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.31
> sse-starlette: 1.8.2
> tenacity: 8.5.0
> tiktoken: 0.7.0
> types-requests: 2.32.0.20240712
> typing-extensions: 4.12.2

**Comment by vbarda** [comment]
@HasnainKhanNiazi could you try using connection pool and see if this resolves your issue? https://langchain-ai.github.io/langgraph/how-tos/persistence_postgres/#use-async-connection

**Comment by keenborder786** [comment]
You need to use `AsyncConnectionPool`, please see the following:

```python
import json
from langchain_core.messages import ToolMessage, SystemMessage
from langchain_core.runnables import RunnableConfig
from langgraph.graph import StateGraph, END
from langchain_core.messages import HumanMessage
import asyncio
from psycopg_pool import AsyncConnectionPool
import os
from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver
import os

os.environ["DB_URI"] = "postgresql://postgres:password@localhost:5432/postgres"

connection_kwargs = {
    "autocommit": True,
    "prepare_threshold": 0,
}

model = ChatOpenAI(model="gpt-4o", temperature=0)
TOOLS = [WikipediaQueryRun(api_wrapper=WikipediaAPIWrapper())]
model = model.bind_tools(TOOLS)
tools_by_name = {tool.name: tool for tool in TOOLS}


class AgentState(TypedDict):
    """The state of the agent."""

    messages: Annotated[Sequence[BaseMessage], add_messages]

def tool_node(state: AgentState):
    outputs = []
    for tool_call in state["messages"][-1].tool_calls:
        tool_result = tools_by_name[tool_call["name"]].invoke(tool_call["args"])
        outputs.append(
            ToolMessage(
                content=json.dumps(tool_result),
                name=tool_call["name"],
                tool_call_id=tool_call["id"],
            )
        )
    return {"messages": outputs}

def call_model(
    state: AgentState,
    config: RunnableConfig,
):
    system_prompt = SystemMessage(
        "You are a helpful assistant. You are able to answer questions about Wikipedia. "
    )
    response = model.invoke([system_prompt] + state["messages"], config)
    return {"messages": [response]}

def should_continue(state: AgentState):
    messages = state["messages"]
    last_message = messages[-1]
    if not last_message.tool_calls:
        return "end"
    else:
        return "continue"

# Define a new graph
workflow = StateGraph(AgentState)

workflow.add_node("agent", call_model)
workflow.add_node("tools", tool_node)

workflow.set_entry_point("agent")

# We now add a conditional edge
workflow.add_conditional_edges(
    "agent",
    should_continue,
    {
        "continue": "tools",
        "end": END,
    },
)

workflow.add_edge("tools", "agent")

async def run_graph(user_input: str, thread_id: str):
    async with AsyncConnectionPool(os.getenv("DB_URI"), kwargs=connection_kwargs) as conn: # this has been updated
        checkpointer = AsyncPostgresSaver(conn)
        await checkpointer.setup()
        graph = workflow.compile(checkpointer=checkpointer)
        config = {"configurable": {"thread_id": thread_id}}
        async for event in graph.astream_events(
            {"messages": [HumanMessage(content=user_input)]},
            version = 'v2', stream_mode="values", config=config
        ):
            if "on_chat_model_stream" == event['event']:
                if len(event['data']["chunk"].content) > 0:
                    print(event['data']['chunk'].content, end='', flush=True)

if __name__ == '__main__':
    print("Running model")
    asyncio.run(run_graph(user_input="How are you?", thread_id="testing5"))


```

**Comment by HasnainKhanNiazi** [comment]
@vbarda @keenborder786 I have tried using `AsyncConnectionPool` but I am getting the same error:

`Running model
Traceback (most recent call last):
  File "/Users/hasnain/Documents/react-agent/src/example_2.py", line 220, in <module>
    asyncio.run(run_graph(user_input="How are you?", thread_id="testing5"))
  File "/Users/hasnain/anaconda3/envs/langgraph/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/hasnain/anaconda3/envs/langgraph/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/hasnain/Documents/react-agent/src/example_2.py", line 210, in run_graph
    async for event in graph.astream_events(
  File "/Users/hasnain/anaconda3/envs/langgraph/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1388, in astream_events
    async for event in event_stream:
  File "/Users/hasnain/anaconda3/envs/langgraph/lib/python3.10/site-packages/langchain_core/tracers/event_stream.py", line 1012, in _astream_events_implementation_v2
    await task
  File "/Users/hasnain/anaconda3/envs/langgraph/lib/python3.10/site-packages/langchain_core/tracers/event_stream.py", line 967, in consume_astream
    async for _ in event_streamer.tap_output_aiter(run_id, stream):
  File "/Users/hasnain/anaconda3/envs/langgraph/lib/python3.10/site-packages/langchain_core/tracers/event_stream.py", line 180, in tap_output_aiter
    first = await py_anext(output, default=sentinel)
  File "/Users/hasnain/anaconda3/envs/langgraph/lib/python3.10/site-packages/langchain_core/utils/aiter.py", line 76, in anext_impl
    return await __anext__(iterator)
  File "/Users/hasnain/anaconda3/envs/langgraph/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 1166, in astream
    async with AsyncPregelLoop(
  File "/Users/hasnain/anaconda3/envs/langgraph/lib/python3.10/site-packages/langgraph/pregel/loop.py", line 508, in __aenter__
    await self.checkpointer.aget_tuple(self.config)
  File "/Users/hasnain/anaconda3/envs/langgraph/lib/python3.10/site-packages/langgraph/checkpoint/postgres/aio.py", line 197, in aget_tuple
    await cur.execute(
  File "/Users/hasnain/anaconda3/envs/langgraph/lib/python3.10/site-packages/psycopg/cursor_async.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.DuplicatePreparedStatement: prepared statement "_pg3_0" already exists`

**Comment by HasnainKhanNiazi** [comment]
I changed keyword arguments to: `connection_kwargs = {
    "autocommit": True,
    "prepare_threshold": None,
}`

`prepare_threshold": None` and it is working for me now. Closing this issue
