### ISSUE TITLE
Node skipped during graph invocation

### ISSUE THREAD

**Issue by ashirgao** [langchain-ai/langgraph#2775]
### Checked other resources

- [X] This is a bug, not a usage question. For questions, please use GitHub Discussions.
- [X] I added a clear and detailed title that summarizes the issue.
- [X] I read what a minimal reproducible example is (https://stackoverflow.com/help/minimal-reproducible-example).
- [X] I included a self-contained, minimal example that demonstrates the issue INCLUDING all the relevant imports. The code run AS IS to reproduce the issue.

### Example Code

```python
from typing import Annotated, TypedDict
import operator

from langgraph.graph import START, END, StateGraph


class MyState(TypedDict):
    path: Annotated[list, operator.add]


class PathLoggingNode:
    def __init__(self, name: str):
        self._name = name

    def __call__(self, state: MyState):
        # print(f"Adding {self._name} to {state['path']}")
        return {"path": [self._name]}


def get_graph():
    def router_fn(state: MyState) -> list[str]:
        return "d"

    builder = StateGraph(MyState)

    builder.add_node("a", PathLoggingNode("node a"))
    builder.add_node("b", PathLoggingNode("node b"))
    builder.add_node("c", PathLoggingNode("node c"))
    builder.add_node("d", PathLoggingNode("node d"))
    builder.add_node("e", PathLoggingNode("node e"))

    builder.add_edge(START, "a")
    builder.add_conditional_edges("a", router_fn, ["b", "c", "d"])

    ## option 1
    builder.add_edge(["b", "c", "d"], "e")

    ## option 2
    # builder.add_edge("b","e")
    # builder.add_edge("c","e")
    # builder.add_edge("d","e")

    builder.add_edge("e", END)

    return builder.compile()


graph1 = get_graph()
op1= graph1.invoke({"path": []})
print(op1)
```

### Description

Expected output: `{'path': ['node a', 'node d', 'node e']}`
Instead, it does: `{'path': ['node a', 'node d']}`

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP PREEMPT_DYNAMIC Thu May  2 18:50:49 UTC 2024
> Python Version:  3.11.9 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)]

Package Information
-------------------
> langchain_core: 0.3.21
> langchain: 0.3.9
> langchain_community: 0.3.9
> langsmith: 0.1.147
> langchain_chroma: 0.1.4
> langchain_openai: 0.2.10
> langchain_text_splitters: 0.3.2
> langgraph_sdk: 0.1.40

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.11.8
> async-timeout: Installed. No version info available.
> chromadb: 0.5.21
> dataclasses-json: 0.6.7
> fastapi: 0.115.6
> httpx: 0.28.0
> httpx-sse: 0.4.0
> jsonpatch: 1.33
> langsmith-pyo3: Installed. No version info available.
> numpy: 1.26.4
> openai: 1.55.3
> orjson: 3.10.12
> packaging: 24.2
> pydantic: 2.10.2
> pydantic-settings: 2.6.1
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.35
> tenacity: 9.0.0
> tiktoken: 0.8.0
> typing-extensions: 4.12.2

**Comment by ashirgao** [comment]
I suspect the simultaneous usage of `add_conditional_edge` and a multi-source `add_edge` leads to this behavior.
 
Replacing the multi-source `add_edge` with single source `add_edge` calls generates expected output (provided as option 2 in the snippet ). Interestingly, both approaches generate the same `draw_mermaid()` response.

**Comment by gbaian10** [comment]
https://github.com/langchain-ai/langgraph/issues/1462#issuecomment-2313052133
This comment can answer your question. 

For option 1, the graph must complete `b`, `c`, and `d` before go to e. However, it can't reach `b` and `c`, so it can never reach `e`. 
For option 2, the graph only needs to complete one of `b`, `c`, or `d` to go to `e`.

**Comment by ashirgao** [comment]
Thanks @gbaian10. I previously thought option1 and option2 were identical. 

I found the generated diagram to be intuitive for option 2 where the graph only needs to complete one of `b`,`c`, or `d` to go to `e`. 

I'm unsure which mermaid edge or shape would best illustrate this difference.
