### ISSUE TITLE
Langgraph dev (cli) error with library

### ISSUE THREAD

**Issue by rd-rugg** [langchain-ai/langgraph#2841]
### Checked other resources

- [X] This is a bug, not a usage question. For questions, please use GitHub Discussions.
- [X] I added a clear and detailed title that summarizes the issue.
- [X] I read what a minimal reproducible example is (https://stackoverflow.com/help/minimal-reproducible-example).
- [X] I included a self-contained, minimal example that demonstrates the issue INCLUDING all the relevant imports. The code run AS IS to reproduce the issue.

### Example Code

```python
Error is inside an internal import.
```

### Error Message and Stack Trace (if applicable)

```shell
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\cwzda\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\cwzda\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\cwzda\AppData\Local\pypoetry\Cache\virtualenvs\chat-analyzer-9qU6P2e3-py3.11\Lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\cwzda\AppData\Local\pypoetry\Cache\virtualenvs\chat-analyzer-9qU6P2e3-py3.11\Lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cwzda\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\cwzda\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cwzda\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\cwzda\AppData\Local\pypoetry\Cache\virtualenvs\chat-analyzer-9qU6P2e3-py3.11\Lib\site-packages\uvicorn\server.py", line 70, in serve
    await self._serve(sockets)
  File "C:\Users\cwzda\AppData\Local\pypoetry\Cache\virtualenvs\chat-analyzer-9qU6P2e3-py3.11\Lib\site-packages\uvicorn\server.py", line 77, in _serve
    config.load()
  File "C:\Users\cwzda\AppData\Local\pypoetry\Cache\virtualenvs\chat-analyzer-9qU6P2e3-py3.11\Lib\site-packages\uvicorn\config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cwzda\AppData\Local\pypoetry\Cache\virtualenvs\chat-analyzer-9qU6P2e3-py3.11\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cwzda\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\cwzda\AppData\Local\pypoetry\Cache\virtualenvs\chat-analyzer-9qU6P2e3-py3.11\Lib\site-packages\langgraph_api\server.py", line 12, in <module>
    from langgraph_api.api import routes
  File "C:\Users\cwzda\AppData\Local\pypoetry\Cache\virtualenvs\chat-analyzer-9qU6P2e3-py3.11\Lib\site-packages\langgraph_api\api\__init__.py", line 7, in <module>
    from langgraph_api.api.assistants import assistants_routes
  File "C:\Users\cwzda\AppData\Local\pypoetry\Cache\virtualenvs\chat-analyzer-9qU6P2e3-py3.11\Lib\site-packages\langgraph_api\api\assistants.py", line 10, in <module>
    from langgraph_api.graph import get_assistant_id, get_graph
  File "C:\Users\cwzda\AppData\Local\pypoetry\Cache\virtualenvs\chat-analyzer-9qU6P2e3-py3.11\Lib\site-packages\langgraph_api\graph.py", line 24, in <module>
    from langgraph_api.js.remote import RemotePregel
  File "C:\Users\cwzda\AppData\Local\pypoetry\Cache\virtualenvs\chat-analyzer-9qU6P2e3-py3.11\Lib\site-packages\langgraph_api\js\remote.py", line 30, in <module>
    from langgraph_api.route import ApiResponse
  File "C:\Users\cwzda\AppData\Local\pypoetry\Cache\virtualenvs\chat-analyzer-9qU6P2e3-py3.11\Lib\site-packages\langgraph_api\route.py", line 17, in <module>
    from langgraph_api.utils import set_auth_ctx
  File "C:\Users\cwzda\AppData\Local\pypoetry\Cache\virtualenvs\chat-analyzer-9qU6P2e3-py3.11\Lib\site-packages\langgraph_api\utils.py", line 8, in <module>
    from langgraph_sdk import Auth
ImportError: cannot import name 'Auth' from 'langgraph_sdk' (C:\Users\cwzda\AppData\Local\pypoetry\Cache\virtualenvs\chat-analyzer-9qU6P2e3-py3.11\Lib\site-packages\langgraph_sdk\__init__.py)
```

### Description

I am trying to run langgraph CLI but I am getting Import Errors.
For dependency management, I am using poetry. Here is the full requirements:

python = "^3.11"
pandas = "^2.2.3"
openai = "^1.57.0"
langchain = "^0.3.9"
tiktoken = "^0.8.0"
langchain-openai = "^0.2.11"
langchain-anthropic = "^0.3.0"
instructor = "^1.7.0"
tavily-python = "^0.5.0"
langgraph = "^0.2.56"
fastapi = "^0.115.6"
twilio = "^9.3.8"
python-dotenv = "^1.0.1"
langchain-community = "^0.3.10"
supabase = "^2.10.0"
sqlmodel = "^0.0.22"
boto3 = "^1.35.83"
uvicorn = "^0.34.0"
python-multipart = "^0.0.20"
langgraph-cli = {extras = ["inem"], version = "^0.1.65"}

### System Info

langgraph dev

**Comment by hinthornw** [comment]
Hi can you update `langgraph-cli[inmem]` please?

**Comment by rd-rugg** [comment]
If I set it to langgraph-cli = {extras = ["inem"], version = "^0.2.60"}

I get:
Because chat-analyzer depends on langgraph-cli[inem] (>=0.2.60,<0.3.0) which doesn't match any versions, version solving failed.

**Comment by rd-rugg** [comment]
With langgraph up I get this different error:

`\ Building...#0 building with "default" instance using docker driver

#1 [langgraph-api internal] load build definition from Dockerfile
#1 transferring dockerfile: 314B done
#1 DONE 0.0s

#2 [langgraph-api internal] load metadata for docker.io/langchain/langgraph-api:3.11
#2 DONE 0.0s

#3 [langgraph-api internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [langgraph-api 1/4] FROM docker.io/langchain/langgraph-api:3.11
#4 DONE 0.0s

#5 [langgraph-api internal] load build context
#5 transferring context: 34.33kB 0.0s done
#5 DONE 0.0s

#6 [langgraph-api 2/4] ADD . /deps/chat_analyzer
#6 CACHED

#7 [langgraph-api 3/4] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*
#7 0.541 Obtaining file:///deps/chat_analyzer
#7 0.543   Installing build dependencies: started
#7 1.869   Installing build dependencies: finished with status 'done'
#7 1.871   Checking if build backend supports build_editable: started
#7 1.943   Checking if build backend supports build_editable: finished with status 'done'
#7 1.945   Getting requirements to build editable: started
#7 2.018   Getting requirements to build editable: finished with status 'done'
#7 2.020   Preparing editable metadata (pyproject.toml): started
#7 2.200   Preparing editable metadata (pyproject.toml): finished with status 'error'
#7 2.204   error: subprocess-exited-with-error
#7 2.204
#7 2.204   × Preparing editable metadata (pyproject.toml) did not run successfully.
#7 2.204   │ exit code: 1
#7 2.204   ╰─> [24 lines of output]
#7 2.204       Traceback (most recent call last):
#7 2.204         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#7 2.204           main()
#7 2.204         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#7 2.204           json_out['return_val'] = hook(**hook_input['kwargs'])
#7 2.204                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#7 2.204         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
#7 2.204           return hook(metadata_directory, config_settings)
#7 2.204                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#7 2.204         File "/tmp/pip-build-env-it1vcfk6/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
#7 2.204           builder = WheelBuilder(poetry)
#7 2.204                     ^^^^^^^^^^^^^^^^^^^^
#7 2.204         File "/tmp/pip-build-env-it1vcfk6/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 62, in __init__
#7 2.204           super().__init__(poetry, executable=executable)
#7 2.204         File "/tmp/pip-build-env-it1vcfk6/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/builder.py", line 55, in __init__
#7 2.204           self._meta = Metadata.from_package(self._package)
#7 2.204                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#7 2.204         File "/tmp/pip-build-env-it1vcfk6/overlay/lib/python3.11/site-packages/poetry/core/masonry/metadata.py", line 58, in from_package
#7 2.204           with readme.open(encoding="utf-8") as f:
#7 2.204                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#7 2.204         File "/usr/local/lib/python3.11/pathlib.py", line 1044, in open
#7 2.204           return io.open(self, mode, buffering, encoding, errors, newline)
#7 2.204                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#7 2.204       FileNotFoundError: [Errno 2] No such file or directory: '/deps/chat_analyzer/README.md'
#7 2.204       [end of output]
#7 2.204
#7 2.204   note: This error originates from a subprocess, and is likely not a problem with pip.
#7 2.205 error: metadata-generation-failed
#7 2.205
#7 2.205 × Encountered error while generating package metadata.
#7 2.205 ╰─> See above for output.
#7 2.205
#7 2.205 note: This is an issue with the package mentioned above, not pip.
#7 2.205 hint: See above for details.
#7 2.436
#7 2.436 [notice] A new release of pip is available: 24.0 -> 24.3.1
#7 2.436 [notice] To update, run: pip install --upgrade pip
#7 ERROR: process "/bin/sh -c PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*" did not complete successfully: exit code: 1
------
 > [langgraph-api 3/4] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*:
2.205 error: metadata-generation-failed
2.205
2.205 × Encountered error while generating package metadata.
2.205 ╰─> See above for output.
2.205
2.205 note: This is an issue with the package mentioned above, not pip.
2.205 hint: See above for details.
2.436
2.436 [notice] A new release of pip is available: 24.0 -> 24.3.1
2.436 [notice] To update, run: pip install --upgrade pip
------
failed to solve: process "/bin/sh -c PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*" did not complete successfully: exit code: 1`

**Comment by vbarda** [comment]
@rd-rugg you have a typo `inem` - should be `inmem`

**Comment by rd-rugg** [comment]
@vbarda oh thanks for spotting it. 
I am getting this error now:
  File "C:\Users\cwzda\Desktop\code\misc\chat_analyzer\agent\config.py", line 18, in is_anthropic
    return config["provider"] == ModelProvider.ANTHROPIC
    

Code is:
```

def get_llm(config: AgentConfig) -> BaseChatModel:
    """Initialize the appropriate LLM based on config"""
    if is_anthropic(config):
        return ChatAnthropic(
            model=config["model_name"],
            temperature=0.2
        )
    
    return ChatOpenAI(
        model=config["model_name"],
        temperature=0.2
    )

def build_agent_graph(config: AgentConfig) -> StateGraph:
    """Build the agent's processing graph"""
    memory_saver = MemorySaver()

    # Initialize tools
    #search_tool = TavilySearchResults(max_results=config["max_search_results"])
    tools = [
        search_gift_ideas_tool,
    ]
    
    # Initialize the LLM based on provider
    llm = get_llm(config)
    
    # Create system message
    system_message = SystemMessage(content=INITIAL_PROMPT)
    
    # Bind tools to LLM
    llm_with_tools = llm.bind_tools(tools)
    tool_node = ToolNode(tools=tools)


    # Define chatbot node
    def chatbot(state: GraphStateOverall):
        if state.get("reccommendations"):
            print("recommendation YES")
            return {"messages": state["reccommendations"]}
        else:
            all_messages = state["messages"]
            response = llm_with_tools.invoke(all_messages)
            print("recommendation NO")
            print(response)
            return {"messages": [response]}
    
    # Build graph
    graph_builder = StateGraph(GraphStateOverall)
    graph_builder.add_node("chatbot", chatbot)
    graph_builder.add_node("tools", tool_node)

    # Add edges
    graph_builder.add_conditional_edges(
        "chatbot",
        tools_condition,
    )
    graph_builder.add_edge("tools", "chatbot")
    graph_builder.add_edge(START, "chatbot")
    
    return graph_builder.compile(checkpointer=memory_saver) 
```


And Config is:

```
from enum import Enum
from typing import TypedDict

class ModelProvider(Enum):
    OPENAI = "openai"
    ANTHROPIC = "anthropic"

class AgentConfig(TypedDict):
    model_name: str  # default: "gpt-4-mini"
    provider: ModelProvider  # default: ModelProvider.OPENAI
    max_search_results: int  # default: 2
    thread_id: str
    user_id: str 
    gift_advisor_number: str

# Helper functions to replace the properties
def is_anthropic(config: AgentConfig) -> bool:
    return config["provider"] == ModelProvider.ANTHROPIC

def is_openai(config: AgentConfig) -> bool:
    return config["provider"] == ModelProvider.OPENAI
```

Not sure if it is related but is there a difference between:
from langchain_core.runnables.config import RunnableConfig
from langchain_core.runnables import RunnableConfig

?

Thank you!

**Comment by vbarda** [comment]
it would need to be `config["configurable"]["provider"]` -- lmk if that solves it for you. going to close since the original issue was resolved

**Comment by rd-rugg** [comment]
@vbarda Unfortunately not. Now it complains about key "configurable"


  File "C:\Users\cwzda\Desktop\code\misc\chat_analyzer\./agent/graph.py", line 56, in build_agent_graph
    llm = get_llm(config)
          ^^^^^^^^^^^^^^^
  File "C:\Users\cwzda\Desktop\code\misc\chat_analyzer\./agent/graph.py", line 31, in get_llm
    print(f"DEBUG CONFIGURABLE: {config['configurable']}")
    
  KeyError: 'configurable'

**Comment by rd-rugg** [comment]
@vbarda can you please reopen the issue? This is not solved yet

**Comment by josiahcoad** [comment]
For me the problem was that I did `pipx install langgraph-cli` and then was trying to use a venv (uv) for dep management. So `langraph dev` was looking in my system deps.
