### ISSUE TITLE
【Question】Why not implement DAG in LCEL？

### ISSUE THREAD

**Issue by csunny** [langchain-ai/langgraph#29]
This is very confusing for users who need to understand both LECL and langgraph. Why not implement DAG in LCEL？

For comparison, we implemented AWEL(Agentic Workflow Expression Language) orchestration at [DB-GPT](https://github.com/eosphoros-ai/DB-GPT), and we think `AWEL  and  agents are all you need.`

![image](https://github.com/langchain-ai/langgraph/assets/17919400/d095bc31-3475-45f8-8f96-27778d388ace)

# Example

https://github.com/eosphoros-ai/DB-GPT/blob/main/examples/awel/simple_chat_history_example.py

```
HttpTrigger(node_id=b71f0ccc-4539-445e-8d87-1ec5ef6e7e83)
 -> MapOperator(node_id=23d11ff8-a1d4-4541-a1ff-adfb0eadd614)
   -> ChatHistoryPromptComposerOperator(node_id=3ee4c2af-d625-445b-a0f3-60863404d82e)
     -> LLMBranchOperator(node_id=bdc20002-b9e9-4ce8-9211-5aba83f4c16e)
       -> LLMOperator(node_id=b4c3fe48-a9d8-4968-a128-df5a6b6edd4c, node_name=llm_task)
      |  -> MapOperator(node_id=ce768e92-5299-43ab-ac04-09755b5f19e2)
      |    -> JoinOperator(node_id=f33f239e-90dd-4dd4-bc12-30d6d0912cfb)
       -> StreamingLLMOperator(node_id=ca529d57-1bd7-479c-9047-5cb5512ade8e, node_name=streaming_llm_task)
         -> OpenAIStreamingOutputOperator(node_id=1952037e-775a-4c9c-a8c3-7ca678f15871)
           -> JoinOperator(node_id=f33f239e-90dd-4dd4-bc12-30d6d0912cfb)
```
![image](https://github.com/langchain-ai/langgraph/assets/17919400/c7572c8e-25a0-40bb-9fe5-92dcc24d4552)

```
with DAG("dbgpt_awel_simple_chat_history") as multi_round_dag:
    # Receive http request and trigger dag to run.
    trigger = HttpTrigger(
        "/examples/simple_history/multi_round/chat/completions",
        methods="POST",
        request_body=TriggerReqBody,
        streaming_predict_func=lambda req: req.stream,
    )
    prompt = ChatPromptTemplate(
        messages=[
            SystemPromptTemplate.from_template("You are a helpful chatbot."),
            MessagesPlaceholder(variable_name="chat_history"),
            HumanPromptTemplate.from_template("{user_input}"),
        ]
    )

    composer_operator = ChatHistoryPromptComposerOperator(
        prompt_template=prompt,
        last_k_round=5,
        storage=InMemoryStorage(),
        message_storage=InMemoryStorage(),
    )

    # Use BaseLLMOperator to generate response.
    llm_task = LLMOperator(task_name="llm_task")
    streaming_llm_task = StreamingLLMOperator(task_name="streaming_llm_task")
    branch_task = LLMBranchOperator(
        stream_task_name="streaming_llm_task", no_stream_task_name="llm_task"
    )
    model_parse_task = MapOperator(lambda out: out.to_dict())
    openai_format_stream_task = OpenAIStreamingOutputOperator()
    result_join_task = JoinOperator(
        combine_function=lambda not_stream_out, stream_out: not_stream_out or stream_out
    )

    req_handle_task = MapOperator(
        lambda req: ChatComposerInput(
            context=ModelRequestContext(
                conv_uid=req.context.conv_uid, stream=req.stream
            ),
            prompt_dict={"user_input": req.messages},
            model_dict={
                "model": req.model,
                "context": req.context,
                "stream": req.stream,
            },
        )
    )

    trigger >> req_handle_task >> composer_operator >> branch_task

    # The branch of no streaming response.
    branch_task >> llm_task >> model_parse_task >> result_join_task
    # The branch of streaming response.
    branch_task >> streaming_llm_task >> openai_format_stream_task >> result_join_task
```

**Comment by nfcampos** [comment]
Hi @csunny LCEL works perfectly fine for DAGs (Directed Acyclical Graphs, ie. graphs without cycles). LangGraph is meant to serve more complex use cases like agents that need cycles (ie. loops) which cannot be expressed as a DAG.

**Comment by csunny** [comment]
@nfcampos  Thanks for your reply, i will take a deep learning.

**Comment by limafang** [comment]
我的想法是，因为语法上的问题，首先 LCEL 本身要实现 loop 和 condition 的情况就比较困难，为了避免更冗余的情况（本身 LCEL 就是为了简化线性流程上 langchain 陈旧的繁琐写法），同时 loop 和 condition 这两种情况又非常重要，举几个可能操作场景，我希望 llm 给我一篇技术文稿，完成后我要做审稿修改使他根据我的意见完善自己的创作成果，这时候我们就需要根据人类输入 condition 来判断继续完善内容，重新撰写内容还是结束任务，使用 LCEL 进行线性的 SOP 编排很难实现这样的场景，同时 langgraph 为 SOP 的编排提供了更多天马行空的可能，我们可以覆盖线性，树形，更多可能的应用场景，因此 langgraph 的实现还是非常有必要的

**Comment by csunny** [comment]
@limafang  Why not use LLMs multi-agents Auto-plan?

**Comment by limafang** [comment]
@csunny Perhaps LLMs can currently plan independently for some simple tasks, but LLM's intelligence is limited on some larger tasks. From my personal perspective, a standard structure (node and edge) is convenient for users to use. In fact, it is also helping LLM to simplify planning problems. For future LLMs, their plans do not need to be generated in a complex reasoning space. Instead, they can generate nodes and edges and simply organize them together. I think this is feasible
