### ISSUE TITLE
DOC: Issue with Agent Names (for Notebook Example: multi-agent-collaboration.ipynb)

### ISSUE THREAD

**Issue by JShollaj** [langchain-ai/langgraph#297]
### Issue with current documentation:

After invoking the agent workflow in the final cell, we receive the following error:

`BadRequestError: Error code: 400 - {'error': {'message': "'Chart Generator' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.5.name'", 'type': 'invalid_request_error', 'param': None, 'code': None}}`

### Idea or request for content:

The way I resolved it is by changing the names of the agent from "Chart Generator" to "Chart". Appearently, the issue is with spacing in agent names when collaborating.

**Comment by hinthornw** [comment]
Should be updated now
