### ISSUE TITLE
langgraph cannot reference other functions within a single tool.

### ISSUE THREAD

**Issue by JemicyChu** [langchain-ai/langgraph#301]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
@tool
def mytool(param1,param2):
  """description"""
  print("this is mytool)
  _second_tool(param1)
  print("end")

def _second_tool(param1):
  print("this is second")
```

### Error Message and Stack Trace (if applicable)

No error happend.
print like :
```
this is mytool
end
```

### Description

There were no errors in this process, just other functions in between that weren't executed and were skipped.

### System Info

langgraph verion 0.0.34-0.0.30.I've been through trying these versions

**Comment by hinthornw** [comment]
Please provide actual langgraph code - the above doesn't involve langgraph at all
