### ISSUE TITLE
can not set recursion_limit in config with langserve

### ISSUE THREAD

**Issue by weiminw** [langchain-ai/langgraph#334]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

I create a graph with langserve.
```
workflow = StateGraph(PlanExecute)
.... add the nodes and edges...
c =  workflow.compile()

.....
app = FastAPI(
    title="AI Agent Sever",
    version="0.2.9",
    description="AI Agent Sever"
)
add_routes(
    app,
    c,
    path="/pe"
)
```
when I use following request invoke. I found the "recursion_limit" parameter config not used.
```
{
    "input": {
        "transaction": "xxxxxxxx.",
        "conversation_id": ""
    },
    "config": {
        "configurable": {
            "recursion_limit": 2
        }
    }
}
```

### Description

I create a graph with langserve.
```
workflow = StateGraph(PlanExecute)
.... add the nodes and edges...
c =  workflow.compile()

.....
app = FastAPI(
    title="AI Agent Sever",
    version="0.2.9",
    description="AI Agent Sever"
)
add_routes(
    app,
    c,
    path="/pe"
)
```
when I use following request invoke. I found the "recursion_limit" parameter config not used.
```
{
    "input": {
        "transaction": "xxxxxxxx.",
        "conversation_id": ""
    },
    "config": {
        "configurable": {
            "recursion_limit": 2
        }
    }
}
```

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2
> Python Version:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.1.43
> langchain: 0.1.16
> langchain_community: 0.0.33
> langsmith: 0.1.31
> langchain_openai: 0.1.3
> langchain_text_splitters: 0.0.1
> langchainhub: 0.1.15
> langgraph: 0.0.37
> langserve: 0.1.0

**Comment by hinthornw** [comment]
Seems this is resolved? Will mark as closed unless others run into this.
