### ISSUE TITLE
I running multi-agent-collaboration.ipynb, add app.get_graph().print_ascii(), raise error

### ISSUE THREAD

**Issue by yang20150702** [langchain-ai/langgraph#335]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

workflow = StateGraph(AgentState)

workflow.add_node("Researcher", research_node)
workflow.add_node("Chart Generator", chart_node)
workflow.add_node("call_tool", tool_node)

workflow.add_conditional_edges(
    "Researcher",
    router,
    {"continue": "Chart Generator", "call_tool": "call_tool", "end": END},
)
workflow.add_conditional_edges(
    "Chart Generator",
    router,
    {"continue": "Researcher", "call_tool": "call_tool", "end": END},
)

workflow.add_conditional_edges(
    "call_tool",
    # Each agent node updates the 'sender' field
    # the tool calling node does not, meaning
    # this edge will route back to the original agent
    # who invoked the tool
    lambda x: x["sender"],
    {
        "Researcher": "Researcher",
        "Chart Generator": "Chart Generator",
    },
)
workflow.set_entry_point("Researcher")
app = workflow.compile()

app.get_graph().print_ascii()

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/xxx/src/agent/multi-agent.py", line 199, in <module>
    app.get_graph().print_ascii()
    ^^^^^^^^^^^^^^^
  File "/xxx/venv/lib/python3.11/site-packages/langgraph/graph/graph.py", line 413, in get_graph
    cond = graph.add_node(branch.condition, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxx/venv/lib/python3.11/site-packages/langchain_core/runnables/graph.py", line 207, in add_node
    raise ValueError(f"Node with id {id} already exists")
ValueError: Node with id router already exists

### Description

I running multi-agent-collaboration.ipynb, add app.get_graph().print_ascii(), raise error

### System Info

langgraph=0.0.38

**Comment by nfcampos** [comment]
Fixed in #336
