### ISSUE TITLE
DOC: Tutorial introduction is using tools_condition which is not in the current version 0.0.38

### ISSUE THREAD

**Issue by TVScoundrel** [langchain-ai/langgraph#348]
### Issue with current documentation:

This page:
https://langchain-ai.github.io/langgraph/tutorials/introduction/#part-2-enhancing-the-chatbot-with-tools

```
from langgraph.prebuilt import tools_condition

# The `tools_condition` function returns "action" if the chatbot asks to use a tool, and "__end__" if
# it is fine directly responding. This conditional routing defines the main agent loop.
graph_builder.add_conditional_edges(
    "chatbot",
    tools_condition,
    # The following dictionary lets you tell the graph to interpret the condition's outputs as a specific node
    # It defaults to the identity function, but if you
    # want to use a node named something else apart from "action",
    # You can update the value of the dictionary to something else
    # e.g., "action": "my_tools"
    {"action": "action", "__end__": "__end__"},
)
# Any time a tool is called, we return to the chatbot to decide the next step
graph_builder.add_edge("action", "chatbot")
graph_builder.set_entry_point("chatbot")
graph = graph_builder.compile()
```
The current version https://pypi.org/project/langgraph/ is at 0.0.38 which does not have the prebuilt `tools_condition` yet.

### Idea or request for content:

Probably either mention that this is bleeding edge, or do a new release on https://pypi.org/project/langgraph/

**Comment by hinthornw** [comment]
Sorry about that! I released the docs before we cut the release. Langgraph is now on 0.0.44 so I'll mark this as closed.

I'll try to be more vigilant at marking minimum version indications in the docs

**Comment by PARTHIBAN-007** [comment]
tools_condition in langgraph.prebuilt only decides the tools not the END action.
