### ISSUE TITLE
DOC: Manually updating the state causes a bad request error

### ISSUE THREAD

**Issue by TVScoundrel** [langchain-ai/langgraph#351]
### Issue with current documentation:

In this section: https://langchain-ai.github.io/langgraph/tutorials/introduction/#what-if-you-want-to-overwrite-existing-messages

```
events = graph.stream(None, config)
for event in events:
    for value in event.values():
        if isinstance(value["messages"][-1], BaseMessage):
            print("Assistant:", value["messages"][-1].content)
````

The tutorial is using Claude 3 haiku but, using any of the claude 3 models, Claud 3 returns a bad request:

"name": "BadRequestError",
	"message": "Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages.2: Did not find 1 `tool_result` block(s) at the beginning of this message. Messages following `tool_use` blocks must begin with a matching number of `tool_result` blocks.'}}"

gpt-4 is working as expected though.

### Idea or request for content:

gpt-4 is doing it correctly but is less verbose so the first part of the tutorial gives less interesting feedback so it should probably be updated so that the expectations of Claude are met.

**Comment by hinthornw** [comment]
Should be fixed by this update to serialization: https://github.com/langchain-ai/langchain/pull/21342

**Comment by AtmehEsraa** [comment]
@TVScoundrel how did you solve it ?

**Comment by ikergalarza** [comment]
i'd also know to fix it!
