### ISSUE TITLE
Adding message history (memory)

### ISSUE THREAD

**Issue by jktoh** [langchain-ai/langgraph#37]
Seems like [RunnableWithMessageHistory](https://python.langchain.com/docs/expression_language/how_to/message_history) is not yet compatible with langgraph.

Any recommendation at the moment to integrate memory into langgraphs?

**Comment by streamride** [comment]
hi, did you find any solution?

**Comment by jktoh** [comment]
Instead of using RunnableWithMessageHistory, have to follow this instead.
https://github.com/langchain-ai/langgraph/blob/main/examples%2Fpersistence.ipynb
