### ISSUE TITLE
STORM example calls with_structured_output that is not implemented for OpenAI

### ISSUE THREAD

**Issue by chiefsfumes** [langchain-ai/langgraph#438]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

from langchain_core.pydantic_v1 import BaseModel, Field
from typing import List, Optional
from langchain_core.prompts import ChatPromptTemplate

direct_gen_outline_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are a Wikipedia writer. Write an outline for a Wikipedia page about a user-provided topic. Be comprehensive and specific.",
        ),
        ("user", "{topic}"),
    ]
)

class Subsection(BaseModel):
    subsection_title: str = Field(..., title="Title of the subsection")
    description: str = Field(..., title="Content of the subsection")

    @property
    def as_str(self) -> str:
        return f"### {self.subsection_title}\n\n{self.description}".strip()

class Section(BaseModel):
    section_title: str = Field(..., title="Title of the section")
    description: str = Field(..., title="Content of the section")
    subsections: Optional[List[Subsection]] = Field(
        default=None,
        title="Titles and descriptions for each subsection of the Wikipedia page.",
    )

    @property
    def as_str(self) -> str:
        subsections = "\n\n".join(
            f"### {subsection.subsection_title}\n\n{subsection.description}"
            for subsection in self.subsections or []
        )
        return f"## {self.section_title}\n\n{self.description}\n\n{subsections}".strip()

class Outline(BaseModel):
    page_title: str = Field(..., title="Title of the Wikipedia page")
    sections: List[Section] = Field(
        default_factory=list,
        title="Titles and descriptions for each section of the Wikipedia page.",
    )

    @property
    def as_str(self) -> str:
        sections = "\n\n".join(section.as_str for section in self.sections)
        return f"# {self.page_title}\n\n{sections}".strip()

generate_outline_direct = direct_gen_outline_prompt | fast_llm.with_structured_output(Outline)

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[12], [line 55](vscode-notebook-cell:?execution_count=12&line=55)
     [51](vscode-notebook-cell:?execution_count=12&line=51)         sections = "\n\n".join(section.as_str for section in self.sections)
     [52](vscode-notebook-cell:?execution_count=12&line=52)         return f"# {self.page_title}\n\n{sections}".strip()
---> [55](vscode-notebook-cell:?execution_count=12&line=55) generate_outline_direct = direct_gen_outline_prompt | fast_llm.with_structured_output(Outline)

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/base.py:208, in BaseLanguageModel.with_structured_output(self, schema, **kwargs)
    [204](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/base.py:204) def with_structured_output(
    [205](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/base.py:205)     self, schema: Union[Dict, Type[BaseModel]], **kwargs: Any
    [206](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/base.py:206) ) -> Runnable[LanguageModelInput, Union[Dict, BaseModel]]:
    [207](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/base.py:207)     """Implement this if there is a way of steering the model to generate responses that match a given schema."""  # noqa: E501
--> [208](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain_core/language_models/base.py:208)     raise NotImplementedError()

NotImplementedError:

### Description

Trying to run the basic example for STORM

### System Info

pip
Mac
python 3.11

**Comment by hinthornw** [comment]
The current example uses tool calling. If your model does not support tool calling, then you can write an adapter.

I'm probably not going to have time to re-implement STORM to show how to do it without tool/function calling

**Comment by chiefsfumes** [comment]
Hi, thanks for the quick response. 
I'm confused, I did not change the models in the example. Do GPT3.5 and GPT4 not support tool calling?
