### ISSUE TITLE
Use  checkpoints.sqlite raise NotImplementedError

### ISSUE THREAD

**Issue by JemicyChu** [langchain-ai/langgraph#495]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code
graph2.py
```
# workflow is normal code

def get_executor_app_with_checkpoint(interrupt_before=None, interrupt_after=None, debug=False):
    _workflow = copy.deepcopy(workflow)
    memory = SqliteSaver.from_conn_string("checkpoints.sqlite")
    return _workflow.compile(checkpointer=memory, debug=debug,
                             interrupt_before=interrupt_before, interrupt_after=interrupt_after)
```
main.py
```
# normal import functions

if __name__ == '__main__':
    from llms.ExecutorAgent.graph2 import get_executor_app_with_checkpoint
    import asyncio


    async def main():
        state = get_state(SerializableDevice("")) # my code,
        app = get_executor_app_with_checkpoint(interrupt_after=['Advice'],debug=True)
        thread = {"configurable": {"thread_id": "100"}}

        res = await app.ainvoke(state, thread)
        print(res)
        snapshot = app.get_state(thread)
        print(snapshot.next)
        print(snapshot.get_state(thread).values["messages"])

        to_replay = None
        for state in app.get_state_history(thread):
            print("Num Messages: ", len(state.values["messages"]), "Next: ", state.next)
            print("-" * 80)
            if len(state.values["messages"]) == 6:
                # We are somewhat arbitrarily selecting a specific state based on the number of chat messages in the state.
                to_replay = state
        print(to_replay.next)
        print(to_replay.config)
    asyncio.run(main())
```
### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "D:\Users\111543801\PycharmProjects\GuiAutomator\test\__init__.py", line 187, in <module>
    main()
  File "D:\Users\111543801\PycharmProjects\GuiAutomator\test\__init__.py", line 163, in main
    res = asyncio.run(app.ainvoke(state, thread))
  File "D:\Users\111543801\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Users\111543801\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\Users\111543801\PycharmProjects\GuiAutomator\venv\lib\site-packages\langgraph\pregel\__init__.py", line 1301, in ainvoke
    async for chunk in self.astream(
  File "D:\Users\111543801\PycharmProjects\GuiAutomator\venv\lib\site-packages\langgraph\pregel\__init__.py", line 994, in astream
    await self.checkpointer.aget_tuple(config)
  File "D:\Users\111543801\PycharmProjects\GuiAutomator\venv\lib\site-packages\langgraph\checkpoint\base.py", line 184, in aget_tuple
    raise NotImplementedError
NotImplementedError

Process finished with exit code 1

### Description

1.This problem only occurs at the end of my graph run

### System Info

langchain==0.1.5
langchain-community==0.0.17
langchain-core==0.2.0
langgraph==0.0.50

**Comment by hinthornw** [comment]
Use https://langchain-ai.github.io/langgraph/reference/checkpoints/#asyncsqlitesaver for async work.

Sqlite doesn't really natively support async operations
