### ISSUE TITLE
DOC: Request for example that uses create_tool_calling_agent and antropic or ChatBedrock

### ISSUE THREAD

**Issue by codekiln** [langchain-ai/langgraph#525]
### Idea or request for content:

Most of the examples use [create_openai_functions_agent](https://github.com/search?q=repo%3Alangchain-ai%2Flanggraph%20create_openai_functions_agent&type=code), which according to langchain's docs, [is deprecated](https://python.langchain.com/v0.1/docs/modules/agents/agent_types/openai_functions_agent/). 

I couldn't find an any results for searching for [create_tool_calling_agent in this repo yet](https://github.com/search?q=repo%3Alangchain-ai%2Flanggraph%20create_tool_calling_agent&type=code).

Request: adapt one of the docs that uses `create_openai_functions_agent` to instead use the more generic `create_tool_calling_agent`, preferably with some non-OpenAI LLM (for diversity).

**Comment by codekiln** [comment]
@hinthornw indeed, all of the results for `create_openai_functions_agent` are in the `examples` directory. Is there something I should do to recategorize this request? It sounds like the DOC issue prefix is meant to be more explicit to the `docs` subdir?

**Comment by hinthornw** [comment]
Do you have a specific request? We use Anthropic in many places in our docs. We don't use `create_tool_calling_agent` because langgraph is designed to replace most instances where you'd use that.

**Comment by hwchase17** [comment]
the base langgraph examples should all work with LangChain models that support bind_tools, which Anthropic should support: https://langchain-ai.github.io/langgraph/tutorials/introduction/
