### ISSUE TITLE
Can not change the name of the langgraph in langsmith

### ISSUE THREAD

**Issue by Undertone0809** [langchain-ai/langgraph#538]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

Any langgraph case or example is OK. You just need to run any langgraph program and see the effect in langsmith.

### Error Message and Stack Trace (if applicable)

None

### Description

In langgraph langsmith, all the names are langgraph, I can not customize the name.

![image](https://github.com/langchain-ai/langchain/assets/72488598/4d6d6800-21e1-456e-a154-e55aea361f62)

I would like to know, first of all, whether it is feasible to modify the name, and second, if it is feasible, how to modify it? If it doesn't work, we need a solution.

### System Info

```

python -m langchain_core.sys_info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22631
> Python Version:  3.10.14 | packaged by Anaconda, Inc. | (main, Mar 21 2024, 16:20:14) [MSC v.1916 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.2.1
> langchain: 0.2.1
> langchain_community: 0.2.1
> langsmith: 0.1.63
> langchain_openai: 0.1.7
> langchain_text_splitters: 0.2.0
> langchainhub: 0.1.16
> langgraph: 0.0.55

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langserve
```

**Comment by Undertone0809** [comment]
> You can define the name for LangSmith in the line where you compile the graph:
> `app = workflow.compile().with_config({"run_name": "Great Name"})`

Great! But I want to know where the document show this？

**Comment by hinthornw** [comment]
It's in the langsmith docs https://docs.smith.langchain.com/how_to_guides/tracing/trace_with_langchain#customize-run-name

**Comment by hinthornw** [comment]
You can also customize dynamically (my_chain.invoke(..., {"run_name": "foo"}))

**Comment by hinthornw** [comment]
I think this can be closed - feel free to re-open if it's not answered
