### ISSUE TITLE
missing MessageGraph

### ISSUE THREAD

**Issue by rwaneyvin** [langchain-ai/langgraph#56]
Dear Langchain,

I cannot find MessageGraph module when trying to test agent-simulation-evaluation.ipynb,
please help me to install that module, thanks a lot!

Cheers!
Richard

**Comment by hinthornw** [comment]
```
from langgraph.graph import MessageGraph
```
should work in recent versions. What's your langgraph version?

**Comment by rwaneyvin** [comment]
it is langgraph 0.0.15, FYI!
thanks a lot!
