### ISSUE TITLE
DOC: when streaming events, how can we get the final state of StateGraph at the end of execution?

### ISSUE THREAD

**Issue by ldorigo** [langchain-ai/langgraph#563]
### Issue with current documentation:

Originally posted this as a discussion but reposting as issue because there's no docs on it and we're currently blocked by this issue - cannot upgrade langchain without upgrading langgraph, and cannot upgrade langgraph without breaking our app. 

I was previously on version 0.30 and I could get the final graph state for a StateGraph by doing:

```python
async for event in parent_runnable.astream_events(version="v1"):          
      if event["event"] == "on_chain_end" and event["name"] == "langgraph_graph":
            output = event["data"]["output"]
            if not output:
                final_state = output.get("__end__", {})
```

However, now that I updated to the last version, it seems like the final event is triggered by the penultimate node (not the end node) and the final state is no longer available? How can I access the final state when the graph is done executing?

**Comment by nfcampos** [comment]
You can use stream_mode=values to get a stream of state values at the end of each step. The last of these will be the final state.

```
async for event in parent_runnable.astream_events(version="v1", stream_mode="values"):          
    if event["event"] == "on_chain_end" and event["name"] == "langgraph_graph":
        final_state = event["data"]["output"]
```

**Comment by ldorigo** [comment]
That gives me a `TypeError: RunnableSequence._atransform() got an unexpected keyword argument 'stream_mode'`.

**Comment by ldorigo** [comment]
On the other hand, manually setting the attribute after compiling the graph seems to work:

```
compiled=  graph.compile()
compiled.stream_mode = "values"
```

**Comment by nfcampos** [comment]
is `parent_runnable` not the graph, but instead some sequence with more things?
