### ISSUE TITLE
astream_events can't work with checkpointer

### ISSUE THREAD

**Issue by gbaian10** [langchain-ai/langgraph#597]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
import asyncio
import uuid
from typing import Annotated, TypedDict

from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.sqlite import SqliteSaver
from langgraph.graph import StateGraph, add_messages

load_dotenv()


class State(TypedDict):
    messages: Annotated[list, add_messages]


model = ChatOpenAI()


async def call_model(state: State):
    messages = state["messages"]
    response = await model.ainvoke(messages)
    return {"messages": response}


workflow = StateGraph(State)
workflow.add_node("model", call_model)
workflow.set_entry_point("model")
workflow.set_finish_point("model")
memory = SqliteSaver.from_conn_string(":memory:")
app = workflow.compile(checkpointer=memory)


async def main():
    inputs = [("human", "Who are you?")]
    config = {"configurable": {"thread_id": str(uuid.uuid4())}}
    async for event in app.astream_events({"messages": inputs}, config, version="v2"):
        kind = event["event"]
        if kind == "on_chat_model_stream":
            content = event["data"]["chunk"].content
            if content:
                print(content, end="|", flush=True)


if __name__ == "__main__":
    asyncio.run(main())
```

### Error Message and Stack Trace (if applicable)

/home/gbaian10/.cache/pypoetry/virtualenvs/langchain-backend-eZX4qY_I-py3.12/lib/python3.12/site-packages/langchain_core/_api/beta_decorator.py:87: LangChainBetaWarning: This API is in beta and may change in the future.
  warn_beta(
Traceback (most recent call last):
  File "/home/gbaian10/online_code/langchain-backend/playground/temp.py", line 46, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/gbaian10/online_code/langchain-backend/playground/temp.py", line 37, in main
    async for event in app.astream_events({"messages": inputs}, config, version="v2"):
  File "/home/gbaian10/.cache/pypoetry/virtualenvs/langchain-backend-eZX4qY_I-py3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 1137, in astream_events
    async for event in event_stream:
  File "/home/gbaian10/.cache/pypoetry/virtualenvs/langchain-backend-eZX4qY_I-py3.12/lib/python3.12/site-packages/langchain_core/tracers/event_stream.py", line 860, in _astream_events_implementation_v2
    await task
  File "/home/gbaian10/.cache/pypoetry/virtualenvs/langchain-backend-eZX4qY_I-py3.12/lib/python3.12/site-packages/langchain_core/tracers/event_stream.py", line 820, in consume_astream
    async for _ in event_streamer.tap_output_aiter(
  File "/home/gbaian10/.cache/pypoetry/virtualenvs/langchain-backend-eZX4qY_I-py3.12/lib/python3.12/site-packages/langchain_core/tracers/event_stream.py", line 125, in tap_output_aiter
    first = await py_anext(output, default=sentinel)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbaian10/.cache/pypoetry/virtualenvs/langchain-backend-eZX4qY_I-py3.12/lib/python3.12/site-packages/langchain_core/utils/aiter.py", line 62, in anext_impl
    return await __anext__(iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbaian10/.cache/pypoetry/virtualenvs/langchain-backend-eZX4qY_I-py3.12/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 1084, in astream
    await self.checkpointer.aget_tuple(config)
  File "/home/gbaian10/.cache/pypoetry/virtualenvs/langchain-backend-eZX4qY_I-py3.12/lib/python3.12/site-packages/langgraph/checkpoint/base.py", line 191, in aget_tuple
    raise NotImplementedError
NotImplementedError

### Description

astream_events can't work with checkpointer.

But if checkpointer is not used, it will be normal.

### System Info

langchain==0.2.2
langgraph==0.0.62
langchain-core==0.2.4

langchain-openai==0.1.8

platfor== linux
python-version==3.12.3

**Comment by hinthornw** [comment]
HI @gbaian10 - thanks for your raising! Could you use the [AsyncSqliteSaver](https://langchain-ai.github.io/langgraph/reference/checkpoints/#asyncsqlitesaver) when using async methods? The Sqlite one specifically support async checkpointing ([doc note](https://langchain-ai.github.io/langgraph/reference/checkpoints/#langgraph.checkpoint.aiosqlite.AsyncSqliteSaver.aput)) - I'll improve the error messaging to point to the docs so this is more clear moving forward.

Thanks!

**Comment by gbaian10** [comment]
Thank you for your reply.

It can work after replacing `SqliteSaver` with the following content. I didn't notice the class of AsyncSqliteSaver. Sorry.

```shell
pip install aiosqlite
```

```python
from langgraph.checkpoint.aiosqlite import AsyncSqliteSaver

memory = AsyncSqliteSaver.from_conn_string(":memory:")
```

**Comment by robocanic** [comment]
Hi @hinthornw , I found that the `PostgresSaver` hasn't implemented the `aget_tuple`, which can also cause similar problems when using astream_events.

**Comment by vbarda** [comment]
@robocanic you can use `AsyncPostgresSaver` (`from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver`). Hope this helps!

**Comment by robocanic** [comment]
> @robocanic you can use `AsyncPostgresSaver` (`from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver`). Hope this helps!

@vbarda It works! Thanks a lot! But I still came across some issues in my project. I' m building a large app using langchain and langgraph. I planned to do some experiments and comparisons on different comonent implementions , including checkpointer. And the initialization of different implemention is completed by a factory,  just like below:
```python
class CheckpointerFactory:

    @classmethod
    def create_checkpointer(cls, checkpointer_type: str, url: str, db_name: str, collection_name: str, use_async: Optional[bool]) -> BaseCheckpointSaver:
        subclasses = cls.__subclasses__()
        for subclass in subclasses:
            if subclass._support(checkpointer_type=checkpointer_type):
                return subclass._create_checkpointer(url=url, db_name=db_name, collection_name=collection_name, use_async=use_async)
        raise NotImplementedError(f"unsupported checkpointer type: {checkpointer_type}")

    @classmethod
    @abstractmethod
    def _support(cls, checkpointer_type: str ) -> bool:


    @classmethod
    @abstractmethod
    def _create_checkpointer(cls, url: str, db_name: str, collection_name: str, use_async: Optional[bool] = False) -> BaseCheckpointSaver:
```
This pattern works fine with other components. But there're some differences between checkpointers. For instance, the initialization of mongo is like below:
```python
def _create_checkpointer(cls, url: str, db_name: str, collection_name: str, use_async: Optional[bool] = False):
    ...
    checkpointer = MongoDBSaver(
        AsyncIOMotorClient(url),  db_name, collection_name
    )
    return checkpointer
```
but the intialization of postgres is like below, I need to manage the connection on my own:
```python
async with await AsyncConnection.connect(DB_URI, **connection_kwargs) as conn:
    checkpointer = AsyncPostgresSaver(conn)
   ...
```
Becuase of the `with` block, I can't return the checkpointer as simply as  mongo do. Is there any solutions ? 
Thanks!

**Comment by ada-k** [comment]
> > [@robocanic](https://github.com/robocanic) you can use `AsyncPostgresSaver` (`from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver`). Hope this helps!
> 
> [@vbarda](https://github.com/vbarda) It works! Thanks a lot! But I still came across some issues in my project. I' m building a large app using langchain and langgraph. I planned to do some experiments and comparisons on different comonent implementions , including checkpointer. And the initialization of different implemention is completed by a factory, just like below:
> 
> class CheckpointerFactory:
> 
>     @classmethod
>     def create_checkpointer(cls, checkpointer_type: str, url: str, db_name: str, collection_name: str, use_async: Optional[bool]) -> BaseCheckpointSaver:
>         subclasses = cls.__subclasses__()
>         for subclass in subclasses:
>             if subclass._support(checkpointer_type=checkpointer_type):
>                 return subclass._create_checkpointer(url=url, db_name=db_name, collection_name=collection_name, use_async=use_async)
>         raise NotImplementedError(f"unsupported checkpointer type: {checkpointer_type}")
> 
>     @classmethod
>     @abstractmethod
>     def _support(cls, checkpointer_type: str ) -> bool:
> 
> 
>     @classmethod
>     @abstractmethod
>     def _create_checkpointer(cls, url: str, db_name: str, collection_name: str, use_async: Optional[bool] = False) -> BaseCheckpointSaver:
> This pattern works fine with other components. But there're some differences between checkpointers. For instance, the initialization of mongo is like below:
> 
> def _create_checkpointer(cls, url: str, db_name: str, collection_name: str, use_async: Optional[bool] = False):
>     ...
>     checkpointer = MongoDBSaver(
>         AsyncIOMotorClient(url),  db_name, collection_name
>     )
>     return checkpointer
> but for postgres, I need to manage the connection on my own:
> 
> def _create_checkpointer(cls, url: str, db_name: str, collection_name: str, use_async: Optional[bool] = False):
>     ...
>     async with await AsyncConnection.connect(url, **connection_kwargs) as conn:
>         checkpointer = AsyncPostgresSaver(conn)
>        ...
> Becuase of the `with` block, I can't return the checkpointer as directly as mongo do. Is there any solutions ? Thanks!

Did you ever find a work around for the postgres connection?

**Comment by ada-k** [comment]
> When I try to run after defining the connection like said above, i get the following error:
> 
> AttributeError: 'coroutine' object has no attribute 'get_next_version'

This worked for me

```python
global CHECKPOINTER_CTX, checkpointer
CHECKPOINTER_CTX = AsyncPostgresSaver.from_conn_string(DB_URI)
checkpointer = await CHECKPOINTER_CTX.__aenter__()
```
