### ISSUE TITLE
DOC: force-calling-a-tool-first.ipynb tool_calls invalid_request_error

### ISSUE THREAD

**Issue by Daggle24** [langchain-ai/langgraph#606]
### Issue with current documentation:

When I try to execute the code in the documentation (I'm not modifying nothing at all) I get the following error:
 Error code: 400 - {'error': {'message': "Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'.", 'type': 'invalid_request_error', 'param': 'messages.[2].role', 'code': None}}
 
 [https://github.com/langchain-ai/langgraph/blob/main/examples/force-calling-a-tool-first.ipynb](url)

**Comment by hwchase17** [comment]
hm i just ran it fine. are you able to provide a full stack trace?

**Comment by Daggle24** [comment]
Sorry, I just had to --upgrade my langchain_openai package..  😐

I close the issue.
