### ISSUE TITLE
how to config recurrsion limit 

### ISSUE THREAD

**Issue by roboticsocialism** [langchain-ai/langgraph#64]
Dear Langgraph,

I encounted this when test chatbot-simulation-evaluation in example.
langgraph.pregel.GraphRecursionError: Recursion limit of 25 reachedwithout hitting a stop condition. You can increase the limitby setting the `recursion_limit` config key

Would you please advise how to config the limit?
Thanks a lot!

Cheers!

**Comment by n11west11** [comment]
The [agent supervisor](https://github.com/langchain-ai/langgraph/blob/18b4bdbf3801948b780a378ea6ec84ae7cfc5aef/examples/multi_agent/agent_supervisor.ipynb#L377) has an example, essentially when you invoke a graph, the second argument is a config dict where you can pass this in.

**Comment by roboticsocialism** [comment]
> The [agent supervisor](https://github.com/langchain-ai/langgraph/blob/18b4bdbf3801948b780a378ea6ec84ae7cfc5aef/examples/multi_agent/agent_supervisor.ipynb#L377) has an example, essentially when you invoke a graph, the second argument is a config dict where you can pass this in.
> 
> ```
> for s in graph.stream(
>     {
>         "messages": [
>             HumanMessage(content="Write a brief research report on pikas.")
>         ]
>     },
>     {"recursion_limit": 100},
> ):
>     if "__end__" not in s:
>         print(s)
>         print("----")
> ```

Thanks a lot, but I got this message when doing it!
TypeError: Got unknown type {'recursion_limit': 100}
probably not support for  MessageGraph

**Comment by hinthornw** [comment]
Are you making sure the "recursion_limit" field is being passed in the `config` arg rather than the primary `input` arg?

**Comment by roboticsocialism** [comment]
> Are you making sure the "recursion_limit" field is being passed in the `config` arg rather than the primary `input` arg?

Yes, then it works, thanks a lot mate, the {"recursion_limit": 100} should be placed at the second argument,
by the way, may I ask one more question, what if unlimit, I tried {"recursion_limit": -1} that didn't work.

**Comment by mail2mhossain** [comment]
langgraph.pregel.GraphRecursionError: Recursion limit of 25 reachedwithout hitting a stop condition. You can increase the limitby setting the `recursion_limit` config key.

How I should set stop condition if recursion failed.

**Comment by hinthornw** [comment]
@roboticsocialism can do something liek `sys.maxsize` for a big. number

**Comment by hinthornw** [comment]
@mail2mhossain could you elaborate? You can track the number of steps in the state and stop preemptively, if that's your question

**Comment by hinthornw** [comment]
close since this is solved
