### ISSUE TITLE
DOC: Grammar and punctuation improvements in LangGraph introduction tutorial

### ISSUE THREAD

**Issue by ruankie** [langchain-ai/langgraph#679]
## Overview

I've recently read through the [LangGraph introduction tutorial](https://langchain-ai.github.io/langgraph/tutorials/introduction/) and noticed a few minor grammar and punctuation errors. Fixing these will make the docs easier to understand and reduce the chances of misinterpretation.

## Errors

- Incorrect closure of back ticks to delineate objects in Markdown ([section 2](https://langchain-ai.github.io/langgraph/tutorials/introduction/#part-2-enhancing-the-chatbot-with-tools))
- Unnecessary double new-line in docstring of `route_tools` function ([section 2](https://langchain-ai.github.io/langgraph/tutorials/introduction/#part-2-enhancing-the-chatbot-with-tools))
- Typo when describing checkpointer memory ([section 3](https://langchain-ai.github.io/langgraph/tutorials/introduction/#part-3-adding-memory-to-the-chatbot))
- Grammar error: using "arbitrary" instead of "arbitrarily" when describing checkpointing ([section 3](https://langchain-ai.github.io/langgraph/tutorials/introduction/#part-3-adding-memory-to-the-chatbot))
- Using "is" instead of "are" to describe plural ([section 3](https://langchain-ai.github.io/langgraph/tutorials/introduction/#part-3-adding-memory-to-the-chatbot))
- Incomplete wrapping of words in double underscore for Markdown formatting ([section 7](https://langchain-ai.github.io/langgraph/tutorials/introduction/#part-7-time-travel))

**Comment by hinthornw** [comment]
Thank you for the PR :)
