### ISSUE TITLE
Async runnables

### ISSUE THREAD

**Issue by tgram-3D** [langchain-ai/langgraph#7]
Quick question: the default langchain.runnables class supports async, but when I try to use async functions in chains with PubSub I get an error traced back to the transform_stream_with_config method: 

TypeError: Cannot invoke a coroutine function synchronously.Use `ainvoke` instead.

I admittedly have not dug into the permchain or runnables code very deep to see what's actually going on, nor would I probably understand it anyway, but I'm curious if there's any way around this issue.

**Comment by nfcampos** [comment]
Hi, this will be addressed in the next version

**Comment by nfcampos** [comment]
We now support async
