### ISSUE TITLE
langgraph up not working on windows because of os.killpg

### ISSUE THREAD

**Issue by Freezaa9** [langchain-ai/langgraph#712]
### **Example Code**
langgraph up

### **Error Message and Stack Trace (if applicable)**
File "C:\Users\geoff\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\geoff\OneDrive\Documents\GitHub\pcd-data-eu-genai-poko-orch\.venv\Lib\site-packages\langgraph_cli\exec.py", line 103, in subp_exec
    os.killpg(os.getpgid(proc.pid), signal.SIGINT)
    ^^^^^^^^^
AttributeError: module 'os' has no attribute 'killpg'. Did you mean: 'kill'?
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001C170BA19E0>

### **Description**
Hi all,

While running langgraph up on windows i get the os.killpg error due to non support by windows.:
https://github.com/langchain-ai/langgraph/blob/19ff4a142f40d1be8ac55409c249f95a82583148/libs/cli/langgraph_cli/exec.py#L103

I know it's a pain to support windows :)
Thanks for your help

### **System Info**
Platform windows:
langgraph==0.0.69
langgraph-cli==0.1.39

**Comment by vbarda** [comment]
@Freezaa9 should be fixed with the latest release 0.1.40. please let us know if you run into any other issues.

**Comment by Freezaa9** [comment]
Working like a charm ! Thanks
