### ISSUE TITLE
langgraph tool calls not working

### ISSUE THREAD

**Issue by lastrei** [langchain-ai/langgraph#720]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
from typing import Literal
from langgraph.prebuilt import create_react_agent
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI


@tool
def get_weather(city: Literal["nyc", "sf"]):
    """Use this to get weather information."""
    if city == "nyc":
        return "It might be cloudy in nyc"
    elif city == "sf":
        return "It's always sunny in sf"
    else:
        raise AssertionError("Unknown city")


tools = [get_weather]

model = ChatOpenAI(model="gpt-4-turbo", temperature=0, base_url="https://xxxx.xxx/v1/",
                   api_key="sk-xxxxx")


def print_stream(stream):
    for s in stream:
        message = s["messages"][-1]
        if isinstance(message, tuple):
            print(message)
        else:
            message.pretty_print()


graph = create_react_agent(model, tools=tools, debug=True)
inputs = {"messages": [("user", "what is the weather in sf?")]}
print_stream(graph.stream(inputs, stream_mode="values"))
```

### Error Message and Stack Trace (if applicable)

```shell
[0:tasks] Starting step 0 with 1 task:
- __start__ -> {'messages': [('user', 'what is the weather in sf?')]}
[0:writes] Finished step 0 with writes to 1 channel:
- messages -> [('user', 'what is the weather in sf?')]
================================ Human Message =================================

what is the weather in sf?
[1:tasks] Starting step 1 with 1 task:
- agent -> {'is_last_step': False,
 'messages': [HumanMessage(content='what is the weather in sf?', id='9c5bb8bd-cef8-454f-93f1-69877b6916c3')]}
[1:writes] Finished step 1 with writes to 1 channel:
- messages -> [AIMessage(content='\n> search("current weather in San Francisco")Currently, in San Francisco, the weather is sunny with a temperature around 70°F. The wind is coming from the west, with speeds ranging from 13 to 18 mph and gusts reaching up to 28 mph. Tonight, the sky will remain mostly clear, with temperatures dropping to a low around 54°F. The winds will continue from the west, with speeds between 8 to 18 mph and gusts as high as 30 mph .', response_metadata={'token_usage': {'completion_tokens': 103, 'prompt_tokens': 14, 'total_tokens': 117}, 'model_name': 'gpt-4-turbo', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None}, id='run-d5f92165-9e4e-4b79-a8a5-31bc1cce3afa-0', usage_metadata={'input_tokens': 14, 'output_tokens': 103, 'total_tokens': 117})]
================================== Ai Message ==================================


> search("current weather in San Francisco")Currently, in San Francisco, the weather is sunny with a temperature around 70°F. The wind is coming from the west, with speeds ranging from 13 to 18 mph and gusts reaching up to 28 mph. Tonight, the sky will remain mostly clear, with temperatures dropping to a low around 54°F. The winds will continue from the west, with speeds between 8 to 18 mph and gusts as high as 30 mph .
```

### Description

i'm trying to create react agent as documents:https://langchain-ai.github.io/langgraph/how-tos/create-react-agent/
but it's still answer from llm not the tools.

### System Info

> OS:  Windows
> OS Version:  10.0.22000
> Python Version:  3.11.8 | packaged by Anaconda, Inc. | (main, Feb 26 2024, 21:34:05) [MSC v.1916 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.2.9
> langchain: 0.2.1
> langchain_community: 0.0.19
> langsmith: 0.1.81
> langchain_experimental: 0.0.47
> langchain_openai: 0.1.8
> langchain_text_splitters: 0.2.0
> langgraph: 0.0.69

**Comment by hwchase17** [comment]
hm I just ran this and it called the tool...

do you have LangSmith trace you can share?

**Comment by vbarda** [comment]
can also confirm that it's running for me, across 4o, 4-turbo and 3.5. maybe something wrong w/ the `base_url` you're passing to `ChatOpenAI`?

**Comment by lastrei** [comment]
I want to know if the version we are using is consistent. This issue has occurred more than once, especially after I updated the package.

**Comment by lastrei** [comment]
> can also confirm that it's running for me, across 4o, 4-turbo and 3.5. maybe something wrong w/ the `base_url` you're passing to `ChatOpenAI`?

i use proxy to access openai-api,it's fine,nothing wrong with it.
```
when use gpt-4o

[0:tasks] Starting step 0 with 1 task:
- __start__ -> {'messages': [('user', 'what is the weather in sf?')]}
[0:writes] Finished step 0 with writes to 1 channel:
- messages -> [('user', 'what is the weather in sf?')]
================================ Human Message =================================

what is the weather in sf?
[1:tasks] Starting step 1 with 1 task:
- agent -> {'is_last_step': False,
 'messages': [HumanMessage(content='what is the weather in sf?', id='e377b94e-0f1e-4820-849a-d80671c0238b')]}
[1:writes] Finished step 1 with writes to 1 channel:
- messages -> [AIMessage(content='\n> search("current weather in San Francisco")\n> mclick(["0", "1", "7"])\n> **end-searching**\n\nThe current weather in San Francisco is partly cloudy with a temperature of around 54°F (12°C). Humidity is at 84%, and there is a gentle west-southwest wind at 5 to 9 mph. Tonight, the weather will remain mostly cloudy with a low of approximately 52°F (11°C) and similar wind conditions.\n\nLooking ahead to tomorrow, you can expect the skies to clear gradually, with temperatures rising to a high of about 71°F (22°C). Winds will continue from the southwest, becoming a bit stronger in the afternoon. Tomorrow night, it will be partly cloudy again, with lows around 54°F (12°C)[National Weather Service](https://forecast.weather.gov/zipcity.php?inputstring=San+Francisco,CA)[San Francisco, CA Weather Conditions | Weather Underground](https://www.wunderground.com/weather/us/ca/san-francisco)[Hourly forecast for San Francisco, California, USA](https://www.timeanddate.com/weather/usa/san-francisco/hourly).', response_metadata={'token_usage': {'completion_tokens': 243, 'prompt_tokens': 14, 'total_tokens': 257}, 'model_name': 'gpt-4o-all', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None}, id='run-74f7fc3a-dc82-4f09-98b1-95fab38ee218-0', usage_metadata={'input_tokens': 14, 'output_tokens': 243, 'total_tokens': 257})]
================================== Ai Message ==================================

```




```
gpt-3.5-turbo

[0:tasks] Starting step 0 with 1 task:
- __start__ -> {'messages': [('user', 'what is the weather in sf?')]}
[0:writes] Finished step 0 with writes to 1 channel:
- messages -> [('user', 'what is the weather in sf?')]
================================ Human Message =================================

what is the weather in sf?
[1:tasks] Starting step 1 with 1 task:
- agent -> {'is_last_step': False,
 'messages': [HumanMessage(content='what is the weather in sf?', id='d491d016-c669-44cf-830b-b3ff111c0c54')]}
[1:writes] Finished step 1 with writes to 1 channel:
- messages -> [AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'call_2bV5C2KunE2fqCudB99rpeHX', 'function': {'arguments': 'from requests import get\n\ndef get_weather(city):\n    url = f"https://wttr.in/{city}?format=%C\\n%t"\n    response = get(url)\n    return response.text.strip()\n\nget_weather("sf")', 'name': 'python'}, 'type': 'function'}]}, response_metadata={'token_usage': {'completion_tokens': 50, 'prompt_tokens': 61, 'total_tokens': 111}, 'model_name': 'gpt-3.5-turbo', 'system_fingerprint': None, 'finish_reason': 'tool_calls', 'logprobs': None}, id='run-c9750522-ea8a-4fec-8008-acb7d77cbfd7-0', invalid_tool_calls=[{'name': 'python', 'args': 'from requests import get\n\ndef get_weather(city):\n    url = f"https://wttr.in/{city}?format=%C\\n%t"\n    response = get(url)\n    return response.text.strip()\n\nget_weather("sf")', 'id': 'call_2bV5C2KunE2fqCudB99rpeHX', 'error': 'Function python arguments:\n\nfrom requests import get\n\ndef get_weather(city):\n    url = f"https://wttr.in/{city}?format=%C\\n%t"\n    response = get(url)\n    return response.text.strip()\n\nget_weather("sf")\n\nare not valid JSON. Received JSONDecodeError Expecting value: line 1 column 1 (char 0)'}], usage_metadata={'input_tokens': 61, 'output_tokens': 50, 'total_tokens': 111})]
================================== Ai Message ==================================
Invalid Tool Calls:
  python (call_2bV5C2KunE2fqCudB99rpeHX)
 Call ID: call_2bV5C2KunE2fqCudB99rpeHX
  Error: Function python arguments:

from requests import get

def get_weather(city):
    url = f"https://wttr.in/{city}?format=%C\n%t"
    response = get(url)
    return response.text.strip()

get_weather("sf")

are not valid JSON. Received JSONDecodeError Expecting value: line 1 column 1 (char 0)
  Args:
    from requests import get

def get_weather(city):
    url = f"https://wttr.in/{city}?format=%C\n%t"
    response = get(url)
    return response.text.strip()

get_weather("sf")
```

**Comment by vbarda** [comment]
@lastrei in the above snippet are you using your own `get_weather` function?

```
def get_weather(city):
    url = f"https://wttr.in/{city}?format=%C\n%t"
    response = get(url)
    return response.text.strip()
```

if so, you need to also add a `@tool` decorator to turn it into a tool that we can pass to the LLM

**Comment by lastrei** [comment]
> @lastrei in the above snippet are you using your own `get_weather` function?
> 
> ```
> def get_weather(city):
>     url = f"https://wttr.in/{city}?format=%C\n%t"
>     response = get(url)
>     return response.text.strip()
> ```
> 
> if so, you need to also add a `@tool` decorator to turn it into a tool that we can pass to the LLM

no , its openai api generate context , not real function in my code.

**Comment by vbarda** [comment]
> > @lastrei in the above snippet are you using your own `get_weather` function?
> > ```
> > def get_weather(city):
> >     url = f"https://wttr.in/{city}?format=%C\n%t"
> >     response = get(url)
> >     return response.text.strip()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > if so, you need to also add a `@tool` decorator to turn it into a tool that we can pass to the LLM
> 
> no , its openai api generate context , not real function in my code.

got it. could you please check if you still run into this issue if you use

(1) non-proxied openai `base_url`?
(2) non-openai tool calling model (let's say `ChatAnthropic`)

also, if you can generate a langsmith trace that would also be very helpful!

the issue is most likely with the tool calling model that's being used

**Comment by lastrei** [comment]
> > > @lastrei in the above snippet are you using your own `get_weather` function?
> > > ```
> > > def get_weather(city):
> > >     url = f"https://wttr.in/{city}?format=%C\n%t"
> > >     response = get(url)
> > >     return response.text.strip()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > if so, you need to also add a `@tool` decorator to turn it into a tool that we can pass to the LLM
> > 
> > 
> > no , its openai api generate context , not real function in my code.
> 
> got it. could you please check if you still run into this issue if you use
> 
> (1) non-proxied openai `base_url`? (2) non-openai tool calling model (let's say `ChatAnthropic`)
> 
> also, if you can generate a langsmith trace that would also be very helpful!
> 
> the issue is most likely with the tool calling model that's being used
[langsmith_trace.json](https://github.com/user-attachments/files/16029823/langsmith_trace.json)

here is the trace,thanks .

**Comment by ladycui** [comment]
hi @vbarda, I'm running the demo code in README with a proxy `base_url`. while, sometimes gpt-3.5 doesn't recognize tools but gpt-4o always works fine. 
Question: is it the proxy that leads to the issue?
just in case that you wanna check more info, here are two links of langsmith for gpt-3.5(failed) and gpt-4o(successful):
https://smith.langchain.com/public/0432c180-2148-4abb-8cb5-3d3ed4294a0d/r
https://smith.langchain.com/public/cc663f7a-813f-48b8-8f41-36df1fe727d9/r

Thanks a lot.

**Comment by vbarda** [comment]
@ladycui I don't think it's necessarily due to proxy, i think it's just model capabilities -- 4o is just much better at tool calling than 3.5

**Comment by vbarda** [comment]
> > > > @lastrei in the above snippet are you using your own `get_weather` function?
> > > > ```
> > > > def get_weather(city):
> > > >     url = f"https://wttr.in/{city}?format=%C\n%t"
> > > >     response = get(url)
> > > >     return response.text.strip()
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > if so, you need to also add a `@tool` decorator to turn it into a tool that we can pass to the LLM
> > > 
> > > 
> > > no , its openai api generate context , not real function in my code.
> > 
> > 
> > got it. could you please check if you still run into this issue if you use
> > (1) non-proxied openai `base_url`? (2) non-openai tool calling model (let's say `ChatAnthropic`)
> > also, if you can generate a langsmith trace that would also be very helpful!
> > the issue is most likely with the tool calling model that's being used
> > [langsmith_trace.json](https://github.com/user-attachments/files/16029823/langsmith_trace.json)
> 
> here is the trace,thanks .

@lastrei could you please send that trace as a public URL instead?

**Comment by lastrei** [comment]
> > > > > @lastrei in the above snippet are you using your own `get_weather` function?
> > > > > ```
> > > > > def get_weather(city):
> > > > >     url = f"https://wttr.in/{city}?format=%C\n%t"
> > > > >     response = get(url)
> > > > >     return response.text.strip()
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > if so, you need to also add a `@tool` decorator to turn it into a tool that we can pass to the LLM
> > > > 
> > > > 
> > > > no , its openai api generate context , not real function in my code.
> > > 
> > > 
> > > got it. could you please check if you still run into this issue if you use
> > > (1) non-proxied openai `base_url`? (2) non-openai tool calling model (let's say `ChatAnthropic`)
> > > also, if you can generate a langsmith trace that would also be very helpful!
> > > the issue is most likely with the tool calling model that's being used
> > > [langsmith_trace.json](https://github.com/user-attachments/files/16029823/langsmith_trace.json)
> > 
> > 
> > here is the trace,thanks .
> 
> @lastrei could you please send that trace as a public URL instead?

https://smith.langchain.com/public/4eb851de-8dd3-4477-95a7-a0aaa960f1e7/r

thanks

**Comment by vbarda** [comment]
@lastrei thanks for sharing the trace. based on the trace, the issue is clearly with the specific LLM you're using - it's hallucinating a tool called `python` and trying to call that instead of `get_weather`. you can try to isolate the tool calling issues by doing the following:

```python
model_with_tools = model.bind_tools([get_weather])
model_with_tools.invoke("what is the weather in sf")
```

you can experiment with different models and see which ones are consistent w/ tool calling. In our experience smarter models like `gpt-4o` and `claude 3.5 sonnet` are significantly better and more consistent at tool calling, so I'd recommend using  those

since the issue is not related to langgraph, I am going to close it

**Comment by joshanjohn** [comment]
I also face similar issues, and notice in one of the model which I was working on (llama), with prompt it is working, like it is calling the tool. However, I tried using the granite models, but the tool is not calling. I was wondering why it is happening?
