### ISSUE TITLE
Tentative Plan for for langgraph Checkpointer Support ?

### ISSUE THREAD

**Issue by sushantMoon** [langchain-ai/langgraph#741]
Will langgraph checkpointer be supported in future release, is there any roadmap? 

Since there is lack of persistent database support in langgraph checkpointer this was my langchain-postgres==0.0.5 go to method for that (please let me know if there are better ways). 

Apologies, since I am new I am not sure how I can help but will be happy to pitch in wherever I can.

**Comment by vbarda** [comment]
hi all -- we just added an example Postgres checkpointer implementation here https://langchain-ai.github.io/langgraph/how-tos/persistence_postgres/. please let me know if you have any questions!

**Comment by vbarda** [comment]
@shermify we do actually recommend implementing your own checkpointer. so in your case, you can make a redis checkpointer that conforms to the [`BaseCheckpointSaver`](https://github.com/langchain-ai/langgraph/blob/main/libs/langgraph/langgraph/checkpoint/base.py#L141) interface, you don't need to switch to SQL. please see the above example for Postgres. let me know if you have any questions!

**Comment by gbaian10** [comment]
> hi all -- we just added an example Postgres checkpointer implementation here https://langchain-ai.github.io/langgraph/how-tos/persistence_postgres/. please let me know if you have any questions!

Would you consider integrating it into some package?

**Comment by DhavalThkkar** [comment]
@vbarda I have created a RedisSaver. What is the way to contribute? I asked @hwchase17 but no response

Here is the discussion [link](https://github.com/langchain-ai/langgraph/discussions/848)

**Comment by shermify** [comment]
Awesome! It would be nice if this was integrated into the core package. 

It's not that we're lazy or don't know how. The problem we tend to run into is in maintaining deeply-coupled code that inherits langchain classes and types. It locks you into a version and doesn't really scale. The more code you have, the more difficult it becomes to upgrade and maintain. Just my 2 cents.

**Comment by vbarda** [comment]
@shermify for now we do not plan to integrate these into the core package, will let you know if that changes in the future

**Comment by vbarda** [comment]
@DhavalThkkar thank you! feel free to add a documentation notebook / page similar to the one here https://github.com/langchain-ai/langgraph/blob/main/examples/persistence_postgres.ipynb

**Comment by DhavalThkkar** [comment]
> @DhavalThkkar thank you! feel free to add a documentation notebook / page similar to the one here https://github.com/langchain-ai/langgraph/blob/main/examples/persistence_postgres.ipynb

Added the PR here #961
