### ISSUE TITLE
AsyncSqliteSaver hangs when using astream_event

### ISSUE THREAD

**Issue by ewianda** [langchain-ai/langgraph#789]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
import asyncio
from pprint import pprint

from langgraph.checkpoint.aiosqlite import AsyncSqliteSaver
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import StateGraph

builder = StateGraph(int)
builder.add_node("add_one", lambda x: x + 1)
builder.set_entry_point("add_one")
builder.set_finish_point("add_one")


async def memory():
    memory = MemorySaver()
    graph = builder.compile(checkpointer=memory)
    config = {"configurable": {"thread_id": "thread-1"}}
    async for event in graph.astream_events(10, config, version="v1"):
        pprint(event)


async def asyncSqlite():
    memory = AsyncSqliteSaver.from_conn_string(":memory:")
    graph = builder.compile(checkpointer=memory)
    config = {"configurable": {"thread_id": "thread-1"}}
    async for event in graph.astream_events(10, config, version="v1"):
        pprint(event)


if __name__ == "__main__":
    asyncio.run(memory())  # <--- Works
    asyncio.run(asyncSqlite())  # <--- Hangs here
```

### Error Message and Stack Trace (if applicable)

```shell
Exception ignored in: <module 'threading' from 'lib/python3.11/threading.py'>
Traceback (most recent call last):
  File " lib/python3.11/threading.py", line 1590, in _shutdown
    lock.acquire()
KeyboardInterrupt:
```

### Description

I am trying to add langraph with astream_events to fastapi and it hangs after the first request is complete. i was a able to isolate the issue using a cli tool

### System Info

langchain==0.1.20
langchain-community==0.0.38
langchain-core==0.1.52
langchain-openai==0.1.6
langchain-text-splitters==0.0.1
openinference-instrumentation-langchain==0.1.14

**Comment by gbaian10** [comment]
I have a same problem.
It has actually finished executing your `asyncSqlite()`.
You can try to print something below and it will print it out.

```python
if __name__ == "__main__":
    asyncio.run(memory())  # <--- Works
    asyncio.run(asyncSqlite())  # <--- Hangs here
    print("hi")  # it will print
```

As for why the program cannot be terminated, I am not sure, but I think it may be waiting for aiosqlite to close the connection, because when I close the connection, it can terminate normally.


```python
async def asyncSqlite():
    memory = AsyncSqliteSaver.from_conn_string(":memory:")
    graph = builder.compile(checkpointer=memory)
    config = {"configurable": {"thread_id": "thread-1"}}
    async for event in graph.astream_events(10, config, version="v1"):
        pprint(event)
    await memory.conn.close()  # <--- add this
```

**Comment by ewianda** [comment]
Oh nice. That is a good enough workaround

**Comment by vbarda** [comment]
Yes, you can manually close the connection, or just use connection manager the following way:

```python
import aiosqlite

async def asyncSqlite():
    async with aiosqlite.connect(":memory:") as conn:
        memory = AsyncSqliteSaver(conn)   # <-- note that here we're passing connection instead of a string
        graph = builder.compile(checkpointer=memory)
        config = {"configurable": {"thread_id": "thread-1"}}
        async for event in graph.astream_events(10, config, version="v1"):
            pprint(event)
```

**Comment by hinthornw** [comment]
Or can use the AsyncSqliteSaver as a context manager directly! It'll close the connection at the end of the block:

```python
async with AsyncSqliteSaver.from_conn_string(":memory:") as saver:
    graph = builder.compile(checkpointer=saver)
    graph = builder.compile(checkpointer=memory)
        config = {"configurable": {"thread_id": "thread-1"}}
        async for event in graph.astream_events(10, config, version="v1"):
            pprint(event)
```

**Comment by PE51K** [comment]
Hello! Is there a way to not compile graph for every request? Any workarounds?

I've read about @asynccontextmanager [here](https://github.com/langchain-ai/langgraph/discussions/1211), but this method works only for FastApi apps, but there is many other application of LangGraph like tg bots and so on.
