### ISSUE TITLE
Final node doesn't wait for all other incoming nodes

### ISSUE THREAD

**Issue by mrbuslov** [langchain-ai/langgraph#954]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
import asyncio
from typing import Annotated

from typing_extensions import TypedDict

from langgraph.graph.message import add_messages
from langgraph.graph import END, StateGraph, START

class State(TypedDict):
    messages: Annotated[list, add_messages]


async def call_node(state: State):
    print("call_node")
    return state

async def call_node_2(state: State):
    print("call_node 2 start")
    await asyncio.sleep(5)
    print("call_node 2 finish")
    return state

async def call_node_2_2(state: State):
    print("call_node 2_2 start")
    await asyncio.sleep(3)
    print("call_node 2_2 finish")
    return state

# Define a new graph
workflow = StateGraph(State)

# Define the two nodes we will cycle between
workflow.add_node("agent", lambda x: print('agent'))
workflow.add_node("agent_2", call_node_2)
workflow.add_node("agent_2_1", lambda x: print('agent_2_1'))
workflow.add_node("agent_2_2", call_node_2_2)
workflow.add_node("agent_2_3", lambda x: print('agent_2_3'))
workflow.add_node("agent_3", lambda x: print('agent_3'))
workflow.add_node("agent_4", lambda x: print('agent_4'))

# Set the entrypoint as `agent`
# This means that this node is the first one called
workflow.add_edge(START, "agent")

# We now add a conditional edge
workflow.add_conditional_edges(
    "agent",
    lambda x: ["agent_2", "agent_3"],
    {
        "agent_2": "agent_2",
        "agent_3": "agent_3",
    },
)

# We now add a conditional edge
workflow.add_conditional_edges(
    "agent_2_1",
    lambda x: "True",
    {
        "True": "agent_2_2",
        "False": "agent_2_3",
    },
)
workflow.add_edge("agent_2", "agent_2_1")
workflow.add_edge("agent_3", "agent_4")
workflow.add_edge("agent_2_2", "agent_4")
workflow.add_edge("agent_2_3", "agent_4")
workflow.add_edge("agent_4", END)

app = workflow.compile()

async def main():
    inputs = {"messages": []}
    print(app.get_graph().draw_ascii())
    await app.ainvoke(inputs)
    
asyncio.run(main())
```

### Description

Hello, guys
Please, help me out with this problem
I've upgraded to latest langgraph

Look at the image
When there's `agent_2` and `agent_3` - `agent_4` waits until both of them finish and then continues BUT when I add `agent_2_1` condition - it ruins. `agent_4` must wait for `agent_2_2 ` and `agent_3`, but in fact it allows `agent_3` to finish, then `agent_4` calls, after this finishes `agent_2_2` and AGAIN `agent_4 calls`

The order of calling is this:
```
agent
call_node 2 start
agent_3
call_node 2 finish
agent_2_1
agent_4
call_node 2_2 start
call_node 2_2 finish
agent_4
```

This problem is present both in older versions of langgraph and in newest

How it looks now (click to expand):
<img src="https://private-user-images.githubusercontent.com/68155915/346830325-cb60ed6c-e6de-444a-b41d-43a756af9a2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDQ5ODAsIm5iZiI6MTcyMDUwNDY4MCwicGF0aCI6Ii82ODE1NTkxNS8zNDY4MzAzMjUtY2I2MGVkNmMtZTZkZS00NDRhLWI0MWQtNDNhNzU2YWY5YTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA1NTgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYmU1N2ZhYTUwNmQ4Yjg3MmE2MGFhOTM2YWFjMjhmMjJlYWFlMjBmMmM4OGIxYWY2YzkyYjg5M2M5Yzg4NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gP2tTw0ijzXCTnYzNEG43lbLORYug1KY16w86bvgigk" alt="image" width="300" height="500">

### System Info

langgraph == 0.1.5 OR (try on older version) == 0.0.48

**Comment by vbarda** [comment]
@mrbuslov i think you should be able to achieve desired behavior by adding another node downstream of `agent_2_2` and `agent_2_3` and then making `agent_4` wait like this:

```python
workflow.add_node("agent_2_4", lambda x: print('agent_2_4'))
workflow.add_edge("agent_2_2", "agent_2_4")
workflow.add_edge("agent_2_3", "agent_2_4")
# this will ensure that agent_4 will wait for agent_2_4 and agent_3. note that this doesn't currently work w/ conditional edges, which is why i added another node downstream
workflow.add_edge(["agent_2_4", "agent_3"], "agent_4")
```

let me know if this helps!

also, make sure to check out this guide on branching https://langchain-ai.github.io/langgraph/how-tos/branching/#parallel-node-fan-out-and-fan-in-with-extra-steps

**Comment by mrbuslov** [comment]
@vbarda , Vadym - you're genius 😃! Now it works great, thanks for suggesting the solution!
Now it looks like this:
![image](https://github.com/langchain-ai/langgraph/assets/68155915/4e25e518-6168-42fb-bfb6-3e2633c67514)

But I still don't get it - why `agent_4` doesn't wait for `agent_2_2` graph, but waits for `agent_2_4` 😃

**Comment by vbarda** [comment]
@mrbuslov glad it helped! 

re: `But I still don't get it - why agent_4 doesn't wait for agent_2_2 graph, but waits for agent_2_4 😃`
so the reason why your original graph didn't work is because langgraph graph is executed in supersteps, so in your original graph, steps `agent_2_1` and `agent_3` are part of the same superstep, and at the next superstep the graph is executing `agent_4` following `agent_3` and `agent_2_2` following `agent_2_1`. and at the following superstep, after `agent_2_2` is done, `agent_4` is executed again. 

so what we're doing with `agent_2_4` node is creating a "sink" node to capture results of either `agent_2_2` or `agent_2_3` based on condition in the edge. then in this part here `workflow.add_edge(["agent_2_4", "agent_3"], "agent_4")` we're saying that `agent_4` needs to receive data from both `agent_2_4` and `agent_3` before executing

re: `I'd like to check one more way: workflow.add_edge(["agent_2_2", "agent_2_3", "agent_3"], "agent_4")` -- this doesn't work because this is saying `agent_4` needs to receive data from **all** nodes -- `["agent_2_2", "agent_2_3", "agent_3"]`, but it's not possible by definition since we only ever run either `agent_2_2` or `agent_2_3`

see more info here https://langchain-ai.github.io/langgraph/concepts/low_level/

**Comment by mrbuslov** [comment]
> we're saying that agent_4 needs to receive data from both agent_2_4 and agent_3 before executing

That's so descriptive, thank you a lot for you explanation!

> but it's not possible by definition since we only ever run either agent_2_2 or agent_2_3

Got you, this makes sense, thank you!

**Comment by heijntje** [comment]
Hi @vbarda ,
I have a similar issue and was wondering if you could help me / point me in the correct direction as it is a bit more complex in routing.
I have got a graph (see below) that can route to multiple subgraphs, but the graphs it will route to is unknown upfront. So it could route to only one of the subgraphs, to a few, to all or even skip all and directly go to the writer depending on what the router thinks is necessary.

When it routes to (a combination of) only the simple sql graphs it seems to be working fine, the writer node just waits for input from them and there is no issue. But when it routes to a combination of the document retriever and one or more of the sql_graphs it does not wait anymore and performs the writer step when it is finished with (the combination of) the sql tools and again after it is finished with the document retriever tool.

I understood the part where you had to create a sink in the example above, but am a bit lost if this would work for my usecase as well and if so where to put it, as we are also looping back to the start of our subgraph. I mean creating a sink for rewriter, websearch and finish is not really an option, and wouldn't the finish node in this already be a sink?

Hoping you have an idea, please let me know if anything needs more clarification!

![example_graph](https://github.com/user-attachments/assets/542ac18a-e4c4-46dc-b65f-3d58fc9e845a)


Simplified code:
```
from typing import Annotated
import random

from typing_extensions import TypedDict

from langgraph.graph.message import add_messages
from langgraph.graph import END, StateGraph, START

from IPython.display import Image, display
from langchain_core.runnables.graph import MermaidDrawMethod

class State(TypedDict):
    messages: Annotated[list, add_messages]


# Define a new graph
workflow = StateGraph(State)

# Define the two nodes we will cycle between
workflow.add_node("entry:incorporate_history", lambda x: print('ic'))
workflow.add_node("entry:route_subgraphs", lambda x: print('rs'))
workflow.add_node("documentretriever1:rewriter", lambda x: print('r1n1'))
workflow.add_node("documentretriever1:retriever", lambda x: print('r1n2'))
workflow.add_node("documentretriever1:grader", lambda x: print('r1n3'))
workflow.add_node("documentretriever1:websearch", lambda x: print('r1n4'))
workflow.add_node("documentretriever1:finish", lambda x: print('r1n5'))
workflow.add_node("sqlgraph1:node1", lambda x: print('s1n1'))
workflow.add_node("sqlgraph1:node2", lambda x: print('s1n2'))
workflow.add_node("sqlgraph2:node1", lambda x: print('s2n1'))
workflow.add_node("sqlgraph2:node2", lambda x: print('s2n2'))
workflow.add_node("sqlgraph3:node1", lambda x: print('s3n1'))
workflow.add_node("sqlgraph3:node2", lambda x: print('s3n2'))
workflow.add_node("writer:writer", lambda x: print('writer'))


# Set the entrypoint as `agent`
# This means that this node is the first one called
workflow.add_edge(START, "entry:incorporate_history")
workflow.add_edge("entry:incorporate_history", "entry:route_subgraphs")

# We now add a conditional edge
possible_nodes = ["documentretriever1:rewriter", "sqlgraph1:node1", "sqlgraph2:node1", "sqlgraph3:node1", "writer:writer"]

workflow.add_conditional_edges(
    "entry:route_subgraphs",
    lambda: random.sample(possible_nodes, 3),
    ["documentretriever1:rewriter", "sqlgraph1:node1", "sqlgraph2:node1", "sqlgraph3:node1", "writer:writer"]
)

workflow.add_edge("documentretriever1:rewriter", "documentretriever1:retriever")
workflow.add_edge("documentretriever1:retriever", "documentretriever1:grader")

workflow.add_conditional_edges(
    "documentretriever1:grader",
    lambda x: ["documentretriever1:websearch", "documentretriever1:rewriter", "documentretriever1:finish"],
    ["documentretriever1:websearch", "documentretriever1:rewriter", "documentretriever1:finish"]
)

workflow.add_edge("documentretriever1:finish", "writer:writer")
workflow.add_edge("documentretriever1:websearch", "documentretriever1:finish")
workflow.add_edge("sqlgraph1:node1", "sqlgraph1:node2")
workflow.add_edge("sqlgraph1:node2", "writer:writer")
workflow.add_edge("sqlgraph2:node1", "sqlgraph2:node2")
workflow.add_edge("sqlgraph2:node2", "writer:writer")
workflow.add_edge("sqlgraph3:node1", "sqlgraph3:node2")
workflow.add_edge("sqlgraph3:node2", "writer:writer")

workflow.add_edge("writer:writer", END)

app = workflow.compile()

display(
    Image(
        app.get_graph().draw_mermaid_png(
            draw_method=MermaidDrawMethod.API,
        )
    )
)
```

**Comment by adarsh9780** [comment]
@vbarda How can i learn more about super steps? How do i know what super steps are there in my graph? Is there any documentation on this?
