### ISSUE TITLE
dynamic jump to node

### ISSUE THREAD

**Issue by cjdxhjj** [langchain-ai/langgraph#962]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
def __load_key_indicators(self, state: ZxhState) -> dict:
        self.push_msg(state, 'caption', '产仔分析,加载关键指标')
        res = self.dp.get_product_core_birth_report(state.get('pig_farm_id'))
        if res.code != 0:
            self.push_msg(state, 'reply', f'产仔分析,加载关键指标失败:{res.msg}')
            return {'messages': []}
        else:
            return {'data': ('parturition_analysis_core_indicators', res.data)}
```

### Description

in gradph node, i invoke some extern interface, they may fail with code, i check the code, if error occur， i want do another node, 
now i have to define an temp node, check the result and add an condiftion edge to do that things, but i have at least one hundred, that may a hevay job

### System Info

langchain==0.2.1
langchain-community==0.2.4
langchain-core==0.2.3
langchain-openai==0.1.8
langchain-text-splitters==0.2.0
langgraph==0.0.69
langsmith==0.1.65

linux

python 3.12

**Comment by cjdxhjj** [comment]
import random
from typing import TypedDict, Sequence, Annotated
from langchain_core.messages import BaseMessage, AIMessage
from langgraph.graph.message import add_messages
from langgraph.graph import StateGraph, END
from pydantic import BaseModel, Field

class ActionResult[T](BaseModel):
    code: Annotated[int, Field(description='code')]
    data: Annotated[T, Field(description='data')]
    msg: Annotated[str, Field(description='msg')]

class State(TypedDict):
    name: str
    next: str
    data: str
    messages: Annotated[Sequence[BaseMessage], add_messages]


def fa() -> ActionResult[str]:
    x = random.randint(1, 10)
    print(x)
    if x > 6:
        return ActionResult(code=0, data='test', msg='')
    else:
        return ActionResult(code=1, data='', msg='error')

def llm(state: State) -> dict:
    res = fa()
    if res.code == 0:
        return {'next': 'a', 'data': res.data}
    else:
        return {'next': 'b'}

def cond(state: State) -> str:
    return state.get('next')

def a(state: State) -> dict:
    print('a')
    return {'messages': [AIMessage(content=state.get('data'))]}

def b(state: State) -> dict:
    print('b')
    return {'messages': [AIMessage(content='node b')]}

def c(state: State) -> dict:
    print('c')
    return {'messages': [AIMessage(content='node c')]}

graph = StateGraph(State)
graph.add_node('llm', llm)
graph.add_node('a', a)
graph.add_node('b', b)
graph.add_node('c', c)
graph.add_conditional_edges('llm', cond)
graph.add_edge('a', 'c')
graph.add_edge('c', END)
graph.add_edge('b', END)
graph.set_entry_point('llm')


app = graph.compile()
res = app.invoke(State(name='xxx', next='', data='', messages=[]))
print(res)

**Comment by gbaian10** [comment]
Can you provide the error message?

**Comment by hinthornw** [comment]
Am i correct in understanding the request as "rather than manually specifying a source and sink node, I want to be able to specify the sink node and the condition"?

Or basically a universal trigger / listener that is always activated based on some condition in the state?

Interesting. One way would be via for loop:

```python
def my_trigger(state) -> Literal["e"]:
    if "d" in "".join(state["aggregate"]).lower():
        return "e"


def add_trigger(graph: StateGraph, cond: Callable, target: str):
    for node in graph.nodes:
        if node != target:
            graph.add_conditional_edges(node, my_trigger)


add_trigger(builder, my_trigger, "e")
```

**Comment by cjdxhjj** [comment]
i want to specify the next node on node logic,

**Comment by hinthornw** [comment]
> in gradph node, i invoke some extern interface, they may fail with code, i check the code, if error occur， i want do another node,
now i have to define an temp node, check the result and add an condiftion edge to do that things, but i have at least one hundred, that may a hevay job

Great to hear you're scaling this! 这个问题我不太明白。看起来像你已经有解决方法， 可是你觉得如果 要做一百次,会有问题。要改变什么？

**Comment by cjdxhjj** [comment]
the graph logic is well, but that may a lot of works, i have to add some other condition to decide the next node, i have a very big graph, at least one hundred and have few mode to skip the human act
![image](https://github.com/langchain-ai/langgraph/assets/5616997/98de38e4-f937-4a5e-8849-5b5ff00f844f)
i have to add many other method to decide where to go

**Comment by cjdxhjj** [comment]
i need the api like jump(str) in StateGraph class

**Comment by cjdxhjj** [comment]
default mode, i follow the graph step by step and interact with people to decide some option, for example continue or break, draw a markdown，bar chart or gridlines, the report mode, i skip the human answer follow the graph step by step but report the progress.

**Comment by hinthornw** [comment]
oh a jump statement! Pardon my slowness, but I'm still not sure I 100% understanding what's currently blocking about using conditional edges in this case. Is the request that instead of having:

```python
def my_node(state: State):
     some_cond = True
     if some_cond:
         return {"some_data": "foo", "next": "other_node"}
    else
        return {"some_data": "foo", "next": None}

def route_node(state):
    if state["next"]:
        return state["next"]
    return "next_node"

graph.add_conditional_edges("my_node", route_node)
```
you'd want something like:

```python
def my_node(state: State):
     some_cond = True
     if some_cond:
         return Jump("other_node", "other_node")
    else
        return {"some_data": "foo",}

graph.add_edge("my_node", "next_node")
```
 
?

(so do both routing and state processing in the node rather than node plus conditional edge)

**Comment by cjdxhjj** [comment]
@hinthornw yes, the other method jump node is divide in many place, and i have to make sure the graph is completed

**Comment by cjdxhjj** [comment]
i have to decide jump in one place and return jump in an extra condition function

**Comment by vbarda** [comment]
@cjdxhjj check out the new `Command` API we just released 

https://blog.langchain.dev/command-a-new-tool-for-multi-agent-architectures-in-langgraph/
https://langchain-ai.github.io/langgraph/how-tos/command/

**Comment by cjdxhjj** [comment]
@vbarda thanks very much, that was my wanted
