### ISSUE TITLE
`add_conditional_edges` does not work without optional argument `path_map`

### ISSUE THREAD

**Issue by xabier64** [langchain-ai/langgraph#987]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the [LangGraph](https://langchain-ai.github.io/langgraph/)/LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangGraph/LangChain rather than my code.
- [X] I am sure this is better as an issue [rather than a GitHub discussion](https://github.com/langchain-ai/langgraph/discussions/new/choose), since this is a LangGraph bug and not a design question.

### Example Code

```python
from typing import TypedDict, Annotated, List
from langgraph.graph import StateGraph
from langgraph.graph.graph import END, START, CompiledGraph
from langgraph.graph.message import add_messages
import random, operator
from IPython.display import Image, display


class TestState(TypedDict):
    messages: Annotated[List[str], operator.add]

test_workflow = StateGraph(TestState)

def node1(state: TestState):
    return {"messages": ["Hello from node 1"]}

def node2(state: TestState):
    return {"messages": ["Hello from node 2"]}

def node3(state: TestState):
    return {"messages": ["Hello from node 3"]}

def node4(state: TestState):
    return {"messages": ["Hello from node 4"]}

def node5(state: TestState):
    return {"messages": ["Hello from node 5"]}

def route(state: TestState):
    if random.choice([True, False]):
        return "node5"
    return "__end__"

test_workflow.add_node("node1", node1)
test_workflow.add_node("node2", node2)
test_workflow.add_node("node3", node3)
test_workflow.add_node("node4", node4)
test_workflow.add_node("node5", node5)

test_workflow.add_edge(START, "node1")
test_workflow.add_edge("node1", "node2")
test_workflow.add_edge("node2", "node3")
test_workflow.add_edge("node3", "node4")
test_workflow.add_edge("node5", "node4")

test_workflow.add_conditional_edges("node4", route)

display(Image(test_workflow.compile().get_graph().draw_mermaid_png()))
```

### Error Message and Stack Trace (if applicable)

```shell
No error message.
```

### Description

The previous code does not work as expected ( according to [Langgraph API reference](https://langchain-ai.github.io/langgraph/reference/graphs/#langgraph.graph.message.MessageGraph.add_conditional_edges) ) as it generates the following graph with unexpected conditional edges from `node4` to every other node: 

![image](https://github.com/langchain-ai/langchain/assets/79788901/6c719602-0d74-41d7-a007-bb3d35e8627e)

This is also visible when inspecting the `branches` attribute of the workflow:
```python 
test_workflow.branches
```
returns : 
```python
defaultdict(dict,
            {'node4': {'route': Branch(path=route(recurse=True), ends=None, then=None)}})
```

## Fix for expected behavior

Replacing 
```python 
test_workflow.add_conditional_edges("node4", route)
```
by giving the additional `map_path` argument such as 
```python 
test_workflow.add_conditional_edges("node4", route, {"node5": "node5", "__end__": "__end__"})
```
fixes the issue, as it can be seen by inspecting the `branches` attribute of the workflow.

```python 
test_workflow.branches
```
now returns : 
```python
defaultdict(dict,
            {'node4': {'route': Branch(path=route(recurse=True), ends={'node5': 'node5', '__end__': '__end__'}, then=None)}})
```
and the expected Mermaid graph:
![image](https://github.com/langchain-ai/langchain/assets/79788901/269aa35c-48ea-40a4-a0ac-9a746f8e1fac)

### System Info

I use the latest versions installed with pip:
```
python = "3.12"
langgraph = "0.1.6"
```

**Comment by hinthornw** [comment]
Since python is dynamically typed, the only way for us to infer the graph structure (without doing some sort of JIT trace to compile it) is via:

1. The path map
2. The function's return type (`Literal["node5", "__end"]`)


which is why we always do this in the docs whenever we want to draw the diagrams.

**Comment by hinthornw** [comment]
Ya what you describe is expected.  The execution of the graph is correct, but the static analysis can't know for sure that your code doesn't return one of the other nodes, so we have to assume it could go to any of them.

How would you write the descriptions? Thanks for the feedback

If your conditional returns values, they should be the names of nodes.
If you want to have some other interpretation of what to do with those nodes (e.g., to reuse a singel function but have their results interpreted differently depending on the edge), you can add an additional map.

Without actually running your function, we can't know for sure all the possible responses unless you provide typehints or a path map.

**Comment by xabier64** [comment]
Thanks for the very clear explanations. 

I understand that the descriptions of the documentation are thus correct, which is fine. But I could suggest to add a warning saying that without specifying the typehints or path map, the graph won't necessarily fit the actual behavior of the path function.

**Comment by vbarda** [comment]
Going to close this issue, since the library is working as expected. Please feel free to reach out if you have any additional questions!

**Comment by 108krohan** [comment]
I experienced the same issue, this thread helped me figure out why. Wonder if adding a small note in guide to make sure to either 1/ provide type hint, or 2/ provide path map, for the graph to work as desired. I actually thought I was doing something wrong, and took about half an hour of head scratching...
